### ISSUE TITLE
Trouble with multiple paragraphs in same section

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#1]
I am having trouble finding out how to start a new paragraph for cases where there are multiple paragraphs in the same section (or subsection, subsubsection, etc.) in the SRS. I tried creating two separate "Paragraph" LayoutObjs but the second one started on the same line as where the first ended, whereas I want it to start on a new, indented line. Is it possible to do that?

@szymczdm Tagging Dan because I am not sure if simply opening an issue alerts anyone.

Brooks

**Comment by bmaclach** [comment]
Update: Using HARDNL does not work because it does not indent the new line.

**Comment by szymczdm** [comment]
This should now be fixed.
