### ISSUE TITLE
TeX math mode dollar signs

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#10]
Drasil does not currently write dollar signs for symbols requiring math mode (such as those with subscripts, Greek letters, etc.)

Luthfi

**Comment by szymczdm** [comment]
I've looked into it. I'll be fixing this soon. Just need to track down how to fix it.

**Comment by szymczdm** [comment]
Turns out this one will need some non-trivial design. I spoke with Jacques about it today and he said he would look into a few things related to the design and get back to me. I'm posting this comment to act as a reminder, since this is high priority.

**Comment by JacquesCarette** [comment]
As far as I can tell, this is now fixed.   There might be some tweaks still to be done, but generally, the infrastructure is in place.

**Comment by bmaclach** [comment]
I found 2 instances where the dollar signs still are not placed correctly. First, dollar signs for fractions are currently causing errors. Here is a sample of the generated LaTeX code from my table of symbols:
```
$C$ & specific heat capacity & \frac{J}{(kg${}^{\circ}C$)}
```
To get this to work, the dollar signs should be placed on either side of the fraction, with the dollar signs within removed, like so:
```
$C$ & specific heat capacity & $\frac{J}{(kg{}^{\circ}C)}$
```
The other error is with equations. Equations in the LaTeX document currently appear like this:
```
\begin{equation}
$E_{P}=\int_{0}^{t}{h_{P}A_{P}(T_{W}(t)-T_{P}(t))}$
\end{equation}
```
When using the equation structure, dollar signs shouldn't be there at all, so it should look like this:
```
\begin{equation}
E_{P}=\int_{0}^{t}{h_{P}A_{P}(T_{W}(t)-T_{P}(t))}
\end{equation}
```
I'm not sure if these are what you referred to when you said there might be some tweaks still to be done, but just in case I thought I should report them here.

**Comment by JacquesCarette** [comment]
Could you create a new issue with these (and assign it to me)?  I'll try to get to these asap.
