### ISSUE TITLE
Implement getSymb and getUnit

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#101]
@JacquesCarette I could use a hand with this one, mainly getting the Maybe to work.

I have the following at the moment:
```
class NamedIdea c => Quantity c where
  typ      :: Simple Lens c Space
  getSymb  :: SymbolForm s => Simple Lens c s
```
Getting the "Maybe" part of it to work is what I'm having trouble with. I thought the obvious way to do this would be to wrap a Maybe around the entire lens; either we have a lens that returns a SymbolForm, or we have Nothing.
`  getSymb :: SymbolForm s => Maybe (Simple Lens c s)`

This doesn't work because GHC says:
```
Illegal polymorphic type: Simple Lens c s
GHC doesn't yet support impredicative polymorphism
When checking the class method:
   getSymb :: forall c. Quantity c => forall s. SymbolForm s => Maybe (Simple Lens c s)
```

The other way to implement that I can think of would be to have:
`  getSymb :: SymbolForm s => Simple Lens c (Maybe s)`

I think this would work as long as we're careful with our data structures, but I have a nagging feeling something is going to go wrong. I'm going to try this one for now, and hope that it goes smoothly, but if you see something wrong with my thought process, please let me know.

**Comment by szymczdm** [comment]
I just realized the first thing wrong with my thought process, getSymb should strictly be a getter; We only want to return the "chunk" that is a SymbolForm for the given Quantity.

**Comment by JacquesCarette** [comment]
Right - 
`getSymb :: SymbolForm s => c -> Maybe s`
is all you need.

**Comment by JacquesCarette** [comment]
`getSymb` is now implemented and pushed.  Interestingly, this should allow us to get rid of MUChunk!
