### ISSUE TITLE
Create a better way to handle acronyms.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#103]
Right now acronyms are concept chunks with "term" set to the acronym and "defn" set to the expanded form of the acronym. Really, we want the "term" to be the expanded form of the acronym, and the "defn" should be a description of what that is. Then we should also have a field for the acronym (might be worth creating a new class and making our acronym concept chunks into instances of it).

**Comment by JacquesCarette** [comment]
Right - that's a hack.  Acronyms are a special kind of synonym, and we should have a way to deal with those.  I think acronyms/synonyms should have their own representation, and should be a kind of reference.

**Comment by szymczdm** [comment]
Just wanted to note: Data.Drasil.Concepts.Documentation will need to be overhauled when this is implemented.

**Comment by szymczdm** [comment]
Forgot to close this when "getA" was implemented in NamedIdea.
