### ISSUE TITLE
Re-build the chunks from the examples as necessary

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#105]
Need to essentially re-implement the existing example chunks for a number of reasons, but it basically boils down to the original implementation used inconsistent naming conventions, chunks duplicate information (ie. term and defn are identical, or id and term), and the examples used things like "id" when they shouldn't have.

@smiths I will most likely need your help in determining what (exactly) should be captured in each chunk that isn't already complete. I'll bring up any issues as I come across them.

**Comment by smiths** [comment]
Hello Dan.  Yes, please let me know if you have any questions about any of the incomplete chunks.

**Comment by szymczdm** [comment]
I'm just setting up a list here for now. Some of these I'll be filling in shortly as they're straightforward. Anyone should feel free to chime in with definition ideas.

The currently undefined terms in Data.Drasil are:

- surface
- restitution coefficient
- acceleration (and angular acceleration)
- moment of inertia
- force
- impulse (vector and scalar)
- position
- distance
- displacement (and angular displacement)
- time
- torque
- gravitational acceleration
- gravitational constant
- mass
- length
- heat transfer
- specific heat capacity
- latent heat
- sensible heat

Note: There are most likely some terms with bad definitions in among the rest, but those will take a deeper look to suss out.

I'll be looking at the example-specific chunks after implementing some/most of the above.

**Comment by szymczdm** [comment]
This and #93 are now saying pretty much the same thing, so I'm going to close this one as it's essentially a duplicate.
