### ISSUE TITLE
Create "abbreviated" class

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#106]
Probably a good idea to have a class for abbreviations. I'm thinking they'll need to be NamedIdeas at bare minimum.

**Comment by JacquesCarette** [comment]
Well, they could be slightly different, in that they need an `id`, a `term` (for the abbreviation) and a *link* to what it abbreviates (which would be a `NamedIdea` at a minimum).  The link idea is likely to come up again and again, so we need to think about that.

**Comment by szymczdm** [comment]
That makes sense, it would make it much easier for when we eventually run a pass over our recipes to pull out chunks and automatically create our table of acronyms/abbreviations.

**Comment by szymczdm** [comment]
Seeing that we can already automatically generate the table of abbreviations and acronyms, I'm going to consider this a non-issue as of now. It was created before we had proper abbreviations/acronyms. If it comes up later I will reopen or create a new issue for the then-current design.
