### ISSUE TITLE
How should fundamental concepts be handled in a table of symbols?

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#107]
This issue appeared while working on commit 38f7287 and was stated as follows:

Should fundamental concepts like "mass" or "time" have their definition printed in the table of symbols, or should we simply use the term? Or both? Currently, printing the symbol and defn means the term never appears, even though it is used in (possibly) other symbol definitions!

For example:
```
symbol | defn
     m | the quantity of matter in a body
   m_W | the mass of water in the system
```

**Comment by JacquesCarette** [comment]
I don't understand how the example connects with the problem?

In any case: the table of symbols should contain all the symbols that occur in the documents, at least by default.  It does make sense to also allow some kind of 'transitive closure' that also adds all the symbols that would occur if we expanded everything out.

**Comment by szymczdm** [comment]
I didn't mean adding all the symbols by expansion. I was actually referring to our table of symbols definitions. Each symbol has it's definition next to it, but some of the definitions (like the one for mass above) don't explicitly name the concept. 

So if one were to not understand that "m" is "mass" then there would be no explicit link between "m" and "m_W". This example is trivially simple, but if we were to swap "m" for "C" and only use the definition, things could become very unclear.

Essentially I think there is a problem with some of the tables of symbols in the examples since they use definitions instead of terms. However, in the examples it actually makes sense to do things that way (though that may change after the second pass I'm currently working on).

**Comment by JacquesCarette** [comment]
We'll need to talk about this on Friday - I am still fuzzy about the details.  I think I understand, but I also have enough doubt about my guess that this warrants an in-person discussion.

**Comment by szymczdm** [comment]
Agreed. I'm having trouble coming up with a clear explanation/example right now.

**Comment by szymczdm** [comment]
My understanding of this issue has been resolved as of the inclusion of the termExcept/defnExcept functions.
