### ISSUE TITLE
Handle "word" representations based on grammar rules. 

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#108]
As we discussed in our previous meeting we need to take our terms/words/combinations of letters that we reference via chunks and create some means of handling simple grammar rules around them. The simplest example of this is having a word at the beginning of a sentence vs. in the middle would change the capitalization (unless it is a proper name).

This will need a bit of design to ensure a good implementation can be made as the wrong design has the possibility of wreaking havoc on the current implementation of Drasil.

**Comment by szymczdm** [comment]
First pass at this is done (with NounPhrases), I just need to finish implementing modifiers (#129), then we can go from there.

**Comment by njericha** [comment]
This is done using functions from `Data\Drasil\SentenceStructures.hs` and as mentioned, #129 will add the missing verbs, verb modifiers (adverbs), and noun modifiers (adjectives).
