### ISSUE TITLE
Quotation marks within a sentence

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#11]
As discussed in the meeting on May 25th, there should be a method for adding quotation marks within a Sentence that will work for both SRS and HTML documents.

Note: I tried using \" and this did indeed work for both .tex and HTML, so this might not be a real issue.

**Comment by szymczdm** [comment]
We will need a means for adding quotation marks. This is low priority for the time being though. The main problem is that TeX open quotation should be `` whereas HTML would use ".

**Comment by szymczdm** [comment]
Done.
