### ISSUE TITLE
Refine orgSec

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#110]
Currently (as of commit: 4d5c7769cc7f6dc0f2) the orgSec / orgSecWTS functions in the module "Drasil.OrganizationOfSRS" are useful for fairly simple and straightforward sections (like those found in Chipmunk and GlassBR), however, they'll need to be refined to generalize the other examples (SSP, SWHS).

Not sure if this is an issue with the template we're using for the SRS or not (ie. Should certain information be arranged in a certain order, then followed by other system-specific information?). I think it would be worth looking into.

**Comment by JacquesCarette** [comment]
Actually, I am finally starting to figure out how to properly do recipes.  And it does not directly involve templates (which would indeed make this complicated), but rather writing an actual 'program' (in an as yet to be defined language) of 'document assembly'.  Such a language would make adding optional information much easier than using templates.

**Comment by szymczdm** [comment]
I'm not sure I get exactly what you mean, but using something other than templates sounds like a great idea because they've already started being a headache.

**Comment by njericha** [comment]
d7b0736369d01cbd78c56b2ddf8cb5ae0c52b8c2 Fixed SSP

**Comment by njericha** [comment]
d7b0736369d01cbd78c56b2ddf8cb5ae0c52b8c2

**Comment by njericha** [comment]
@danscime should be able to fix this now that we've gone through and updated this function

**Comment by danscime** [comment]
SWHS updated as of 5010bcbe09b716f9785b29c7b543e335c2c8e30b
