### ISSUE TITLE
Drasil redesign

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#111]
[new_design2.pdf](https://github.com/JacquesCarette/literate-scientific-software/files/750852/new_design2.pdf)

**Comment by szymczdm** [comment]
Just adding the photo of the board from today's meeting as well.

![img_20170203_111934](https://cloud.githubusercontent.com/assets/235140/22605222/e507e8b8-ea1c-11e6-88cb-7bcc8df6071c.jpg)

**Comment by smiths** [comment]
Actual implementation is a variation on this.  Key words queries, choices.  Okay to close.
