### ISSUE TITLE
CommonIdea

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#112]
We currently have that a NamedIdea may have an abbreviation.  This is good.  But there are times when there are ideas around which we insist *must* have an abbreviation.  Cueing from the definition
> Any convenient short form used as a substitution for an understood or inferred whole.

from https://en.wiktionary.org/wiki/abbreviation, I think we should introduce a sub-class of NamedIdea which assuredly has an abbreviation.  [Note that reading about the generic concept of abbreviation at https://en.wikipedia.org/wiki/Abbreviation is rather informative].  We make heavy use of "must have" abbreviations in our referencing system, for example.

One of the combinators we should have (on NamedIdea!) is `short`, which will return the abbreviation (if it exists), otherwise the term.  We can then use `short` while constructing "templates" for the more informal sentences that make up the SRS.

**Comment by szymczdm** [comment]
Sounds good. I take it we'll also need to create a new data structure for Concepts which are an instance of this new sub-class as well?

On another note, what should we name the sub-class? My first thought was "Short"/"ShortForm", though that doesn't sound very descriptive, and other names like "AbbreviatedIdea" don't sound great to me.

**Comment by JacquesCarette** [comment]
I meant to use `CommonIdea` for that class.  An idea becomes 'common' when it has a short form.

And yes, it will need a new data-structure.

**Comment by szymczdm** [comment]
This issue has been resolved as of the inclusion of Language.Drasil.Chunk.CommonIdea
