### ISSUE TITLE
Should we split up Chunk.hs?

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#114]
Chunk.hs is starting to get a bit crowded, I'd like to partition it out in a meaningful way.

I think it should be split something like:

Chunk.hs -- Keep Chunk, NamedIdea, and SymbolForm (and associated data structures). These are the "base" chunks from which everything else springs.

Create: Concept.hs and CommonIdea.hs for their respective classes and data structures. Note: CommonIdea has no data structures as of yet, but that will change very soon.

Does this sound good? Or is it unnecessary?

**Comment by JacquesCarette** [comment]
Good idea.  I would even be fine with a smaller splitting (i.e. NamedIdea and Symbol form).

**Comment by szymczdm** [comment]
Alright, I think I will go with the smaller splitting.

**Comment by szymczdm** [comment]
Done as of b263d18
