### ISSUE TITLE
Remove plural hacks from Spec.hs and update the examples

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#115]
Just a reminder that the current examples are hacked into having working plurals. Those should be removed and replaced with NounPhrases.

**Comment by njericha** [comment]
I just noticed sPlur is defined in Spec.hs and NounPhrase.hs, can we delete the ones in Spec.hs?

**Comment by szymczdm** [comment]
Once all the examples have removed it, yes. Deleting it from Spec will be a priority. If you can confirm it doesn't break things, delete it!

**Comment by njericha** [comment]
Resolved: see commit 45cf7530b
