### ISSUE TITLE
Capitalization of definitions

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#117]
Just ran into this while trying to remove a few sLower instances. Definitions need to have some means of capitalization changing (ie. mid-sentence vs at start). See glassBR (Body.hs line: 328)

**Comment by njericha** [comment]
Can this be closed now that `sLower` is removed and we can use `at_start` to capitalize? @szymczdm

**Comment by JacquesCarette** [comment]
I believe so!

**Comment by njericha** [comment]
Tentatively closing. If needed Dan can reopen
