### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#118]
With the summer students starting soon, it seems like a good time to update the README file with practical information.  I think we should add instructions for building Drasil and running the case studies.  It would also be nice to have an explanation of the contents of each of the folders at the top level.  If there is a folder we don't need any more, we should consider removing it.
The answers to any practical questions that the summer students ask should be recorded in the README, so that this information is captured for future users/developers.

**Comment by szymczdm** [comment]
Sounds good. I'm also going to add a few style notes (for writing in Drasil) which I think would come in handy for updating things later on (i.e. so things like find and replace will find every instance of something)

**Comment by smiths** [comment]
Yes, your style notes are a great idea.  Anything we can do to make things more consistent is good.  By recording this information in the repo, we won't have to repeat it in the future when similar questions come up.

**Comment by JacquesCarette** [comment]
This is great.  What is missing from the README (at the start!) is an actual description of what the project is all about.
