### ISSUE TITLE
Break up design doc template?

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#119]
When I originally implemented the generation of the design doc, I made it as one big generation template since all of the example documents were so similar (the paragraphs and sections in all of the documents are virtually identical and the only thing that changes is the list/descriptions of modules and the entries in tables and graphs).  Unfortunately this makes it difficult to make any changes to the inputs since they are repeatedly passed along and manipulated through the template.  

I'm working on cleaning up the examples for the design doc but the way it is now makes changing anything very tedious.  Would it be best if I pull the design doc generation out of Language.Drasil and break it up into individual pieces and place them alongside TableOfSymbols.hs/TableOfUnits.hs/etc. in Example.Drasil, rather than keeping this large rigid template?  

Also, is this where those pieces would belong, or should these go into a library like Data.Drasil -- maybe Document.Drasil?

**Comment by JacquesCarette** [comment]
Yes, pull them out of Language.Drasil.  Some parts should go into Data.Drasil.Document (for the things which is really basic to all documents); some parts should go into Examples.Drasil, for those things which correspond to 'our' templates, but may not necessarily be re-used by anyone else.

**Comment by smiths** [comment]
Close by #413
