### ISSUE TITLE
Test "make" on Linux and OSX

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#121]
Now that Henry and I have got the OSX build working on his machine, we need to check if it will work on the others. I have a feeling we will run into some problems, so I need everyone to pull the most recent version and try to `make` (inside the code folder).

If/when it fails, please let me know what the error is by posting it here. Also, please check inside your .stack-work folder for something along the lines of:

`.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build` and let me know what the full path to the build folder is.

Thanks!

**Comment by smiths** [comment]
Hi Dan.  I pulled the most recent version and I believe that everything worked.  There were some errors, but I believe those are known errors.  I'll attach the full output of make, in case my assumption is incorrect.  As far as the folder for the work, it is the same as the one you suggested:

.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build

Full output of make:

drasil-0.0.6: unregistering (components added: exe:swhs)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
make: [swhs] Error 1 (ignored)
make: [swhs] Error 1 (ignored)
make: [swhs] Error 1 (ignored)
make: [swhs] Error 1 (ignored)
make: [swhs] Error 1 (ignored)
drasil-0.0.6: unregistering (components added: exe:tiny)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
drasil-0.0.6: unregistering (components added: exe:ssp)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
drasil-0.0.6: unregistering (components added: exe:glassbr)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
make: [glassbr] Error 1 (ignored)
make: [glassbr] Error 1 (ignored)
make: [glassbr] Error 1 (ignored)
drasil-0.0.6: unregistering (components added: exe:chipmunkdocs)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
make: [gamephys] Error 1 (ignored)
make: [gamephys] Error 1 (ignored)
drasil-0.0.6: unregistering (components added: exe:pcm)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...

**Comment by szymczdm** [comment]
@hmadej . @smiths could you test the version I just pushed (commit 0a63045c1de7af05e006bccfafecc06ce60ae929). If it works (I had issues with the exec command before, but it seems to be working) then we should be good on all OS.

**Comment by JacquesCarette** [comment]
It is going to take a bit of work for me to do this.  My version of Ubuntu only comes with GHC 7.8.4, so I'll need to update that first.

**Comment by hmadej** [comment]
Latest version (commit 0a63045) works for me.

**Comment by szymczdm** [comment]
Alright @JacquesCarette , no real rush (except for when you want to test things :) ). I can spin up one of my old Linux VMs to test it right now, and I'm sure Steven will test it when he gets a chance since he's probably up-to-date.

**Comment by JacquesCarette** [comment]
I needed to update anyways.  Stack is installed, I'm currently installing ghc.

**Comment by smiths** [comment]
Hello Dan.  I'm not sure what you are looking for in the output of make.  There are some error messages, but I think they are the "known" errors.  I'll attach the full output of make:

stack build :swhs
drasil-0.0.6: unregistering (components added: exe:swhs)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
stack exec swhs
diff --strip-trailing-cr ./stable/swhs/SWHS_SRS.tex ./SRS/SWHS_SRS.tex &> SWHS_log.log
make: [swhs] Error 1 (ignored)
diff --strip-trailing-cr ./stable/swhs/SWHS_MG.tex ./MG/SWHS_MG.tex >> SWHS_log.log 2>&1
make: [swhs] Error 1 (ignored)
diff --strip-trailing-cr ./stable/swhs/SWHS_SRS.css ./Website/SWHS_SRS.css >> SWHS_log.log 2>&1
diff --strip-trailing-cr ./stable/swhs/SWHS_SRS.html ./Website/SWHS_SRS.html >> SWHS_log.log 2>&1
make: [swhs] Error 1 (ignored)
diff --strip-trailing-cr ./stable/swhs/SWHS_SRS2.tex ./SRS/SWHS_SRS2.tex >> SWHS_log.log 2>&1
make: [swhs] Error 1 (ignored)
diff --strip-trailing-cr ./stable/swhs/SWHS_SRS2.css ./Website/SWHS_SRS2.css >> SWHS_log.log 2>&1
diff --strip-trailing-cr ./stable/swhs/SWHS_SRS2.html ./Website/SWHS_SRS2.html >> SWHS_log.log 2>&1
make: [swhs] Error 1 (ignored)
stack build :tiny
drasil-0.0.6: unregistering (components added: exe:tiny)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
stack exec tiny
diff --strip-trailing-cr ./stable/tiny/SRS.tex ./SRS/SRS.tex &> log.log
diff --strip-trailing-cr ./stable/tiny/MG.tex ./MG/MG.tex >> log.log 2>&1
diff --strip-trailing-cr ./stable/tiny/SRS.css ./Website/SRS.css >> log.log 2>&1
diff --strip-trailing-cr ./stable/tiny/SRS.html ./Website/SRS.html >> log.log 2>&1
stack build :ssp
drasil-0.0.6: unregistering (components added: exe:ssp)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
stack exec ssp
diff --strip-trailing-cr ./stable/ssp/SSP_SRS.tex ./SRS/SSP_SRS.tex &> SSP_log.log
diff --strip-trailing-cr ./stable/ssp/SSP_MG.tex ./MG/SSP_MG.tex >> SSP_log.log 2>&1
diff --strip-trailing-cr ./stable/ssp/SSP_SRS.css ./Website/SSP_SRS.css >> SSP_log.log 2>&1
diff --strip-trailing-cr ./stable/ssp/SSP_SRS.html ./Website/SSP_SRS.html >> SSP_log.log 2>&1
stack build :glassbr
drasil-0.0.6: unregistering (components added: exe:glassbr)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
stack exec glassbr
diff --strip-trailing-cr ./stable/glassbr/GlassBR_SRS.tex ./SRS/GlassBR_SRS.tex &> GlassBR_log.log
make: [glassbr] Error 1 (ignored)
diff --strip-trailing-cr ./stable/glassbr/GlassBR_MG.tex ./MG/GlassBR_MG.tex >> GlassBR_log.log 2>&1
make: [glassbr] Error 1 (ignored)
diff --strip-trailing-cr ./stable/glassbr/GlassBR_SRS.css ./Website/GlassBR_SRS.css >> GlassBR_log.log 2>&1
diff --strip-trailing-cr ./stable/glassbr/GlassBR_SRS.html ./Website/GlassBR_SRS.html >> GlassBR_log.log 2>&1
make: [glassbr] Error 1 (ignored)
stack build :chipmunkdocs
drasil-0.0.6: unregistering (components added: exe:chipmunkdocs)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
stack exec chipmunkdocs
diff --strip-trailing-cr ./stable/gamephys/Chipmunk_SRS.tex ./SRS/Chipmunk_SRS.tex &> Chipmunk_log.log
make: [gamephys] Error 1 (ignored)
diff --strip-trailing-cr ./stable/gamephys/Chipmunk_MG.tex ./MG/Chipmunk_MG.tex >> Chipmunk_log.log 2>&1
diff --strip-trailing-cr ./stable/gamephys/Chipmunk_SRS.css ./Website/Chipmunk_SRS.css >> Chipmunk_log.log 2>&1
diff --strip-trailing-cr ./stable/gamephys/Chipmunk_SRS.html ./Website/Chipmunk_SRS.html >> Chipmunk_log.log 2>&1
make: [gamephys] Error 1 (ignored)
stack build :pcm
drasil-0.0.6: unregistering (components added: exe:pcm)
drasil-0.0.6: build
Preprocessing library drasil-0.0.6...
Preprocessing executable 'chipmunkdocs' for drasil-0.0.6...
Preprocessing executable 'glassbr' for drasil-0.0.6...
Preprocessing executable 'pcm' for drasil-0.0.6...
Preprocessing executable 'ssp' for drasil-0.0.6...
Preprocessing executable 'swhs' for drasil-0.0.6...
Preprocessing executable 'tiny' for drasil-0.0.6...
drasil-0.0.6: copy/register
Installing library in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/lib/x86_64-osx-ghc-8.0.2/drasil-0.0.6-AkbXHZWzOz36lG44xlYli9
Installing executable(s) in
/Users/smiths/Repos/litNew/code/.stack-work/install/x86_64-osx/lts-8.12/8.0.2/bin
Registering drasil-0.0.6...
stack exec pcm
diff --strip-trailing-cr ./stable/pcm/PCM_SRS.tex ./SRS/PCM_SRS.tex &> PCM_log.log
diff --strip-trailing-cr ./stable/pcm/PCM_SRS.css ./Website/PCM_SRS.css >> PCM_log.log 2>&1
diff --strip-trailing-cr ./stable/pcm/PCM_SRS.html ./Website/PCM_SRS.html >> PCM_log.log 2>&1
sh log_check.sh
-------------------------------------------
- SWHS_log.log IS NOT EMPTY -- DIFFERENCE
- BETWEEN GENERATED AND STABLE OUTPUT FOUND
-------------------------------------------
-------------------------------------------
- GlassBR_log.log IS NOT EMPTY -- DIFFERENCE
- BETWEEN GENERATED AND STABLE OUTPUT FOUND
-------------------------------------------
-------------------------------------------
- Chipmunk_log.log IS NOT EMPTY -- DIFFERENCE
- BETWEEN GENERATED AND STABLE OUTPUT FOUND
-------------------------------------------
-------------------------------------------
- ERROR IN GENERATED OUTPUT SEE ABOVE FOR -
-             MORE DETAILS                -
-------------------------------------------

**Comment by szymczdm** [comment]
@smiths yours is working properly, so there's no problem there :D I was having issues with some build directories having different names (so the executables weren't running), but I believe it is all cleared up now. Essentially, since I didn't have OSX I couldn't be sure it had worked.

**Comment by JacquesCarette** [comment]
Looks like it worked (with the expected failures) on Linux.  And as a bonus, I now have stack and GHC 8.0 installed.  I'll update my other machines later.

**Comment by palmerst** [comment]
Works for me on Windows 7 & Ubuntu.

**Comment by szymczdm** [comment]
Alright, I got it to work on Linux Mint (which is considered an 'unsupported' distro for stack) as well as my Win7, so I think we can consider it working. 

Should any other problems arise, they're likely machine-specific and not an issue with the Makefile itself.
