### ISSUE TITLE
NamedIdea of' pluralizes second term, no alternative of available 

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#122]
of' pluralizes second term:
Purpose of Document -> Purpose of Documents
this does not match the stable example.

of_ does not use Nounphrase does not match type signature of of'. 

when changed will affect:
orgOfDoc
prpsOfDoc 
in Documentation.hs

**Comment by szymczdm** [comment]
Should be fixed as of b4ea5efae0a5e7791e11deefce36ad4f37ff2680
