### ISSUE TITLE
create "introduce abbreviation" combinatoric

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#123]
This line for example,
S "of the" +:+ (titleize srs) +:+ S "(" :+: (short srs) :+: S ")" +:+
can be made less awkward with a single function that does this step all at once. 
So could do something like, 
(introAbb srs) =>
S "Software Requirements Specification (SRS)"

**Comment by JacquesCarette** [comment]
combinator.  Should probably be split into a combinator to parenthesize, another to concatenate a titleized version to its parenthesized short version.  Whether we want to add "of the" to that is an interesting design question.

**Comment by szymczdm** [comment]
I think the "of the" was a copy-paste accident. We discussed this combinator this morning, and I was already thinking we should have it in two pieces, so I'll get on that.

**Comment by JacquesCarette** [comment]
:smiley: :+1:

**Comment by szymczdm** [comment]
Done. See 309979458e82b02d5a7888919cea1b721c9364e0. Also, the parenthesis wrapping did already exist, it's `sParen`
