### ISSUE TITLE
Inconsistent Nouns Defined in documentation.hs

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#125]
I am not sure if this is an existing issue for this but in /Data/Drasil/Concepts/Documentation.hs, noun phrases like "physical system description" are defined as a commonINP on line 16 where as "specific system description" is defined as a compoundNPNC on line 59. These two ideas should be defined similarly given they are of the same form with an adjective at the start?

**Comment by JacquesCarette** [comment]
It's a work in progress.  Well spotted.

**Comment by szymczdm** [comment]
Presently they are defined differently for a reason which essentially boils down to: physical system description comes up in the documentation several times where it *requires* an abbreviation ("must have" not "may have"), which is where common ideas come into play. The others do not *require* an abbreviation (that we know of), though it would be simple enough to add them.

However! You are entirely correct about them being some adjective + the same nounPhrase. Which means we will use our compoundNPNC `systemdescription` with an adjective combinator to build "general system description", "specific system description", and "physical system description" chunks.

**Comment by szymczdm** [comment]
I think we've solved this particular issue (the inconsistency was due to the nature of the information necessitating an abbreviation), and the implementations of modifiers will be covered alongside #129
