### ISSUE TITLE
normal vector inconsistent across examples

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#126]
in Quantities/Math.hs the normal vector symbol is defined as (vec $ hat LN) but, in the gamephys example the normal vector symbol is just (vec LN), shouldn't these two definitions be consistent with one another? if so which one?

This inconsistency currently breaks gamephys vs the stable.

**Comment by hmadej** [comment]
also  displacement unit vector vs unit displacement vector.

**Comment by szymczdm** [comment]
Great finds!

**Comment by hmadej** [comment]
also the difference between a perpendicular vector vs a normal vector? they seem to mean the same thing, but both are used.

**Comment by JacquesCarette** [comment]
Those are, I believe, synonyms.  Being able to have synonyms is another wanted feature, which could be used to make the document "read better".  I think there is already an issue about that -- try to hunt it down and link it to this one?

**Comment by hmadej** [comment]
related to issue #90

**Comment by hmadej** [comment]
Definition in datarefs.ha:
"is the angular velocity of a rigid body as a function of time t (s), also equal to the derivative of its angular displacement with respect to time t" 
Definition in physics.hs:
 "The rate of change of a body's orientation."

Seems like one is the "short" definition of the other.

**Comment by JacquesCarette** [comment]
This latest comment is about angular velocity, not normal vector, no?  That should be a separate issue.

**Comment by smiths** [comment]
I agree with Jacques that we should have one question per issue.  Reading through the above, I'm not sure what has been addressed and what is still pending.

As far as normal vectors, unit vectors and perpendicular vectors go, these are separate concepts.  A unit vector has a magnitude of 1.  The direction of the vector is not relevant.  If its length is 1, it is a unit vector.  Unit vectors are often represented with a "hat" over the vector's symbol.  This is a notation that might change from project to project, but within a project, we should be consistent.

A normal vector is one that is perpendicular to a surface.  The normal vector is perpendicular to the tangent vector that is parallel to the surface.  A normal vector is often calculated to have a length of 1, but this isn't required for a vector to be normal.  Many normal vectors are also unit vectors, but this isn't required by the terminology.  I don't know if in the particular example we are discussing whether the normal vector is also a unit vector.  If it is, it should also get a "hat."

A perpendicular vector is one that is at right angles to another vector.  The dot product between perpendicular vectors is equal to zero.  A normal vector is defined by being perpendicular to the tangent vector, but the concept of perpendicular is more general than this.  Given any vector we can calculate vectors that are perpendicular to it.

I'll hold off on commenting on angular velocity until we have a separate thread for that discussion.

**Comment by hmadej** [comment]
new issue for angular velocity and similar definitions #131

**Comment by szymczdm** [comment]
@hmadej is this issue still open? If so, what needs to be done?

**Comment by hmadej** [comment]
used parametrized unital hack to get around this.

**Comment by szymczdm** [comment]
Alright, seeing as we have an issue for implementing proper parameterized unitals (#91) , I'm going to close this one and we'll make the appropriate modifications to remove the hack when #91 is complete.
