### ISSUE TITLE
Function to Plural an Abbreviation Needed?

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#127]
Example/Drasil/SWHS/Modules.hs/Line 68: ... (short ode) :+: S "s using the parameters" ... 
This is a hack I noticed while removing AddS in commit 45cf7530b and it shows up throughout this file and in SWHS/Body.hs. Is there any way to fix this since "plural" doesn't work on Sentences? Maybe something like short'.

**Comment by JacquesCarette** [comment]
I am unaware of a non-hack method of fixing this.

**Comment by szymczdm** [comment]
There is no non-hack way to fix this, and I'm going to say this should be low priority for the time being, until I have a chance to think about it. Seems like it would require a pluralization scheme similar to that used by NounPhrases.

**Comment by smiths** [comment]
Low priority, hack solution.  Okay to close.
