### ISSUE TITLE
Keep definition with term?

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#128]
So here is our output vs. stable output:

427c427
< Description & $H_{f}$ is the amount of thermal energy required to completely melt a unit mass of a substance.\newline$Q$ is the latent heat energy\newline$m$ is the mass
---
> Description & $H_{f}$ is the FIXME: MISSING TERM - FOR MORE INFORMATION SEE Drasil.SWHS.DataDefs\newline$Q$ is the latent heat energy\newline$m$ is the mass

Do we want to use that definition with the term or get rid of it or I'm not too sure...

**Comment by szymczdm** [comment]
We should have the "correct" definition in place, i.e. "amount of thermal energy required to completely melt a unit mass of a substance.".
