### ISSUE TITLE
Nouns as Verbs?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#129]
Some words can appear as more than one class (i.e. noun, verb, adjective) within a given line of text.  I am not sure if someone has mentioned this already but it may be wise to create a new function to handle/categorize these kinds of words.  An example can be seen in the PCM Body.hs in the s4_intro paragraph with the line `S "instance" +:+ (phrase $ model ^. term) +:+ S "(ODE) that models the solar water heating tank."`.  Note that model is used as both a noun and a verb.

**Comment by JacquesCarette** [comment]
And those are *different concepts*.  Right now, our `NamedIdeas` are all nouns.  We do not have good representations for modifiers of nouns (aka adjectives), verbs, or verb modifiiers (aka adverbs).  We have not needed them sorely enough.  Looks like we are rapidly getting there!

**Comment by smiths** [comment]
Close for now. It will come up again when it is necessary/relevant.  Parameterized unitals will likely come before #91 .
