### ISSUE TITLE
Label/Symbol mix-up in Data Definitions

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#13]
When Data Definitions are printed in TeX, the symbol is placed in a row called "Label" and the label only appears as part of the Refname row.

In HTML, the row called "Label" displays "DD: " followed by the symbol. The actual label does not appear at all (by label I mean the short name of the data, for example "Heat flux out of coil").

**Comment by szymczdm** [comment]
This was a design choice as HTML can hyperlink across documents, so there's no need for a refname. I will, however, fix the label in the HTML output soon, so that it does not show "DD:". It may eventually come back (or refname may be added in the future) if deemed necessary.

**Comment by szymczdm** [comment]
Made the change to no longer show "DD: " in the HTML output. Closing this issue for now, if something comes up later we can reopen.

**Comment by bmaclach** [comment]
Thanks Dan. The other problem I was referring to here was that I think the entire "Label" field should be called "Symbol". This is just a very small issue, but I think it's worth mentioning because elsewhere in the document (for example with the Theoretical Models), the "Label" field contains words describing what the symbol represents, so just for consistency we might want to make that change.
