### ISSUE TITLE
Similar but different definitions in datarefs.hs and physics.hs

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#131]
For angular velocity
Definition in datarefs.ha:
"is the angular velocity of a rigid body as a function of time t (s), also equal to the derivative of its angular displacement with respect to time t"
Definition in physics.hs:
"The rate of change of a body's orientation."

Discussed this with Dan on Friday, the main difference in definitions being the "a rigid body".

There are a few other examples similar to this. Linear displacement vs linear displacement "of a rigid body" etc...

**Comment by smiths** [comment]
The fact that the body is rigid is a necessary assumption for some parts of the theory.  For instance, for a rigid body all points within the body will always be displaced by the same amount.  The angles will be different, but they can all be predicted by knowing the orientation of the body and the location of the point within the body.  If a body is not rigid, that is, if it can deform, tracking the location and orientation of particles within the body is more complicated.

I haven't looked at all of the instances where rigid body comes up.  My guess is that the original document is not as complete as it could be.  In some cases we should probably be explicit that we are talking about a rigid body.  In other cases, the concept is more general than rigid body mechanics and we should keep it general.

For any instance where rigid body is mentioned (or not mentioned), the question is whether this is correct, or whether we were careless in the original document.  If you have a question about a specific instance, please let me know.

**Comment by hmadej** [comment]
from the stand point of definitions though specifically quantities and concept, shouldn't "angular velocity" be the "base" definition and it just be parametrized by "rigid body". Right now I have to make create a separate definition almost for the "rigid body" part.

**Comment by smiths** [comment]
The fact that the body is rigid is a necessary assumption for some parts of the theory.  For instance, for a rigid body all points within the body will always be displaced by the same amount.  The angles will be different, but they can all be predicted by knowing the orientation of the body and the location of the point within the body.  If a body is not rigid, that is, if it can deform, tracking the location and orientation of particles within the body is more complicated.

I haven't looked at all of the instances where rigid body comes up.  My guess is that the original document is not as complete as it could be.  In some cases we should probably be explicit that we are talking about a rigid body.  In other cases, the concept is more general than rigid body mechanics and we should keep it general.

For any instance where rigid body is mentioned (or not mentioned), the question is whether this is correct, or whether we were careless in the original document.  If you have a question about a specific instance, please let me know.

From your last comment,  yes "angular velocity" should be the base definition.  The concept of angular velocity is more general than the concept of rigid bodies.  A deformable body can also have an angular velocity.  You can see on the Wikipedia page for angular velocity that "rigid body considerations" are given in a separate section:

https://en.wikipedia.org/wiki/Angular_velocity#Rigid_body_considerations
