### ISSUE TITLE
Rigid Body Dynamics

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#132]
Hello Henry.  If you haven't already looked at them, the series of articles at the following link are quite helpful for understanding rigid body dynamics in games:

http://chrishecker.com/Rigid_Body_Dynamics

You can close this issue once you have had a look at these resources and asked any questions that come up.

**Comment by hmadej** [comment]
I took a look at the documents, do not have any questions at the moment, will re-open this issue if I do.

**Comment by smiths** [comment]
Sounds good.
