### ISSUE TITLE
Update examples to use [TSIntro]

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#133]
I've updated DocumentLanguage.hs (as of 41956a3a09d61f09a6249465080e7d27f0f3ea4c) to include the changes we discussed in the all-hands meeting. If your example uses RefSec you'll need to change the intro for the table of symbols from a section (example: s1_2_intro) to a list of TSIntro items (example: [Purpose, SymbConvention [Lit heat_transfer, Doc swhs], SymbOrder])

**Comment by njericha** [comment]
I have fixed SSP as of 659833af603fbc6df7bb546b86722f2ab66df1c6

**Comment by danscime** [comment]
Fixed SWHS as of 8c7c331

**Comment by hmadej** [comment]
Fixed Gamephys as of f89d366

**Comment by AKM11** [comment]
Fixed PCM as of 559930d.

**Comment by szymczdm** [comment]
Fixed as of bbc31a386973016842c78a5e48a471aed84d7da9

**Comment by niazim3** [comment]
Fixed GlassBR as of d6ee3e9.
