### ISSUE TITLE
TableOfSymbols Intro for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#136]
There is currently no introduction for the table of symbols for GlassBR. Will one be added soon?

**Comment by smiths** [comment]
For GlassBR's table of symbols introduction, you should follow the "little language" that was designed during yesterday's meeting and subsequently implemented by Dan.  This is discussed in issue #133.  You can speak with your colleagues and/or Dan to get further details.

**Comment by JacquesCarette** [comment]
Note that the 'right' process is for you to implement this, put a comment here with the commit where this is done, and then close the issue.  I'll reopen so that you can start building good `git` habits right away!  😃

**Comment by niazim3** [comment]
Thank you; Implemented in commit d6ee3e9.
