### ISSUE TITLE
Better names or system designed for combinators (ex. for, for'', for''', for'''')

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#137]
As shown in 90a411dca67968915129086aba10024369b8d13b , many of the combinators such as "for" and "of" have up to 5 versions with the names having "proliferation of primes".

**Comment by szymczdm** [comment]
I'll take a look at a better way. It seems like the two "most common" uses of "for" across examples should be for and for', then we can have for'' with explicit "use X and Y" instead of adding a number of combinators.
