### ISSUE TITLE
Replace all (S "") with EmptyS

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#139]
I've added a constructor (EmptyS) to Sentence to replace `S ""` wherever it appears.

Please update your examples.

**Comment by hmadej** [comment]
gamephys does not have instances of `S ""`

GlassBR, SWHS, and DocumentLanguage have all occurrences of it.

**Comment by njericha** [comment]
This does not come up in my example

**Comment by danscime** [comment]
Fixed SWHS as of 3c6454a

**Comment by danscime** [comment]
Fixed SWHS as of dfe534a

**Comment by AKM11** [comment]
Not present in PCM.

**Comment by niazim3** [comment]
Updated GlassBR as of cf697ea.

**Comment by njericha** [comment]
I'm assuming this is now fixed and we can close this issue.

**Comment by szymczdm** [comment]
Indeed. It appears all the examples are fixed and I cannot find it anywhere else.
