### ISSUE TITLE
Explicit grouping in expressions

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#14]
Need to have a way to explicitly add brackets when it is meaningful. For example: k = (i+1)+j.

**Comment by JacquesCarette** [comment]
I guess what needs to happen for this one is that our design discussion needs to be captured, put on the wiki, and then this issue can be made to point to that.

**Comment by szymczdm** [comment]
Added a quick [wiki page](https://github.com/JacquesCarette/literate-scientific-software/wiki/Explicit-Grouping-of-Expressions) for this one.
