### ISSUE TITLE
SWHS progName to be changed

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#140]
I have changed it to lower case, but still needs to be fixed for when it needs to be plural when automated into table of symbols.

**Comment by szymczdm** [comment]
Can you add a bit more detail on what you mean exactly?

**Comment by danscime** [comment]
For the table of symbols automation, I use this as my parameter:

[TSPurpose,SymbConvention [Lit (nw heat_trans), Doc (nw progName)], SymbOrder]

It uses progName which is "solar water heating system" but to match stable, it needs to be pluralized at the end, but the plural command doesn't work on it.
