### ISSUE TITLE
Lower cased label for Theoretical Models and upper cased OF in SSP

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#141]
The "factor of safety'' label for Theoretical Models is now lowercased and cannot fix until the table generation automatically titleizes the label. If I try to titleize "factor of safety'' the "of" gets capitalizes with it since I am not (and cannot) use an 'of' combinator. The for this is that I need to have a custom plural: "factors of safety''.

**Comment by njericha** [comment]
I should be able to temporally fix the capitalization using: nounPhrase' s p c = Phrase (S s) (S p) c CapWords

**Comment by szymczdm** [comment]
Why can you not use one of the `of` combinators here?

**Comment by njericha** [comment]
of'' returns a sentence whereas of and of' return a NP

**Comment by njericha** [comment]
factor = npnc "factor"    (cn' "factor")
safety = npnc "safety"    (cnIES "safety")

If I use for'' I will have to use it in my body with these defined terms above rather than using the term from the below concept with is what I'm trying to reference. @szymczdm 

fs_rc :: RelationConcept
fs_rc = makeRC "fs_rc" (nounPhrase "factor of safety" "factors of safety") fs_desc fs_rel

**Comment by njericha** [comment]
for now I will use 
nounPhrase'' :: Sentence -> PluralForm -> CapitalizationRule -> CapitalizationRule -> NP
nounPhrase'' = Phrase
and manually tell drasil what to do

**Comment by szymczdm** [comment]
you should now be able to create a NounPhrase for "factor of safety" using the of_'' combinator. If you have a problem, reopen this issue.

**Comment by njericha** [comment]
This has now fixed all but one case "factor of safety" shows up. The remaining issue is still in theoretical models table. "Factor of Safety" is still not capitalized and this is done internally somehow since all that is in my body.hs is `s4_2_2_tmods = map Definition [Theory fs_rc]`

**Comment by szymczdm** [comment]
That's a separate issue that will be solved alongside #29 since we're going to need to reimplement some things before it'll be done. I'll make a note in #29 to ensure we confirm it's done, and close this issue for the time being.
