### ISSUE TITLE
Updating mgDoc?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#143]
I have received a similar issue where mgDoc is used to the one where I had used mkDoc (with regard to unnecessary capitalization of words built into the mkDoc function) which is now updated.
I attempted to make a customizable mgDoc'' using the following function based on the updated mkDoc': 
type Topic = NWrapper
mgDoc'' :: NamedIdea c => c -> (NWrapper -> NWrapper -> Sentence) -> Sentence -> [Section] -> Document
mgDoc'' sys comb authors secs = 
  Document ((nw mg) `comb` (nw sys)) authors secs
and ran into the error **not in scope: type constructor or class `NWrapper`**.
How can this be fixed?

**Comment by szymczdm** [comment]
Seems like you're missing an import of the NWrapper data type.

**Comment by niazim3** [comment]
Fixed as of 2c47be1.
Should I remove mgDoc and/or mgDoc' yet?

**Comment by szymczdm** [comment]
I would recommend you not remove mgDoc / mgDoc' as they are generating the Module Guide (as opposed to the SRS). That system is being overhauled, but until it's done, we don't want to break things.

Also, since you said this is fixed, I'm going to close the issue.
