### ISSUE TITLE
Code readability (coding style question) Paren vs $

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#145]
For coding style which one is preferred:

1. `plural (position ^. term)`
2. `(plural $ position ^. term)`
3. `plural $ position ^. term`

when used in a list, example:
1. `[S "Determine the", plural (position ^. term), S "and", plural  (vel ^. term), 
  S "over a", S "period of", phrase (time ^. term) ]`

2. `[S "Determine the", (plural $ position ^. term), S "and", (plural $ vel ^. term), 
  S "over a", S "period of", (phrase $ time ^. term)]`

3. `[S "Determine the", plural $ position ^. term, S "and", plural $ vel ^. term, 
  S "over a", S "period of", phrase $ time ^. term]`

the second (2.) option feels more readable to me.

**Comment by szymczdm** [comment]
I prefer option 2 as well. It's definitely the clearest to me.

**Comment by JacquesCarette** [comment]
I'm ok with 2.  [Though over the longer term, this may be moot, we'll see]
