### ISSUE TITLE
Update SSP to use two files for definitions

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#146]
Other examples use a DataDefs.hs and a Unitals.hs for their definitions which creates a hierarchy whereas SSP only has a single defs.hs file. Is SSP supposed to be like this?

**Comment by smiths** [comment]
No SSP is behind the other examples.  It was started last summer, but not completed.  You should follow the other examples for things that they do well, like having a hierarchy of definitions.

**Comment by szymczdm** [comment]
You're looking at what was essentially the initial version of the implementation. You can re-organize things as you see fit, as long as it makes sense.

Splitting things up a bit makes sense to me, not to mention it will help with pattern-finding when I get to overhauling data defs.

**Comment by szymczdm** [comment]
Dangit @smiths, beat me by a couple of seconds.

**Comment by njericha** [comment]
fixed c1fd1bbd42fb3827a9c83b6a2ed158614638ea96
