### ISSUE TITLE
Need a 'the' and 'of the' combinator

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#148]
Need a 'the' combinator for section headers like "The Client" and an 'of the' combinator for the section header "scope of the project".

**Comment by szymczdm** [comment]
"The" seems like it would fall under a modifier (as it's an article), but either way, I'll create it ASAP.

It should be able to be combined with our existing "of" combinator(s), since "the" will be a unary modifier.

**Comment by danscime** [comment]
SWHS has a "Properties of a Correct Solution" as a title. So like an "of a" combinator or something.

**Comment by szymczdm** [comment]
Fixed as of f8b862c8742a58d1e14abd28ccb31ff7c1b07316

**Comment by szymczdm** [comment]
@danscime that's a different issue, so I'll close this one for now.

**Comment by niazim3** [comment]
I tried to combine the 'of_' and 'the' combinators using `scpOfTheProj = npnc "scpOfTheProj" (of_ scope (the project))`, but received the following error message: **No instance for (Language.Drasil.Chink.NamedIdea.NamedIdea NP) arising from a use of _of**_ ... is this because both 'of_' and 'the' are expecting NamedIdea types and both produce NPs?

**Comment by niazim3** [comment]
The following lines of code worked:
`scpOfTheProj = npnc "scpOfTheProj" (scope `of'` theProj)
theProj           = npnc "theProj"      (the project)`
I'm not sure if I should close this issue though since this is a roundabout way of completing the task...

**Comment by szymczdm** [comment]
Having "the project" as its own chunk seems redundant, so I'm going to modify the way the `the` combinator works. I'll let you know once I've implemented the changes.

**Comment by szymczdm** [comment]
Updated `the` in 1fd5d51551d60256b9d6b450efd1ff15e87d16cd and removed chunks which included `the` from Documentation.hs. Examples will need to be updated, but otherwise this is complete.

**Comment by niazim3** [comment]
Why is the following code giving these outputs?
"The  Data definitions" <-- (at_start' $ the dataDefn)
"the data definitions" <-- (plural $ the dataDefn)
Desired output: **"The data definitions"**
