### ISSUE TITLE
Module imports form a cycle when making a new section header of type NPNC

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#149]
'traceyMatrix' and 'graph' are terms defined in data/drasil/concepts/Math.hs.
'Traceability Matrices and Graphs' is a section header in GlassBR, which I feel should be defined in Documentation.hs.
In order to not have multiple definitions of the same terms, I tried to import 'traceyMatrix' and 'graph' from the Math.hs file using **import Data.Drasil.Concepts.Math (traceyMatrix, graph)** and defining a new variable **traceyMandG  = npnc "traceyMandG"  (cnICES traceyMatrix `and` cn' graph)** as a new documentation section header.
But I receive an error because the module imports form a cycle (since Math.hs imports Documentation.hs and vice versa)... is there a way around this?

**Comment by szymczdm** [comment]
The only way around this is to avoid creating a cyclic import. In this case, it means we need to figure out if they both rely on some underlying concept, which needs to be moved to a different module and imported into both as necessary.

Why is "traceyMatrix" in Math anyway? It seems that "traceability" would be a documentation concept, as would a traceability matrix. Also, why is unit_ in Documentation? It seems like unit would be a concept elsewhere, though I'm not sure where exactly.

**Comment by niazim3** [comment]
Since 'traceability' is an adjective, could 'traceability matrix' and 'matrix' be an NP defined in Documentation?

**Comment by JacquesCarette** [comment]
'matrix' definitely belongs in math.  But 'traceability matrix' does not.

**Comment by niazim3** [comment]
Update: In my current directory, 'traceyMatrix' is now in Documentation, 'matrix' and 'graph' stayed in 'Math.hs, and 'unit' has returned to Math.hs.

I'm trying to directly define the title 'Traceability Matrices and Graphs' within the body of my example since I kept getting a cycle of imports error when importing anything from Math.hs, despite removing the import of 'unit' from Documentation.hs... 

So this may be a separate issue but 
**s9 = Section (titleize' traceyMatrix `and` (titleize' $ graph ^. term))** is what I'm trying to get to work, however, `and` seems to be a pre-defined function in Haskell, so it is expecting a t0 Bool type. Could the 'and' combinator be renamed to something else and used in Body.hs somehow?

**Comment by JacquesCarette** [comment]
For `and`, see issue #150 (just closed).

For your main issue, that will probably need someone else to look into the details.  Maybe you can ask one of your co-workers, or @szymczdm if he's still around?

**Comment by szymczdm** [comment]
and is fixed as of 667314fce405beff and I'll look into the cyclic import.

**Comment by szymczdm** [comment]
I've figured out the problem - it has to do with where Template.MG. is. MG is in Language, when it should really be elsewhere (ie. Data or Example). Template.MG imports Docs, which imports Math, which imports Language.Drasil, which imports Template.MG.

I'll move Template.MG somewhere better for the time being, as it's going to be revamped shortly anyhow.

**Comment by szymczdm** [comment]
Fixed as of 0c58d0a1d5829053284270977efc4073a2187ca2
