### ISSUE TITLE
Representing functions in Expr

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#15]
There is currently no way to represent functions in expressions. For example, representing temperature as a function of time by T(t).

**Comment by JacquesCarette** [comment]
Could you expand on this?  Do you mean representing function calls?  Depending on what this means, it could either be very easy to do, or very hard [and options in between].

**Comment by bmaclach** [comment]
No, I just mean being able to print something like "T(t)" as part of an expression (just for display purposes). Currently,  "T(t)" can't be printed because there is no defined operation between T and t.

**Comment by JacquesCarette** [comment]
P {margin-top:0;margin-bottom:0;}


Right, this means that "function call" should be part of the Expr grammar.  That's easy to do.
Dan?

**Comment by szymczdm** [comment]
Added function calls. They can accept multiple parameters in the form of a list of expressions. So T(t) would be something like:

`FCall (C T) [C t]`

whereas F(x,y) would be something like:

`FCall (C F) [C x, C y]`
