### ISSUE TITLE
"and" combinator does not work (keyword namespace collision?)

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#150]
Haskell has a built in function `and :: Foldable t => t Bool -> Bool` which is taking precedence over `NamedIdea.and`

**Comment by JacquesCarette** [comment]
The convention we've used up to now is to append an `_` when that happens.

**Comment by szymczdm** [comment]
How odd, I'm not getting any warnings or errors. Alright, so we have two options, either A) hide the import of "and" from Prelude, or B) rename "and" to "and_". 

I'm leaning towards just renaming it for simplicity, in case we need Prelude.and in the future

**Comment by hmadej** [comment]
Fixed as of  667314f, language/Drasil was also not exporting 'and_'
