### ISSUE TITLE
Placement of Words?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#152]
I am unsure on where to place a few key words.  Namely, in which file (Documentation, Software, Physics, etc.) should we place 'program', 'surface' and 'energy'/'equation' (if even needed)?  Also, should I make heat flux part of thermodynamics or should I leave it in Example?

As a side note, should we keep this issue open in case clarification is needed for other terms later on (people can just add to it)?

**Comment by JacquesCarette** [comment]
There will always be words who placement will not be clear.  Especially as some words are overloaded, so the same word [but meaning different things] may well naturally belong to more than one domain.

But, be that as it may, we'll try to find a decent home, and fix it later if we were wrong.  So: `program` should go in Software, `surface` in Math, `energy` in Physics, `equation` in Math.  They are common enough that they will all eventually be needed.  heat flux should be part of Thermodynamics.

If you are happy with these calls, then close the issue.  We should open new ones when new words become a problem.

**Comment by szymczdm** [comment]
Jacques beat me to the punch as I was about to say the same. Also, program (and possibly others of those terms) should already exist in Data.Drasil! So make sure you're not duplicating things.

**Comment by AKM11** [comment]
Alright, thank you, I will rearrange them.
