### ISSUE TITLE
Moved Template.MG, Examples need to be updated.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#153]
Hi all,

I moved Template.MG so you now need to update the imports on any files that referenced it to add
`import Drasil.Template.MG`.

The same goes for Template.DD

Please check off the boxes once you've finished:

- [x] gamephys
- [x] glassbr
- [x] pcm
- [x] ssp
- [x] swhs
- [x] tiny

**Comment by AKM11** [comment]
Multiple redundancy warnings pertaining to these imports are popping up.  I presume that this is only because they are not directly being called upon in file?

**Comment by hmadej** [comment]
This is probably done? I think tiny has been updated.

**Comment by njericha** [comment]
I think so seeing as there are no warnings or crashes
