### ISSUE TITLE
Meta Issue

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#154]
The number of issues has gone sky-high.  This is fine (in that it is the right process).  The number of open issues is not good; the number of open issues which are unassigned is definitely bad.

Dan, please review all open issues, and figure out who should be assigned.  

Also, I think it is time to start using milestones.  My first thought is to start bumping up the 'minor' version of Drasil (i.e. right now it is 0.0.6) every week.  So at the end of tomorrow, it would get bumped to 0.0.7.  We should have slightly bigger milestones, which bump up the middle number.

Some issues should be assigned to 0.0.7, 0.0.8, 0.1.0 and 0.2.0.

**Comment by JacquesCarette** [comment]
I did a little bit of this.  But I really need to get back to writing a different document instead...

**Comment by szymczdm** [comment]
I've done the majority of the issues, there are a few I'm really not sure where to place them (milestone-wise), and some may need to be punted down past 0.2.0. I don't want to create an artificial milestone for the time being, so I'll leave them uncategorized right now.

If that sounds alright, then we can close this issue (and essentially make a new meta-issue for 0.0.8, to review and see where we stand).

**Comment by JacquesCarette** [comment]
So are there some that I should look at, milestone-wise?  I don't mean the ones past 0.2.0 (they can stay as is), but rather the ones where you are not sure?

**Comment by szymczdm** [comment]
The ones I'm not sure about are essentially the ones assigned to Steven. The other ones seem to all be post-0.2.0

**Comment by JacquesCarette** [comment]
Ah, ok.  Let's review those at Monday's meeting.  Steven's comp is in the morning, so he should be there at the afternoon meeting.
