### ISSUE TITLE
Clean up SWHS example - Unique Chunks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#156]
By "clean up" I mean removing as much duplication as we can, creating new combinators, etc. It will be an ongoing task over the summer, but we should get the first pass done soon.

**Comment by szymczdm** [comment]
Specific goal of this pass: remove all duplication of concepts so that each comes from a single unique source.

**Comment by danscime** [comment]
Duplication of concepts have been removed as they can be found in Unitals. We might be able to close this issue.

**Comment by szymczdm** [comment]
I'm still seeing a bit of duplication, not necessarily of chunks, but things like `phase_change_material = dcc "pcm" (nounPhraseSP "Phase Change Material") ...` and `phsChgMtrl  = commonINP "phsChgMtrl" (pn' "Phase Change Material") "PCM"` are both using different noun phrases for the same term.

**Comment by danscime** [comment]
How would I fix that, because they're two different types, so when called upon, they may need to be a certain type right?

**Comment by szymczdm** [comment]
There's a couple of different things going on here. First off, `nounPhraseSP "Phase Change Material"` and `pn' "Phase Change Material"` are saying the same thing (yes, with different types), except the first states that it's a self-plural noun phrase, whereas the second states it's a proper noun with a plural created by adding 's'. 

These should be unified into one NounPhrase and used as appropriate.

`phase_change_material` should be able to be constructed from `phsChgMtrl` by using the `dcc` smart constructor as it has it there, the main difference being that it should look more like:

`phase_change_material = dcc "pcm" phsChgMtrl ...`

**Comment by danscime** [comment]
I'm getting an error:

Couldn't match expected type ‘NP’ with actual type ‘CINP’

**Comment by szymczdm** [comment]
Try using (^. term) on phsChgMtrl

**Comment by danscime** [comment]
So it's fine to have both now since the one is sort of built of the other?

**Comment by szymczdm** [comment]
Yes, since everything is coming from one source and we're essentially just "tacking on" more (necessary) information. This might change after we look over and re-inventory the current data structures we're using, but for now it's not an issue.

**Comment by danscime** [comment]
Alright, so I got it to work, so we're good on that specific example. I'll clean up a bit more with the progName and swhsFull things.

**Comment by AKM11** [comment]
All instances of term definition duplication cleared as of commit da09cf60b79d63f0e824cc18f06050d52ad5d683.
NOTE: The method of doing so feels like a hack but functionally works.
