### ISSUE TITLE
Clean up PCM example - Unique Chunks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#157]
By "clean up" I mean removing as much duplication as we can, creating new combinators, etc. It will be an ongoing task over the summer, but we should get the first pass done soon.

**Comment by njericha** [comment]
I think you mean PCM?

**Comment by szymczdm** [comment]
Yup. My bad.

**Comment by szymczdm** [comment]
Specific goal of this pass: remove all duplication of concepts so that each comes from a single unique source.

**Comment by AKM11** [comment]
I can do a general cleanup of the code but what concept duplication were you referring to?

**Comment by szymczdm** [comment]
It may not apply to PCM actually, because of how small that example happens to be, but if you could ensure that the chunks used throughout aren't duplicates of other chunks (i.e. they represent the same concept, but have slightly different spelling/definitions OR there's one version in your example-specific concepts and another version (possibly identical) in Data.Drasil somewhere). 

Basically just the clean up we've been discussing: making sure there's only one chunk per concept so we can track everything down.

**Comment by AKM11** [comment]
I think PCM is fine and there is no direct duplication of terms with Data.Drasil that I can see.  If any terms seem too general and need to be moved or rearranged to fit some standard, just let me know.
