### ISSUE TITLE
Create custom and combinator

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#159]
I would like to be able to use an **and** combinator that will titleize' the first term and titleize' the second one, since that'll be adding too many specific combinators, can we get a custom one made?

I tried to follow the example of the custom for combinator, but the the types are incorrect: 
`and_'' :: (NamedIdea c, NamedIdea d) => (Sentence -> NP) -> (Sentence -> NP) -> c -> d -> NP
and_'' f1 f2 t1 t2 = (f1 $ t1 ^. term) +:+ S "and" +:+ (f2 $ t2 ^. term)`

**Comment by szymczdm** [comment]
I need to see an example of where you're trying to use this, so I can set phrase, plural, etc. up in a meaningful way. If you just need a sentence combinator, then the types will be very different than a nounphrase combinator.

**Comment by niazim3** [comment]
I'm trying to get "Traceability Matrices and Graphs" using `s9 = section (titleize' traceyMandG)` in the Body of my Example, where traceyMandG is defined in Documentation.hs using NPs : `traceyMandG  = npnc "traceyMandG"  (traceyMatrix `and_'` graph)`.
