### ISSUE TITLE
Mapping and interpolation

### ISSUE THREAD

**Issue by Sodaaaa** [JacquesCarette/literate-scientific-software#16]
1.
 **Mapping**
In the Data Definitions section in "glassbr_srs.pdf" file, there is a relation which is a function that maps from t (nominal thickness) to h (minimum thickness). Details are as follows.

**Location**: 6.2.4 Data Definitions -> DD1
h = h(t),  h(t) = (t = 2.5 => 2.16 | t = 2.7 => 2.59 | t=3.0 => 2.92 | t=4.0 => 3.78 | t=5.0 => 4.57 | t=6.0 => 5.56 | t=8.0 => 7.42 | t=10.0 => 9.02 | t=12.0 => 11.91 | t=16.0 => 15.09 | t=19.0 => 18.26 | t=22.0 => 21.44)

2.
**Interpolation**
And there are 3 relations which are functions (supposed to be equations, actually using an interpolation algorithm) using their specified parameters. They are listed as follows.
- **Location**: 6.2.3 Instance Models -> IM3 **Equations:** q = q(w_TNT, SD)
- **Location**: 6.2.4 Data Definitions -> DD3   **Equations:** J = J(q_hat, a/b)
- **Location**: 6.2.4 Data Definitions -> DD7  **Equations:** q_hat_tol = q_hat_tol(J_tol, a/b)

Currently, I can't enter them in Drasil as h = h(t) or q = q(w_TNT, SD) since they can't be a Relation. And the equations used for them might need further discussions.

**Comment by Sodaaaa** [comment]
Another mapping case.
**Location:** 6.2.4 Data Definitions -> DD5
GTF = GTF(g)

**Comment by njericha** [comment]
This can now be done using `FCall`
