### ISSUE TITLE
Definition sources?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#162]
In response to  issue #93 pertaining to sloppy naming conventions and descriptions, is there any source in particular you would like us to be drawing definitions from?

**Comment by JacquesCarette** [comment]
There is no one place, unfortunately.  We'll have to do it example-by-example.

**Comment by AKM11** [comment]
So just implement definitions as we find them and if there is a problem we will be told?

**Comment by JacquesCarette** [comment]
That's probably the most efficient.

**Comment by AKM11** [comment]
Alright, thank you.
