### ISSUE TITLE
Update aNP combinator

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#165]
We either need to update the aNP combinator or create a new one that creates a NounPhrase.

**Comment by szymczdm** [comment]
`aNP` already creates a NounPhrase, so I'm assuming you meant NamedIdea.

**Comment by szymczdm** [comment]
Fixed with the addition of `a_` from 1fd5d51551d60256b9d6b450efd1ff15e87d16cd
