### ISSUE TITLE
Synonyms?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#166]
Drasil currently allow for synonyms?  In issue #163 we discussed heat, which can be a short form for heat energy or thermal energy.  How difficult would it be to add synonyms to Drasil?  Knowing what terms are synonymous is actually currently a source of confusion to anyone that is learning physics (or any science).

I don't think this is something to focus on now, but I'll label this issue as a potential future enhancement.

**Comment by szymczdm** [comment]
Currently only unit synonyms are allowed.

>How difficult would it be to add synonyms to Drasil? 

I'm not exactly sure, I think it needs a bit of design to do something that makes sense and is scalable.

**Comment by njericha** [comment]
We could do something like,
```
thermEnergy = dcc "thermEnergy" (nounPhrase "thermal energy") ("the energy related to...")

synonym :: (Concept c) => c -> String -> ConceptChunk
synonym c termSynonym = dcc (c ^. id) (nounPhrase termSynonym) (c ^. defn)

heat = synonym thermEnergy "heat"
```

**Comment by szymczdm** [comment]
@njericha that won't quite work, as we'll then have two (trivially) different chunks with matching ids (big problem). 

The exact implementation details are a little hazy for me right now, and would rely on the databases/maps approach we've done elsewhere, but essentially we'd need to be able to have a new chunk that has an id, a term, and a second 'synonym id'. Then we can look up everything except the term using the synonym id and the databases/maps.

**Comment by smiths** [comment]
@szymczdm, please put our decision about synonyms on the wiki page under the heading "design choices."  Please close this issue after doing that.

**Comment by szymczdm** [comment]
Done. Can be found [here](https://github.com/JacquesCarette/literate-scientific-software/wiki/Design-Choices).

**Comment by smiths** [comment]
Looks good.
