### ISSUE TITLE
LinkedIn

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#168]
Although this issue isn't specifically Drasil related, I wanted to try Dan's handy Task List feature for GitHub.  😃 

If you are interested, could each of you create a LinkedIn (https://www.linkedin.com/) account, if you don't already have one, and send an invitation to me.  ( @szymczdm and @JacquesCarette  would probably also like an invitation.)  LinkedIn is a nice way to stay connected professionally.  It is a good way for you to build up contacts over time, and it is a good way for me to find you when it is necessary to fill out Appendix D for future NSERC grant applications.  😄 

Please check off the box once you've completed this task, or decided that you would rather not participate.

- [x] @hmadej 
- [x] @njericha 
- [x] @niazim3 
- [x] @AKM11 
- [x] @jainrohan28 
- [x] @danscime 

Thank you.

**Comment by szymczdm** [comment]
@hmadej can you take a look at this issue so we can close it?

**Comment by hmadej** [comment]
created linkedin account and added @smiths @szymczdm @JacquesCarette
