### ISSUE TITLE
Ordering of Table of Symbols changed in SSP slightly

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#169]
When I did commit c1fd1bbd42fb3827a9c83b6a2ed158614638ea96 , the generated output changed the order slightly to the table of symbols. This can be best seen in commit 57692e0e7382db1924b26000dd75167862103d4b. I'm guessing this is because how the sort function treats unitless quantities but I just want to make sure there isn't a sorting issue with the table generation.

**Comment by szymczdm** [comment]
I'll look into it, but judging from the commit with the updated output, it looks to be in the correct order (unless I misread something). I wouldn't worry too much about it unless we see something blatantly wrong (like 'T' before 'S').

**Comment by JacquesCarette** [comment]
Took myself and Spencer off of this, as it seems that @szymczdm is on top of it.

**Comment by szymczdm** [comment]
From what I'm seeing in the output, things look okay (though we may change the sorting method in the future), so I'm going to close this and consider it a non-issue.
