### ISSUE TITLE
Add Jingwei, Brooks and Luthfi as members

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#17]
So that everyone can see their drasil code, we need Jingwei, Brooks and Luthfi to have write access to the git repo.  I thought I could add them, but I do not see any part of the interface that lets me add new members.  Dan or Jacques, can you please do that?

**Comment by JacquesCarette** [comment]
We would need their github userid to do that.  I am not sure I have them?

**Comment by smiths** [comment]
There github ids are: Sodaaaa, lmawarid and bmaclach
