### ISSUE TITLE
Attempt to use 'at_start' instead of 'phrase' during table creation

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#170]
I'm trying to eliminate the inconsistencies between GlassBR's Website and Stable files, specifically at this point in the description of the table of symbols. In order to do so, I believe the function that needs to be altered is the **mkTSymb** one from DocumentLanguage.hs. I attempted to change the current `phrase` calls to `at_start` ones and compiled, however, there is no change in the output of the _Table Of Symbols_. 
E.g. of inconsistency: desired output --> `< $a$ & Plate length (long dimension) & mm`
                                  current output --> `> $a$ & plate length (long dimension) & mm`

Am I missing something crucial?

**Comment by niazim3** [comment]
I seem to have forgotten to update line 120, will close this issue once I've committed my changes.

**Comment by niazim3** [comment]
Fixed as of c3cf890.

**Comment by hmadej** [comment]
Should all the descriptions be capitalized? this change has capitalized my table: 
`< acceleration
---
> Acceleration
127c127
< coefficient of restitution
---
> Coefficient of restitution
138c138
< force
---
> Force
149c149
< gravitational acceleration
---
> Gravitational acceleration
160c160
< gravitational constant
---
> Gravitational constant
171c171
< moment of inertia
---
> Moment of inertia
182c182
< horizontal unit vector
---
> Horizontal Unit Vector
193c193
< impulse (vector)
---
> Impulse`

**Comment by szymczdm** [comment]
This will affect all of the examples, so I think we need to agree on a convention. I think using at_start makes sense, so we'll have tables like:

Symbol | Term
---------|-------
a | Acceleration
g | Gravitational constant

etc. If anyone prefers a different convention, or would like to suggest a particular variant instead, please feel free. Otherwise, once you've all taken a look, just check your id off (then we'll close the issue).

- [ ] @hmadej 
- [ ] @niazim3 
- [ ] @AKM11 
- [ ] @njericha 
- [ ] @danscime

**Comment by niazim3** [comment]
This is very specific to my example, but what should I do in a case like the following: 
`
< $w_{TNT}$ & Explosive **M**ass in equivalent weight of TNT & kg
---
> $w_{TNT}$ & Explosive **m**ass in equivalent weight of TNT & kg
`

**Comment by szymczdm** [comment]
I think that change should be fine, if it ends up being a problem, we'll come back to it.

**Comment by njericha** [comment]
I'll just have to update stable to capitalize this

**Comment by szymczdm** [comment]
Looks like everyone has agreed to this convention. Done.
