### ISSUE TITLE
Non-functional vs nonfunctional (inconsistent across examples)

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#171]
which one should it be? this is not consistent across examples and within examples.

**Comment by szymczdm** [comment]
Personally I prefer "nonfunctional" (lacking the hyphen).

**Comment by JacquesCarette** [comment]
I don't have a strong preference either way.  We should really wait for @smiths to weigh in though.

**Comment by smiths** [comment]
I don't have a strong opinion, but I would prefer non-functional requirements.  Based on a quick google search, it seems to be the more commonly employed form.  I like the idea that this term will now be consistent within and between documents!  I also assume that if we change our minds at a later point, switching to nonfunctional will be a trivial change.

**Comment by hmadej** [comment]
ok, changed to "non-functional" this can be re-opened if we need to change back to nonfunctional.
