### ISSUE TITLE
Remove all instances of sLower and sMap

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#172]
Now that we have noun phrases with proper capitalization rules, we should be able to remove all instances of `sLower` and `sMap`. The majority of these will be straightforward. You may need to ensure your chunk terms are written in lower case, for these instances, so the output doesn't change.

You'll likely find a bunch of odd changes to capitalization as you attempt this, so I'd recommend going one chunk at a time until you've removed them all, double-checking your logs as you go.

We'll use a task lisk here as well, so you can check off when your example is done.

- [x] gamephys
- [x] glassbr
- [x] pcm
- [x] ssp
- [x] swhs
- [x] tiny

**Comment by njericha** [comment]
my example doesn't use sLower or sMap

**Comment by AKM11** [comment]
PCM cleared as of commit 1717b8dd4adad4e00d5718019a675134ebb7fa03

**Comment by niazim3** [comment]
GlassBR cleared as of commit 6128dfa.

**Comment by szymczdm** [comment]
Finished as of 990f2e3dece412af1ca0fb80557b2ccd016cca14.
