### ISSUE TITLE
Coding conventions and naming

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#174]
Hello Dan.  Could you please write a brief document to summarize the coding conventions and frequently used functions?  You mentioned previously that you were working on an automatically generated API document.  Of this is possible, this would likely do the trick.

I find that it takes me time to read the code, since I don't immediately associate the short names with something.  For instance cn, cn', npnc, etc.  I can guess at most of these, but it would save me time, and it would help future developers, if we recorded all of this information in one convenient place.

**Comment by smiths** [comment]
I found a start to what I'm looking for in the README.md file in the code folder.  I hadn't seen that previously.  Very helpful.  Can you add cn, cn', and npnc to your legend?

**Comment by szymczdm** [comment]
I've added them to the legend as of 68ceb414a3e9015a9809ad42b589c9639c24f349, the rest of the API documentation will be done this week. That also encompasses #118.

**Comment by szymczdm** [comment]
Now `make doc` should create a Docs folder with all of the generated API documentation.
