### ISSUE TITLE
Pascal and Newton

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#175]
I noticed in SSP ( @njericha ) and GlassBR ( @niazim3 ) that in the Table of Units Newton and Pascal are not capitalized.  Unfortunately, these unit names should be capitalized to honor the people that they are named for.  I am not quick at reading the code, but the lower case could be due to a toLower in unit_table (in TableOfUnits.hs).  In my local version I replaced toLower by (\x -> x) and I get the upper case version, but unfortunately, I also get upper case for the other units that are not capitalized.

The simple fix is to use proper capitalization when we create the units.  That is, we use capitals in the string when this applies, and lower case when this applies.  We would then not use the toLower function at all, and simply rely on getting the information correct in the SI_Units.hs file.

Of course, I am open to more elegant solutions.  😄

**Comment by JacquesCarette** [comment]
Interesting issue.  In a way, we should never `toLower` anything.  It's probably ok to `titleize` and `at_start` for everything. So it would make sense to have the capitalized version as the standard name in the units database.

**Comment by szymczdm** [comment]
This should be fixed as of 6c4cb16fb33ac3095e70280e7cd61bd61f096c2d ( partly due to 990f2e3dece412af1ca0fb80557b2ccd016cca14)

**Comment by smiths** [comment]
Thank you for sorting this out Dan.  I have good news and bad news.  The bad news is that I believe I was wrong -- after looking into it, I don't think Pascal and Newton are actually capitalized.  The good news is that Celsius is capitalized, as I believe you have correctly done in the code.

I am basing my new opinion on the documentation from NIST (National Institute of Standards and Technology):

https://www.nist.gov/pml/weights-and-measures/writing-metric-units

From their description, which I saw in other resources as well, all names are lowercase, except for Celsius, or when the unit name starts the beginning of a sentence.  They symbols for the units are capitalized when they are intended to honour the person that they are named for.  There are sources on the web that say Pascal, Newton etc should be capitalized, but the are just people saying it.  The SI resources suggest what the NIST page says.

The other good news is that it is (I believe) a simple fix to get the capitalization of our units correct.  In fact, this is a trivial, but still compelling example, of the value of the generative approach.  😄 

Dan, if you agree with following the convention from the NIST page, can you please update the code related to this one (hopefully) last time?  If you do not agree, we should discuss.  I am going to reopen the issue.

**Comment by szymczdm** [comment]
I agree, I'll update the code accordingly shortly.
