### ISSUE TITLE
Clear a Warning?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#178]
The MG file employs a temporary variable titled ccs which is identical to something pulled from Language.Drasil on line 201/203 and causes multiple warning messages.  Would it be alright to adjust that variable name? (I tested it on my computer by changing it to ccs' and it worked fine but since this is the MG file I would rather check before committing anything.)

**Comment by szymczdm** [comment]
I didn't notice this issue earlier, sorry, but I've already fixed all the warnings as of ee49839aac77554e7727ff7624f78edce0eb6f57
