### ISSUE TITLE
SRS SWHS With PCM and Without PCM New Section

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#179]
Can you please add the new sections to the SRS for SWHS.  The latest version can be found at https://github.com/smiths/swhs.  The new sections are "Characteristics of Intended Reader"  and "System Scope."  The text of the introduction sections has been modified to reflect the presence of these new sections.

I tried to add the sections myself, but after several minutes of looking I could not find which files I should edit.

This change applies to both the PCM example and the no-PCM example.  I believe that @njericha is working on the PCM example and @AKM11 is working on the no-PCM example.  If this is incorrect, please let me know.

Modifications were also made to R2, R5 and R6.  I'm not sure these are currently in the Drasil examples, so this might not be relevant at the moment.

**Comment by szymczdm** [comment]
It's actually @danscime and @AKM11 working on these, so I've asigned them.

**Comment by smiths** [comment]
Thank you Dan.

**Comment by AKM11** [comment]
@danscime and I found and added "Characteristics of Intended Reader" to the Body file but we were not sure where to find "System Scope" on the pdf.  Suggestions?

**Comment by smiths** [comment]
The System Context (I inadvertently said scope) is given in Section 3.1 of the original document.

**Comment by danscime** [comment]
Updated SWHS as of 9ef18b5

**Comment by danscime** [comment]
PCM was also updated last week.
