### ISSUE TITLE
Equations with cases

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#18]
Currently no way to implement equations with different cases in definitions.

Edit:  My typed example didn't format well, so I'll use an image instead.  See T_cases (n) in the following image:  http://i.stack.imgur.com/jdm47.png

**Comment by szymczdm** [comment]
This is mostly finished. I just need to finish fixing up the errors with the TeX display and it should be working. The HTML version seems to work, albeit it can look a little odd sometimes.

**Comment by szymczdm** [comment]
Fixed. I'll close the issue once I merge my branch into master. If you want to test, you can always pull the DanWB branch and try it.

**Comment by szymczdm** [comment]
I've merged branches, this is now implemented.
