### ISSUE TITLE
Use of the term 'scpOfTheProj'?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#180]
For some reason, using the NPNC 'scpOfTheproj' causes the word "project" to automatically be plural?

As in, using `titleize' scpOfTheProj` and `phrase scpOfTheProj` results in the following output respectively: "Scope of The Projects" and "scope of the projects'.

**Comment by szymczdm** [comment]
`titleize' ` is the plural version of `titleize`

**Comment by niazim3** [comment]
@szymczdm Sorry that was a typo on my part, what I meant to type was: `titleize scpOfTheProj` produces "Scope of The Projects".

**Comment by szymczdm** [comment]
Check which "of" combinator is being used to create the NounPhrase. I believe you want `of_` and currently you've likely got `of_'`

**Comment by niazim3** [comment]
That was what was causing the incorrect output, thank you @szymczdm. (Commit e077668)

The `the` term is now causing some issues in that titleize --> Scope of The Project, at_start --> Scope of the project ... would making a custom `the` combinator that automatically capitalizes the word after it be considered an inefficient solution?

**Comment by szymczdm** [comment]
As a short-term hack, that's fine. When I'm done the NP modifiers, our `the` functions will likely change.

**Comment by niazim3** [comment]
I just realized a new `the` function may actually not be a good solution since `scpOfTheProj` is defined in Documentation.hs. 
Assigning a `the` combinator that'll automatically capitalize the word after it will cause problems for when we'd like the output to be something like "scope of the project", since using `phrase` will cause the output to be "scope of the **P**roject", which would be incorrect in the middle of a sentence.
So for now, I guess I'll leave `scpOfTheProj` as it is until a custom `the` is available for use?

**Comment by niazim3** [comment]
I believe I almost have a custom _the_ combinator working; I don't think I should push my changes until the errors stop coming up though... however, these are the changes I have made thus far:

Added the following to **Language.Drasil.Chunk.NamedIdea**
`theCustom :: (NamedIdea c) => (NP -> Sentence) -> c -> NPNC
theCustom f t = npnc ("the" ++ t ^. id)
                (nounPhrase''(S "the" +:+ (f $ t ^. term)) (S "the" +:+ (f $ t ^. term)) CapFirst CapWords)`
Exported it into **Language.Drasil**
And changed the scpOfTheProj definition to the following in Data.Drasil.Concepts.Documentation
`scpOfTheProj :: (NP -> Sentence) -> NPNC
scpOfTheProj oper = npnc "scpOfTheProj" (scope `of_` theCustom oper project)`

The error I am getting is within **Example.Drasil.SRS**, where redefining scpOfTheProj to be 
`scpOfTheProj = section (titleize Doc.(scpOfTheProj titleize))`
 is causing type errors. 
![image](https://cloud.githubusercontent.com/assets/28247301/26223676/1cc1718a-3bed-11e7-8d2a-d2daf549f00c.png)
Is this due to an incorrect type declaration or because of some requirements for using `section`?

**Comment by niazim3** [comment]
Completed as of commit 833e086.
