### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#181]
I think I have completed everything I was supposed to for PCM (short of issue #179 on which @danscime and I are still waiting for a reply) and I am having difficulty thinking of something to do next.  Are there any suggestions or should I just try to find work for myself?

**Comment by JacquesCarette** [comment]
Take a look in Drasil.SRS.   See that `intro` combinator?  There should be one like it for every section of an SRS.  And then those should be used.

**Comment by AKM11** [comment]
Okay, found it but I am not really clear on where I need to use it.  Clarification?

**Comment by JacquesCarette** [comment]
In every example, every section starts with `section (titleize' foo) [...]`.  That should be replaced with a combinator `foo`, and then use `foo [...]` directly.

**Comment by AKM11** [comment]
We think we need to adjust the intro 'combinator' to work with the 'section' function instead of the 'Section' type.  Is it alright if we make the change?

**Comment by JacquesCarette** [comment]
Yes please.

**Comment by AKM11** [comment]
Okay know what to do.  Thank you.  On this topic though, I am missing most of the sections to PCM and so have VERY little to change in this regard.  Is there anything else I can do after this?

**Comment by JacquesCarette** [comment]
Do PCM, and then Dan will be out of his current meeting and give you more.

**Comment by AKM11** [comment]
Alright, thank you.
