### ISSUE TITLE
Cartesian coordinates vs Cartesian coordinate system

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#182]
In game physics we use and define the following:

> Right-hand coordinate system: A coordinate system where the positive z-axis comes out of the screen
> Cartesian coordinates:  A coordinate system that specifies each point uniquely in a plane by a pair of numerical coordinates

This seems inconsistent, both are are coordinate systems. Should this instead be: 

> Cartesian coordinate system:  A coordinate system that specifies each point uniquely in a plane by a pair of numerical coordinates

**Comment by hmadej** [comment]
"A Cartesian coordinate system is used." is used in other places in the document so I'll update to cartesian coordinate system to be consistent, and this can be re-opened after if it should be the other way.

**Comment by smiths** [comment]
Hi Henry.  The decision for a right-handed coordinate system and for a Cartesian coordinate system are actually independent decisions.  A Cartesian coordinate system can be right-handed or left handed.  It is an arbitrary decision, but the usual convention is to pick the right-handed system.  Other coordinate systems, like a curvilinear coordinate system, could also likely be described as right-handed or left-handed.

The concept of a Cartesian coordinate system is actually 3D, but the definition is for 2D.  The notion of the handedness of a coordinate system only comes up when there is a third dimension.  Can you please verify that the documentation is clear about the restriction to 2D physics.  Hopefully at some point (but not this summer), we find a way to start with the 3D concept and automatically specialize it to 2D for physics in a plane.

**Comment by hmadej** [comment]
sorry I meant specifically the "coordinate system" vs "coordinates" not the difference in coordinate systems, I will try to be more clear in my communication next time.

**Comment by smiths** [comment]
Okay.
