### ISSUE TITLE
Fix occurrences of SRS.intro in examples

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#183]
I have changed the intro function in drasil\srs.hs as of dbb8a04bb8338d02ce0365c064c5e1361ceacabf

- [x] @AKM11 
- [x] @njericha
- [x] @hmadej 
- [x] @danscime 
- [x] @niazim3

**Comment by hmadej** [comment]
fixed as of cea9697

**Comment by danscime** [comment]
Fixed SWHS as of 7346b41

**Comment by niazim3** [comment]
Updated as of ab241ce.

**Comment by AKM11** [comment]
Fixed as of commit 6b518ca671be75272afc5dfd4af77cb0b23faab1
