### ISSUE TITLE
Create Functions for Each Section in the Examples

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#184]
For @AKM11 
assumption conts sects = section (titleize' assumption) conts sects
thModel conts sects = section (titleize' thModel) conts sects
genDefn conts sects = section (titleize' genDefn) conts sects
dataDefn conts sects = section (titleize' dataDefn) conts sects
inModel conts sects = section (titleize' inModel) conts sects
datumConstraint conts sects = section (titleize' datumConstraint) conts sects
requirement conts sects = section (titleize' requirement) conts sects
nonfunctionalRequirement conts sects = section (titleize' nonfunctionalRequirement) conts sects
functionalRequirement conts sects = section (titleize' functionalRequirement) conts sects
likelyChg conts sects = section (titleize' likelyChg) conts sects

**Comment by AKM11** [comment]
Thanks
