### ISSUE TITLE
Section Function Change

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#185]
The Example.Drasil.SRS file now has a list of individual functions for each section.  When possible, import SRS into Body and change the section ('title') parts of the section functions into their respective counterparts.
e.g.:
`section (titleize specificsystemdescription)[s4_intro] [s4_1, s4_2]`
->
`SRS.specSysDec [s4_intro] [s4_1, s4_2]`

- [x] SWHS
- [x] PCM
- [x] GlassBR
- [ ] HGHC
- [x] SSP
- [x] GamePhysics

Thanks

**Comment by niazim3** [comment]
GlassBR has been updated for the section headers currently defined in SRS, but I still need to update the section headers that are specific to my example.

**Comment by niazim3** [comment]
GlassBR updated as of commit decb291.

**Comment by njericha** [comment]
tiny does not have this section
