### ISSUE TITLE
Software Plurals?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#186]
So, last week (commit 1f1d89cf5c5670206469c764c058e6d3e525225) I changed some terms in Drasil\Concepts\Software so that they were singular instead of plural.  However, I could not find any changes to the resulting output after I did so and could only find references to the items in functions labeled `makeImpModule` in the Module.hs files in GlassBR, HGHC and SWHS.  To this end, I was wondering what the `makeImpModule` actually pulls from the terms and what modifications (if any) need to be made to accommodate for the pluralization.

**Comment by JacquesCarette** [comment]
This is basically because the stuff related to modules has not have had their keywords pulled out.  And quite a bit of this will need some fixing.  It's not really a design issue.  You are quite right to point this out though.

**Comment by njericha** [comment]
Non issue?

**Comment by AKM11** [comment]
Ironically, we just found what this did.  Apparently the `makeImpModule` function pulls out the term (e.g. input parameter) to use as a title.  There are a number of items in the logs (which are now easier to see now that so many lines have been cleared) that directly relate to this change.  To this end, is it more correct to leave the term itself as a singular and adjust the `makeImpModule` function to pluralize said terms or leave the terms as plural and simply view them as names to a singular entity?

**Comment by JacquesCarette** [comment]
Leave the term as singular, definitely.  Yes, adjust `makeImpModule`, but don't fuss about it too much, as that is likely to change very soon.

**Comment by szymczdm** [comment]
I'm assuming this issue is closed now (especially with the code gen changes that have been made), unless anyone says otherwise.

**Comment by AKM11** [comment]
This issue is still not fixed.

**Comment by AKM11** [comment]
Wait, my mistake, misread the log. Looks like someone fixed this issue (I hope?).
