### ISSUE TITLE
`+:` versus `+:+ ":"`

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#188]
Figure out why `+: S "1"` causes a discrepancy 
(747c747: should get `<a id="Table:T1UCT">` but actually get `<a id="Table:T1:UCT">`)
and `+:+ S "1:"` does not.

**Comment by niazim3** [comment]
It turns out, only using `+:` within a Table title is causing the discrepancy; that too not in the output, but in the internal files. For example,
![image](https://cloud.githubusercontent.com/assets/28247301/26413334/b5396da6-4079-11e7-87e9-f6ef4bc59a2d.png)
@szymczdm @JacquesCarette  Would it be better to leave the stable files as is and just use `+:+ ":"` in the Body of GlassBR or use the newer `+:` combinator and update the stable .aux, .html, and .tex files?
![image](https://cloud.githubusercontent.com/assets/28247301/26413229/498fa23c-4079-11e7-96a5-e3f155baec3c.png)

**Comment by szymczdm** [comment]
I think this is actually related to #208 since the labels are auto-generated. I'll need to look at it in a bit more depth, but you should use the `+:` combinator for now, until I figure out whether this is a problem.

**Comment by niazim3** [comment]
Updated GlassBR to use the `+:` combinator as of commit 67fd4c5.

**Comment by njericha** [comment]
Presuming this is fixed now since #208 is closed?
