### ISSUE TITLE
Logarithm (and other math symbols)

### ISSUE THREAD

**Issue by Sodaaaa** [JacquesCarette/literate-scientific-software#19]
Currently unable to write the logarithm of sth in Expr.

**Comment by JacquesCarette** [comment]
logarithm is important enough to add to the core language.  But soon enough, this will get out of hand, and so we'll need to build some kind of 'library' of known functions and then be able to call these in Expr.  That should be opened as a separate issue, as it needs design.  [We may eventually remove log, when the library works well enough].

**Comment by lmawarid** [comment]
Currently also unable to write integral symbols, summation symbols and single/double absolute value bars (temporarily circumventing this issue by using (Atomic "||r||")). Not sure if I should raise a separate issue since this seems to be in a similar category, so I'll just add on here for now.

**Comment by JacquesCarette** [comment]
Please raise a separate issue for each (integral, summation, absolute value, norm).  While similar at the level of display, they are fairly different semantically, and so may end up requiring a different design.

**Comment by JacquesCarette** [comment]
Note that first leaving a comment here was an excellent first choice.  If what was missing was (for example) 'sin' and 'cos', probably having them added to this issue would have been the correct thing to do.

**Comment by lmawarid** [comment]
Alright, opened separate issues for all of them.

**Comment by szymczdm** [comment]
Log has been implemented (along with some others).
