### ISSUE TITLE
Port SWHS Code to Water Only Example

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#191]
1. Copy the CCode and Python code from the Program folder from the SWHS example (https://github.com/smiths/swhs/tree/master/Program).

2. Modify the C code example and the Python example to work when there is no PCM.  This should just involve deleting things to simplify the other example.

3. The C code and Python examples also include unit tests.  You should also port the subset of those unit tests that apply for the only water example.

What we would like is for the only water example to have a working C and Python implementation.  At present there is only a Matlab implementation for PCM.  The approach I outlined is to copy the files from the swhs repo and then start deleting parts until you get the subset of the original that only includes heating of the water.

Later on (hopefully this summer!) we will take what you are producing manually and try to automatically produce it with Drasil.  At this point however, this task does not involve Drasil itself.  You should commit your code into the SolarHeatingWaterOnly folder.

**Comment by AKM11** [comment]
Okay, first question, should I be downloading this PyDSTool module referenced in a number of python modules (e.g.: event.py)?

**Comment by smiths** [comment]
As a first step Aaron, you should run the original SWHS example (the one in the swhs repo).  Running this example will require you to install PyDSTool (and some other libraries).  The instructions are in the README file.  The implementation includes a Makefile.

Your water only example will likely also require PhDSTool, since this is the tool used to solve the ODE.  You will not need event.py anymore though, since there will no longer be any events.  You should review the SWHS documentation so that you see how events are used.  (An event is when melting starts - you don't have any melting.)

If you do not like the PhDSTool, you can use a different library to solve your ODE.  Your example only has one very well behaved ODE.  We could find other options to solve it.

**Comment by AKM11** [comment]
I was following the README file and have been trying to run the make command (python version) per suggestion but I continuously get the error: 
```
copy Testing\\inputFiles\\P01.in P01.in
make: copy: Command not found
make: *** [test] Error 127
```
Any advice on what to do?

**Comment by JacquesCarette** [comment]
Are you working on Windows?  What shell do you use when you run the above?

**Comment by AKM11** [comment]
Yes, I am working on Windows.  I am trying to run the make/make test command in the command line.
...
Actually, should I be using the Python shell?

**Comment by JacquesCarette** [comment]
I don't think the Python shell would make a difference.  The thing to look at is what is in your PATH.  Try

    echo $PATH

in your terminal.  Not sure where copy.exe is.  [I actually recommend installing cygwin - http://cygwin.org - instead of using cmd].  This is the kind of problem which is easiest debugged in person; hopefully @szymczdm  is around to help.

**Comment by AKM11** [comment]
Thanks Dr. Carette, Dan just stopped by and suggested something similar.  It seems to be working now.

**Comment by AKM11** [comment]
New question, I was following the steps in the README to set up the CVODE library when I was directed to the Sundials installation pdf.  I got to the step asking me to run cmake-gui ../<source directory> (section 1.3) and now I am having problems.  Can anyone explain the sub-steps following this one? Thanks.

**Comment by smiths** [comment]
Hello Aaron.  If there is a new question, there should be a new issue.  :-)  You should also close the above issue, if the problem is sorted out.

My first suggestion is that you work with your colleagues on this.  @hmadej would be a good place to start.  Since you are in the same office, and because there is often iteration required, in-person discussion is usually more effective than the issue tracker.  If you do need to use the issue tracker, you will need to include considerably more information in your issue post.  You should specifically say what OS you are using, what you tried and especially the text of any error messages.  Screen shots are often helpful for this.  If you want people to help you, then they need to be able to at least partially reproduce what is happening on your machine.

**Comment by AKM11** [comment]
Oh, sorry, misunderstood the email.  Thank you for the advice.
