### ISSUE TITLE
Update use of UWrapper in examples

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#192]
I just broke some (all) of the examples by making a change to how Unitals work. You should be able to fix this by replacing any use of `uw` (or other UWrapper constructor) with the new `ucw` (UCWrapper) constructor.

If you can't get it working, or some new error pops up, let me know. We'll continue using the check off method for ensuring examples are updated (when all the boxes are checked, please close the issue):

- [x] gamephys
- [x] glassbr
- [x] pcm
- [x] swhs
- [x] ssp
- [x] tiny

**Comment by AKM11** [comment]
PCM fixed as of commit 3454ef9fd96192fcb448682e7768ca0452c3ee8b.

**Comment by danscime** [comment]
Fixed SWHS as of ae008cd

**Comment by niazim3** [comment]
GlassBR did not use `uw`.

**Comment by njericha** [comment]
fixed d73b09dc27f6ecb631e2b0b41262af8af9f9c96a

**Comment by hmadej** [comment]
gamephys does not use uw
