### ISSUE TITLE
Converting Symbol to String?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#194]
In order to close issue #113, I want to get rid of a duplication, specifically, 'aspectRMax'. In order to ensure that an abbreviation is not removed from the table of Abbreviations and Acronyms, I'm trying to make ar_max a CINP type, but in order to do that, I need to keep the symbol formatting to retain it's 'max' subscript. However, CINP expects a String as its last parameter, and `(sub (ar ^. symbol) (Atomic "max"))` produce a Symbol type... is there currently a function that converts a Symbol to a String and vice versa? @szymczdm 

Also, I believe there needs to be a consistency of how ARmax is output (i.e. either "ARmax" as it is or "ARmax" with "max as a subscript"); which one would be preferred? @smiths 

(Issue is somewhat related to issue #167)

**Comment by niazim3** [comment]
Or can I create a new chunk type `commonINP_` in CommonIdea.hs which takes in both a Symbol and String? Would that be avoiding the problem at hand? @szymczdm

**Comment by szymczdm** [comment]
I believe I have a solution in mind, it will just take me a bit to get to it. I think if we change CINP's acronym from String to Sentence (and adjust the smart constructors somewhat), we can then use the Symbol as an acronym where necessary.

**Comment by JacquesCarette** [comment]
We should indeed minimize the use of String in datatypes.  More or less, they should occur in noun phrases and inside Sentence, but likely nowhere else.

**Comment by szymczdm** [comment]
I just double-checked, CINP does in fact use Sentence, so I'm just going to create a smart constructor for ones where a symbol is used as the abbreviation. I'll also create a custom constructor for when it could be any kind of Sentence.

**Comment by niazim3** [comment]
How would we call the symbol? 
Using `ar_max ^. symbol` doesn't seem to work because CINP doesn't recognize "symbol" and `short ar_max` isn't working  becuase it "couldn't match expected type 'Symbol' with actual type 'Sentence'".

**Comment by niazim3** [comment]
To get the symbol for `ar_max`, use the following syntax: `(getS ar_max)`.
