### ISSUE TITLE
Meta issue: gitlab issues

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#195]
There are 12 open issues on the Drasil gitlab (https://gitlab.cas.mcmaster.ca/smiths/drasil/issues).  Some of these probably should be ported to here.  All of them should be reviewed for 'relevance' and re-assigned as appropriate.

**Comment by smiths** [comment]
Hello Jacques.  Good point.  I have gone through those issues.  Most of them should have been closed a long time ago.  I did find an issue that was not sorted out, so I have recreated in our GitHub repo as issue #196 .
