### ISSUE TITLE
Traceability for GlassBR Assumptions

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#196]
For the SRS for GlassBR, please add cross-references for A1, A2, and A3 in section 6.2.1.  Each assumption should end with a link to the theoretical model (or definition or instanced model etc) that uses it.  The current documentation makes it appear that A1, A2 and A3 are not used by anything.  If that is the case, the assumptions shouldn't even be included.  These assumptions are important though, so we need to find out where they should be invoked.  My guess is that the assumptions would be invoked as part of the theoretical models, with a reference to the original standard that is the source of most of the requirements (Reference 4).

Maryyam, please review the original SRS in the CaseStudies folder, under glass/Documentation/SRS and the original source material, under CaseStudies in folder class, under Reference.  Once you have done this please correct the "manual" (that is, nonDrasil) version of the documentation to properly cross-references the assumptions.  The manual version is where I previously pointed to the SRS, in CaseStudies/glass/Documentation/SRS.

You will not be able to update the Drasil example at this time, since I do not believe that the Drasil DSLs include a facility for cross-referencing between theoretical models and assumptions.  @szymczdm can let us know if it is actually possible to add cross references.

If you notice any other problems with the original SRS for GlassBR, please post these as issues so that we can correct the problems in the original SRS.

**Comment by niazim3** [comment]
Currently, A1, A2, and A3 are not being referenced anywhere except for **A3** being used by **LC1**.
I believe that **A1** can be referred to by the definition of **LR** and **Glass Types** based on the following relations:

![image](https://cloud.githubusercontent.com/assets/28247301/26263076/2e7f3a98-3ca5-11e7-9589-8705e9fa3acc.png)


Before I make any changes, I'd like to confirm that adding a cross-reference between said chunks would make sense, so if these potential differences can please be reviewed (@smiths), that'll ensure that I don't encode anything incorrect.

**Comment by smiths** [comment]
Very good Maryyam!  You have definitely found the source of the assumption from Reference 4.  Yes, please reference A1 in the definition of LR.  You should also reference A1 in the description of IM2 (Calculation of Capacity (LR)).  When you include the citation to Reference 4, please also include the page number for your appendix statement.  (What you are doing now would have been much easier if the original author had done this.)  I do not believe that Drasil yet supports generation of references.  ( @szymczdm can inform us if there is a way to generate references in Drasil.)  Assuming there is not, please just add a sentence that points the reader to the appropriate part of the reference, so that we do not lose this important information.  I suggest  you include in IM2 a full quotation of the part you have highlighted in green.

**Comment by niazim3** [comment]
Update: Commits 60cd55c and 8e21457.
For the time being, should the stable files also be updated or just the manually generated ones?

**Comment by smiths** [comment]
Please update the stable files too.

**Comment by niazim3** [comment]
Also, "A2: This practice does not apply to any form of wired, patterned, etched, sandblasted, drilled, notched, or grooved glass with surface and edge treatments that alter the glass strength." is quite vague but like you stated, extremely important. However, I cannot seem to find a strong correlation between the assumption and a pre-existing requirement, definition, etc... is it suitable to create a new requirement that follows this assumption or to reference this assumption somewhere in the introduction?

**Comment by smiths** [comment]
Hello Maryyam.  The assumption comes from E1300-09A.29610 in the Reference folder.  The scope section lists this assumption in sub-section 1.4.  The assumption is used in the calculation of the load resistance, so you should reference this assumption in the same places where you reference A1.  Please make clear in the revised text that the assumption comes from E1300, on page 1.  We don't want this to be easy to find for anyone searching in the future.  😄 

You can update both the stable version and the manually produced version of the SRS.

**Comment by niazim3** [comment]
Added A2 references as of commit 224964a. Please let me know whether the format of the references I have added is correct; otherwise, it seems this issue can be closed?

**Comment by smiths** [comment]
Looks good.  Yes, we can close this issue.
