### ISSUE TITLE
Create foldlList "list" function

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#197]
Just so it's on record that we made a function that takes a list of sentences and creates a sentence by putting commas between the elements, ending in a "_, and _". Ex. 
`(foldlList [this, other, that]) -> this, other, and that`

**Comment by JacquesCarette** [comment]
I'm pretty sure I had already created such a function.  But quite likely not in a very visible place [i.e. it's my fault you guys didn't know about it].

We need to better document our sentence combinators.

**Comment by hmadej** [comment]
added foldle1 which uses first value in the list as the accumulator for foldle.
