### ISSUE TITLE
Making sure people know about foldlsC

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#199]
I wanted to clean up some places where `(foldl (:+:) (EmptyS) $ intersperse (S ", ") _)` was used. I've make `foldlsC ` that folds a list of sentences with commas and a space. Correct me if there is already a function that does this. ex. `(foldlsC [S "a", S "b", S "c"]) -> S "a, b, c"`. See 57eb4dbba3656432689220e3e2693d7e9b922bd2

**Comment by JacquesCarette** [comment]
See the comment I just left on that commit.

**Comment by njericha** [comment]
to copy what I replied on the commit, @JacquesCarette 

Not exactly. (foldle sC sC EmptyS) will put a comma at the start of a list.
ex. (foldle sC sC EmptyS) [a,b,c] -> ", a, b, c"

**Comment by JacquesCarette** [comment]
Indeed.  This feels like an idiom that already exists in Haskell, I just can't quite put my finger on it.  Ah well, that can be optimized later, it is the existence of `foldlsC` which matters.

**Comment by njericha** [comment]
`intersperse sC` fells like it should work but we can't do that since sentences aren't treated as "list of characters"
