### ISSUE TITLE
Including brackets in expressions

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#2]
@szymczdm 

Is there a way to include brackets in expressions (Expr) so that they will appear on the final printed product? 
I've tried simply adding the brackets to the expression code, and I've tried using the " :* " operator, but neither method added brackets to the SRS document.

Brooks

**Comment by szymczdm** [comment]
Looking into it. Can you please show me the exact example you are trying to do?

**Comment by smiths** [comment]
Hi Dan.  Please look at PCM_SRS DD1 and DD2.  generically: q = h*(T_a - T_b)

**Comment by szymczdm** [comment]
This should now be fixed. Brackets should be added automatically for those types of expressions. Please test it out and let me know. I'll be opening another issue for explicit grouping of expressions.

**Comment by bmaclach** [comment]
It seems to be working.

However, when we want to show a symbol as a function of another one, a similar problem arises. For example, in PCM_SRS DD1 and DD2 there are temperatures as functions of time. Could brackets be added for this purpose? Should I open a new issue for this?

The heat flux itself is also a function of time. But, since it's on the left side of the equation and EqChunks only define the right side of the equation, I wouldn't be able to add brackets there anyways, so this might be a separate issue altogether.

**Comment by szymczdm** [comment]
Sounds like the issue is actually that we need to add the ability to
represent functions into Expr. That is a separate issue entirely.
