### ISSUE TITLE
Summation symbol

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#20]
Currently unable to write summation symbol with Drasil.

**Comment by szymczdm** [comment]
Can you give a little more detail and/or an example of where you need it? Is it just a matter of adding Sigma to the language or expressing a sum in an equation/expression?

**Comment by palmerst** [comment]
This issue also applies to my example.  In my case I require it (as well as product notation symbol) in the context of equations/expressions.  See attached image from my SRS:

![summation](https://cloud.githubusercontent.com/assets/14371273/15683013/3f0d2cfe-272e-11e6-9b3b-2fef051338cb.png)

**Comment by lmawarid** [comment]
I require it as well in a similar context (equations in a table), for example:

![image](https://cloud.githubusercontent.com/assets/16506055/15683688/97d84ef6-2731-11e6-8915-e37a6fc20444.png)

**Comment by szymczdm** [comment]
Summation is implemented, however, I have not solidified the design choices for displaying bounds. That may take a little while.
