### ISSUE TITLE
Pull common "changes" out of examples and move them to Changes.hs

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#200]
I've created Data\Drasil\Changes.hs so we can put the common "likely changes" and "unlikely changes" there and simply call them in our examples similar to what we did with Modules.hs. If you have general likely/unlikely changes, put them in Data. Also check if your items are already in Changes.hs. See 982479ab46bebdd7c5a5d0af3778eac786755bfc

- [x] @hmadej 

- [x] @njericha

- [x] @niazim3 

- [x] @danscime 

- [x] @AKM11

**Comment by AKM11** [comment]
The Changes file is not present in PCM.

**Comment by njericha** [comment]
Done 8dea92d3f3b9b36635cc97a1d8d7b41c300f00e6

**Comment by danscime** [comment]
Added to SWHS as of 9f32278

**Comment by niazim3** [comment]
GlassBR updated as of 4add041.
