### ISSUE TITLE
Typo in GamePhysicsSRS case study

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#201]
In instances models -> IM1 -> Description:
is:
`ai(t) is the i-th body’s acceleration at time t **(m)**.`
should be:
`ai(t) is the i-th body's acceleration at time t **(ms−2)**.`

should the case study be updated?

**Comment by hmadej** [comment]
fixed as of 577932a

**Comment by smiths** [comment]
Thank you for catching this type Henry.
