### ISSUE TITLE
Fix Awkward Text in GlassBR SRS

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#202]
Hello Maryyam.  I noticed while reading your SRS except for issue #196 that the citations are awkward in the text of GlassBR.  For text like "as defined in [5] in Reference" please delete the "in Reference".  This request applies to all instances of "in Reference" that I could see in the excerpt, and probably also elsewhere in the document.

Can you please make this fix in your Drasil code and in the "manually" produced version in the CaseStudies folder.  I do not know if we will always maintain both versions, but for now I would like to.

**Comment by niazim3** [comment]
Completed as of commit da71599. The version in CaseStudies did not have the 'in Reference' text present.

**Comment by smiths** [comment]
Great!
