### ISSUE TITLE
Cannot fix SRS header 

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#203]
```
184c184
< SRS & Software Requirements Specification
---
> SRS & Software Requirement Specification
```
For some reason "requirement" is still not plural. This is a new issue since we changed "srs" in Documentation.hs to use a compoundNPNC rather than the exact string we needed. If anyone wants to try and fix this feel free. 
my attempt bc3f18c84d09f4b11587e297d43f04e72a2a55f4

**Comment by AKM11** [comment]
At least a temporary fix as of commit 14fa21db0bf099fadab8b5be7395691a62350583.

Note: long story short, I was not able to fully test the example due to problems elsewhere.  I think it is running fine but other minor errors may still pop up.
