### ISSUE TITLE
Instance Model typo for gamephys.srs stable version

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#204]
SRS->Instance Models-> IM3

`P**k**(to) `is how the variable is defined in the input and output section however
`p**i**(t)` is how it is defined in the description

all the other variables for this instance model are defined using k consistently in input, output and description:

`v**k**(to)`
`v**k**(t)`

is I and k being used interchangeably for position?

also a "p**2**(t)" is defined in output, but doesn't seem to defined or used anywhere in that specific instance model.

**Comment by smiths** [comment]
i and k are dummy variables, so technically i or k (or anything else could be used).  However, it really doesn't make sense to be inconsistent.  Please use k for all instances.

Please remove p_2(t).  It seems to be an error to me.

**Comment by hmadej** [comment]
Updated to use k of for all instances, and removed p_2(t). 418fcc7
