### ISSUE TITLE
Fix use of contraint_

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#205]
If anyone is using constraint_ change it to constraint (i.e. remove the underscore.) Make will be broken until done so.

- [x] SWHS
- [x] GlassBR
- [x] SSP
- [x] GamePhysics
- [x] PCM

**Comment by hmadej** [comment]
gamephys updated - cdf107e

**Comment by danscime** [comment]
Make is running, meaning constraint_ is not being used anywhere.
