### ISSUE TITLE
Running into an error in a file I didn't alter?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#206]
Make runs into an error that states: `chipmunkdocs.EXE: SRS/Chipmunk_SRS.tex: commitBuffer: invalid argument (invalid character) make: *** [gamephys] Error 1`

I'm not sure how to fix this so I'd appreciate any suggestions...

**Comment by szymczdm** [comment]
Have you tried asking @hmadej ? He's been the most involved with that example.

**Comment by hmadej** [comment]
issue seems to arising from adding instance models to gamephys, the issue does not appear to happen on my machine however, for now commented out instance models.  991b820

**Comment by JacquesCarette** [comment]
@szymczdm please track down what's going on, then assign to the most appropriate person.

**Comment by niazim3** [comment]
It turns out the error was being caused due to some unicode characters not being recognized, fixed through commits d2931b3 and 3febf55.
