### ISSUE TITLE
Problem building haddock documentation

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#209]
I've an issue with running `make docs`. If you do it on a clean install of the haskell platform (or stack), it will fail due to the following error:
```
Language/Drasil/Code/Imperative/Helpers.hs:11:1: error:
  Failed to load interface for 'Data.String.Utils'
```

I'm not sure why this is, as Data.String.Utils is part of MissingH which should be installed by (and available to) stack. I have no problems on my main dev machine.

@JacquesCarette can you take a quick look and let me know if you see something obvious?

**Comment by JacquesCarette** [comment]
I think you want `stack haddock` (https://docs.haskellstack.org/en/stable/build_command/) rather than raw `haddock`.  The latter will look in your global haskell install, and not your local one.

**Comment by szymczdm** [comment]
Closed as of 76207abbbf1c1a81e91d6902eea88569a782833c

**Comment by smiths** [comment]
Thank you @szymczdm and @JacquesCarette .  Make docs works with no problems now.  @szymczdm , I like your explanation of make docs in the README file.  This will definitely help future users, and me, every time I forget where to find the generated documentation.  It isn't issue worthy, but at some point I would like to discuss why stack puts the compiled code and documentation in a hidden (and fairly deeply nested) folder.  I'm sure there is a good reason, but it seems odd to me.  😄

**Comment by JacquesCarette** [comment]
Isn't there a `stack install` step that one can take to 'install' the code somewhere easy to find?

**Comment by szymczdm** [comment]
`stack install` will move the executables to an "easy to find" location (your bin folder / AppData on Windows). As for the documentation, I can't find anything on moving it somewhere easier to find. The only "easy" way to get to it I've found is `stack haddock drasil --open` which will open it in your browser after it builds.

**Comment by smiths** [comment]
Thanks for the info @szymczdm .  Interestingly stack install puts the executables in the following folder /Users/smiths/.local/bin on my machine.  I looked into it a bit and it seems that the stack people didn't want a collision with the more standard /usr/local/bin.  If you put the .local/bin file on your path, then the programs you install with stack could be run from anywhere.  There is probably a way to locally configure stack install to put the files somewhere else, but I don't think this is something we need to worry about at the moment.
