### ISSUE TITLE
Integral symbol

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#21]
Currently unable to write integral symbol with Drasil.

**Comment by lmawarid** [comment]
Yes, I need it for an equation in a table:
![image](https://cloud.githubusercontent.com/assets/16506055/15683747/da659a6c-2731-11e6-882e-3f70cd33831e.png)
There are no bounds in this specific instance, but I've needed bounds for derivations elsewhere in the document.

**Comment by szymczdm** [comment]
Implemented. See my comment on summations regarding bounds.
