### ISSUE TITLE
Cross-reference Tables in SRS for Game Physics

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#210]
If possible, please replace hard-coded cross references to tables with Drasil code to automate this.  For instance, in Body.hs, the reference to Tables 1 and 2 is hard coded into the string:

s4_2_6_intro = Paragraph $ foldlSent 
  [S "Table 1 and 2 show the", (plural datumConstraint),S "on", ...

@szymczdm has said that automatic cross referencing is possible.

Requirements that should point to a table should have an explicit reference to the table added.  For instance, 

s5_1_req4 = foldlSent [S "Verify that the inputs", 
  S "satisfy the required", plural physicalConstraint]

should have a reference generated to Table 1 (data constraints).

**Comment by hmadej** [comment]
added references for table 1 and table 2  b3ca1ce , will continue adding references anywhere I see them missing.
