### ISSUE TITLE
Parameterizing the Figure, Table, and Traceability Graph/Matrix Labels

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#215]
Would it be possible to agree on a consistent labelling format? @smiths 
That is, should the words "showing the connections between" be capitalized (like GlassBR and SWHS) or not (like GamePhys)
![image](https://cloud.githubusercontent.com/assets/28247301/26457150/27491ff4-413d-11e7-8872-7a3c7675fc90.png)

**Comment by smiths** [comment]
Yes, I like consistent capitalization.  It would be idea if this were a documentation configuration that could be changed.  Some journals and authors have different conventions.  @szymczdm would be able to say if this would be easy to do or not.  If this is something to worry about in the future, please use the capitalization convention from SWHS and GlassBR in all examples.  (That's the one that I like best.)  😄

**Comment by niazim3** [comment]
Update labels of tables, figures, and/or traceability matrices/graphs in examples to use `figureLabel` and/ or `showingCxnBw`:
- [ ] GlassBR

**Comment by niazim3** [comment]
GlassBR updated as of commits e69d549 and 4ad30eb.

**Comment by JacquesCarette** [comment]
Sigh.  I prefer the other capitalization...  Oh well, can't win them all.

**Comment by smiths** [comment]
Someday Drasil will have a "capitalization convention" parameter, and then we can both be happy.  😄

**Comment by danscime** [comment]
Updated SWHS as of 60ee9b68be64f0bebfd8022a65d28edae62732ae
