### ISSUE TITLE
Use Cross references when possible

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#216]
Please go through your Drasil code and use automatic cross references where possible.  Henry has done this with his two tables, as shown in commit:

https://github.com/JacquesCarette/literate-scientific-software/commit/b3ca1cebb604d9bf7e8454f4380f8c68cc24b3d2

I noticed in issue #213 that the table numbers are hard coded in integer strings.

Once you have completed this for your code, you can mark it as done in the task list.

- [x] @hmadej 
- [x] @niazim3 
- [x] @danscime 
- [x] @AKM11 
- [x] @njericha

**Comment by njericha** [comment]
I can't fix this yet because my "table 2 and 3" do not exist in my code yet

**Comment by danscime** [comment]
I also cannot fix as I don't have the tables in my code.

**Comment by AKM11** [comment]
NoPCM is also missing numbered tables.

**Comment by smiths** [comment]
@njericha and @danscime , can you just create a dummy empty table?  This would give you a placeholder that you can fill in later.

**Comment by AKM11** [comment]
Added dummy tables as of commit e2e83c42587c4163b6a58559b137b9871de4fa34.

As a side note, I do not actually have anywhere to reference the tables. The Data Constraints section does not exist. Should I add it?

**Comment by smiths** [comment]
Yes @AKM11 , please add a Data Constraints section.  We can worry about the content at a later time, but please add the section as a placeholder.

**Comment by njericha** [comment]
Did SSP b27d3a15d8e679cfffa65203cbeec50ccd38f258

**Comment by danscime** [comment]
Created and referenced dummy tables for SWHS as of 7b8f9c40d1e4c6a9c55f58c94871c13ab3eef96f

**Comment by niazim3** [comment]
GlassBR updated as of commit 932880a.

**Comment by AKM11** [comment]
Blank Data Constraints section added and tables referenced as of commit 97a7653a187512b5d237a6937837478fde4d5cc2.
