### ISSUE TITLE
Using '^. unit'?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#218]
In order to complete #216 for GlassBR, Table 2 needs to be cross-referenced.
Table 2 is predefined within `s6_2_5_table1`, which was previously commented out. Trying to compile after removing the comments resulted in the following error:
![image](https://cloud.githubusercontent.com/assets/28247301/26464379/9d35628c-4155-11e7-92de-f1410e784d85.png)
This may to be the reason why other tables were commented out as well; is `^. unit` not how to access the unit of a unitary chunk? @szymczdm

**Comment by szymczdm** [comment]
That's an interesting issue. I'll take a look shortly, but to my knowledge that was correct.

**Comment by JacquesCarette** [comment]
My guess is that there is a definition of `unit` (of type `UnitDefn`) in scope which shadows the `unit` lens.

**Comment by niazim3** [comment]
@AKM11 suggested using `unitSymb` instead and it seems to work.
Closed as of commit 1399f87 and 72d5b7b.
