### ISSUE TITLE
Use new inModelF function to make "Instance Models" Section

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#219]
See 327a7ae4b195841318becee69b47701f20018cc7

- [x] @hmadej 
- [x] @niazim3 
- [x] @danscime 
- [x] @AKM11 
- [x] @njericha

**Comment by danscime** [comment]
SWHS updated as of 67e2e8f

**Comment by niazim3** [comment]
GlassBR does not have an introduction following **Instance Models**, so will not be implementing `inModelF`, unless it needs to be added to the original CaseStudies.
@smiths Should the following generic introduction to **Instance Models** be added to GlassBR?
"This section transforms the problem defined in this Section into one which is expressed in mathematical terms. It uses concrete symbols defined in this Section to replace the abstract symbols in the models identified in this Section and this Section."

**Comment by smiths** [comment]
Hello Maryyam.  Yes, please add the generic introduction.  The introductory text was not left out of the original on purpose.  It was simply missed.

**Comment by niazim3** [comment]
GlassBR updated as of commit 051fd6f.

**Comment by AKM11** [comment]
Place holder sections created and inModelF function employed as of commits 3831679fce55c674ab8d21f483710b9e5dc65888 and c81aca1925216c5ef1dc22ab1a4894e0e9e51f2b
