### ISSUE TITLE
Absolute value bars

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#22]
Currently unable to write absolute value bars in Drasil.

**Comment by szymczdm** [comment]
Again, please provide an example of where it is necessary and I'll get on it.

**Comment by lmawarid** [comment]
Sure. Once again, I need it for an equation in a table. I don't actually have an example for the abs themselves, but I do have one for the norm below and I assume they're closely related:
![image](https://cloud.githubusercontent.com/assets/16506055/15683843/5df87052-2732-11e6-8277-bf08d619c9f1.png)

**Comment by szymczdm** [comment]
Abs is implemented, norm is not yet.

**Comment by szymczdm** [comment]
Closing this as there is a separate issue (#23) for norm.
