### ISSUE TITLE
Move All Case Studies to the Case Studies Folder

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#221]
Can you please move the SolarHeatingWaterOnly and hghc_Example to the CaseStudies folder, and update the README.md files in the root folder and the CaseStudies folder?  Now that I have moved ssp to the CaseStudies folder, I think it makes sense to have all of the examples together.  It should make it easier for us to find things going forward.

**Comment by AKM11** [comment]
Files rearranged and READMEs updated as of commit 049360d241988f39992a867d7ced95416a9a6a28.

**Comment by smiths** [comment]
That was quick!  Thank you Aaron.
