### ISSUE TITLE
Consistency when referencing?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#224]
There should probably be some consistency when referencing Tables.
Is it better to have it state something to this effect:
"**Table 5 (this Table)** shows the dependencies of theoretical models, data definitions and instance models with each other."
or without the Table number:
"**this Table** shows the dependencies of theoretical models, data definitions and instance models with each other. "?
@smiths

**Comment by njericha** [comment]
related to #223

**Comment by smiths** [comment]
My understanding is that when the target is html the second option ("this Table shows ..") is generated, and when the target is Latex, the text will come put as Table 5 (or whatever number).  Automatically numbering tables is taken care of by LaTex.  They are numbered in the order that they occur.  Html doesn't have this, so we use a hyperlink.  @szymczdm can clarify if I have misrepresented how cross referencing works in html versus LaTeX.

Assuming I am correct, I like the way it is currently done.  There is no need for the LaTex and html documentation to be exactly the same.

**Comment by niazim3** [comment]
Question answered in comment of commit a1e336f.
