### ISSUE TITLE
Create a wrapper/function to reduce duplication in GlassBR?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#226]
Although issue #113 has been closed due to reduction in code duplication via the deletion of some variables and an increase in cross-referencing between similar variables, can there be some new type of wrapper/function/dataType that reduces the need to even cross-reference between similar variables and chunk all the necessary data associated with every variable into one type? I'm not really sure if this would improve code readability/efficiency or how exactly this may be applied, but doing so may reduce the need to have 2 similar variables for the same concept (e.g. `prob_br\probBreak`, `nonFL\nonFactoredL`, etc.)

**Comment by JacquesCarette** [comment]
Could you expand on the duplication that you see?  Thanks for referencing explicit concepts in the description above, but it's still a little cryptic for me to wrap my head around this problem (how difficult, important, etc).

**Comment by niazim3** [comment]
For example, currently, `prob_br` is a `VarChunk` and `probBreak` is a `ConceptChunk` defined as follows:
`prob_br = vc "prob_br" (nounPhraseSP "probability of breakage") (sub cP lB) Rational`
and
`probBreak = dcc "probBreak" (prob_br ^. term) ("The fraction of glass lites or plies that would break at the first " ++ "occurrence of a specified load and duration, typically expressed " ++ "in lites per 1000.")`
Since these are defining the same concept (i.e. the probability of glass breaking), perhaps we can create a single concept of some sort that has an
- id
- term
- definition
- symbol
- space
- unit (although not applicable in this example)?
Like I stated before, I'm not sure if this would be acceptable from a conceptual standpoint (i.e. should concepts have symbols?), or whether or not this is the correct approach to further reduce duplication, but if it is applicable it may reduce chunks building off of other chunks.

**Comment by JacquesCarette** [comment]
It "has to" make sense - because this is how 'probability of breakage' is being used.

Note that the best thing to do here is to introduce a new Space, Probability, and drop the constraints.

It is a little surprising that we have no data-structure to do this yet.  @szymczdm ?

**Comment by szymczdm** [comment]
I may be misunderstanding something, but we have chunks that include an id, term, definition, symbol, space, and unit (they're Unitals), and those lacking units are ConVars. 

The "Probability Space" would definitely make sense, especially since it would create an implied constraint, which would be simple to make explicit when generating the table of constraints.

**Comment by szymczdm** [comment]
@niazim3 has this issue been resolved, or do we need to create/modify a data structure?

**Comment by niazim3** [comment]
@szymczdm 
No changes have been made, however, at the same time, there currently isn't a direct example where a change would drastically alter anything. 
I had created this issue as a more general question to see if there is possibly a design element that can be implemented so that a concept can contain every piece of information it may need (e.g. id, term, defn, eqn, symbol, unit, space, acronym, constraints, etc.) in a single chunk instead of having its elements distributed in difference types, in order to decrease the multiple chunks for each chunk/idea.
It seems that such a structure implementation isn't necessary at this point though, so I suppose this issue can be closed.
