### ISSUE TITLE
Formatting Introduction for GlassBR?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#228]
In order to use the newly created `introF` function that automatically generates part of the introductory paragraph, I was wondering if it matters that "This section explains the purpose the document is designed to fulfil, the scope of the requirements and the organization of the document: what the document is based on and intended to portray." is changed to "This section explains the purpose of this document, the scope of the system, the organization of the document and the characteristics of the intended readers.", that too as part of a second paragraph (as opposed to the single paragraph that followed the introduction in the CaseStudies version of GlassBR)? 
The 2 sentences are quite similar in content, however they are worded differently...
(Commit 7fa8845)

**Comment by smiths** [comment]
Hello Maryyam.  I have no problem with changing the text of any of the sections to have it match with your standardization efforts.  However, I think your proposal introduces information that is not in your SRS.  Your proposed text mentions the characteristics of the intended readers, but you do not have this section in your document.  

My advice is to add the section "Characteristics of Intended Reader".  You can follow Section 2.3 of the SWHS example (https://github.com/smiths/swhs/blob/master/SRS/PCM_SRS.pdf).  If you add this section, I have no problem with your proposed standardization of the introductory text.

**Comment by niazim3** [comment]
Thank you @smiths. After a deeper look into other examples, it actually turns out SSP and GamePhysiscs also do not have the "Characteristics of Intended Reader"

**Comment by smiths** [comment]
Yes, SSP and GamePhysics should add the "Characteristics of Intended Reader" section as well.  Can you please coordinate with @njericha and @hmadej ?  We can create an issue if necessary.

The characteristics section is about the people reading the document.  The user section is about the people using the software.  They aren't necessarily the same people.
