### ISSUE TITLE
Norm symbol

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#23]
Currently unable to write the norm symbol (double absolute value bars) in Drasil.

**Comment by szymczdm** [comment]
Can you provide an example of how/where norm is used?

**Comment by lmawarid** [comment]
Sure, here's an example:

![image](https://cloud.githubusercontent.com/assets/16506055/16389737/4dd74112-3c6d-11e6-8b17-d39d0cfb63d9.png)

**Comment by szymczdm** [comment]
This one needs design based on what we mean by "norm" and how we can specify which norm we want to use.

**Comment by JacquesCarette** [comment]
We should sort-of be able to figure this out from the units/dimension of the resulting symbol.  Still needs design, but I think we can infer this.
