### ISSUE TITLE
Add the "Characteristics of Intended Reader" section to Examples

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#230]
As discussed in issue #228, **GlassBR**, **SSP**, and **GamePhysics** should add the "Characteristics of Intended Reader" section. As @smiths mentioned, we are to follow Section 2.3 of the SWHS example (https://github.com/smiths/swhs/blob/master/SRS/PCM_SRS.pdf).

- [ ] @hmadej 
- [x] @niazim3 
- [x] @njericha

**Comment by smiths** [comment]
Thank you for coordinating th is Maryyam.

**Comment by niazim3** [comment]
Where are we getting the information to fill in the first 4 parameters for the currently automatically generated section defined in **OrganizationOfSRS.hs**? @smiths 
`--Characteristics of Intended Reader section
charIntRdrF :: Sentence -> Sentence -> Sentence -> Sentence -> Sentence -> Contents -> Section
charIntRdrF know c1 und c2 progName r = 
  SRS.charOfIR (intReaderIntro know c1 und c2 progName r) []

--paragraph called by charIntRdrF
intReaderIntro :: Sentence -> Sentence -> Sentence -> Sentence -> Sentence -> Contents -> [Contents]
intReaderIntro know c1 und c2 progName r = [Paragraph $ foldlSent [S "Reviewers of this", (phrase documentation),
  S "should have a strong knowledge in" +:+. know, S "A", c1,  
  S "course on this topic is recommended. The reviewers should also have an understanding of",
  und `sC` S "as typically covered in", c2 +:+. S "courses", S "The", (plural user), S "of",
  progName, S "can have a lower level of expertise, as explained in", (makeRef r)]]`

SWHS would call this function using the following code: 
`s2_3 = charIntRdrF (plural $ CT.heat ^. term)
  (S "third or fourth year Mechanical Engineering")
  (S "differential" +:+ (plural $ equation ^. term))
  (S "first and second year Calculus")
  (s3_2)`

**Comment by smiths** [comment]
I'm sorry @niazim3 ; I do not understand your question.  Maybe it is more appropriately directed to @szymczdm ?

**Comment by niazim3** [comment]
Sorry @smiths, I meant to ask about where the _content_ that should be added can be found?
Since user characteristics may refer to a different group of people than the intended readers, we're unsure of what Sentences we should input as parameters (i.e. what should they have "strong knowledge" of, which courses must they have taken, what should they have previous understanding of (and which course that's typically taught in), etc. ).

**Comment by smiths** [comment]
Okay, now I understand.  Please go ahead and make a best guess for the knowledge that users should have.  You can follow the examples where this information is filled in.  It doesn't matter if the filled in information is "perfect."  We just need an idea.  We can always iterate on the details in the future.  The knowledge is usually going to centre around mathematics and physics.  If you can characterize the knowledge in terms of a level of education, that is ideal.  For instance, first year calculus is a fairly precise statement.  The content of a first year calculus course is fairly standardized across institutions.

Let me know (via an issue) once you have a section filled in for review.  I'd be happy to look it over.

**Comment by hmadej** [comment]
I think: "Reviewers of this documentation should have knowledge of _____." "The reader should also have an understanding of _____", "The users of ____" would probably make a good frame for this section.

**Comment by niazim3** [comment]
I agree @hmadej, I'll update the current charIntRdrF to be more generalized.

**Comment by niazim3** [comment]
See 9932829 for the most recent version of charIntRdrF.

**Comment by njericha** [comment]
Assuming this is done @hmadej
