### ISSUE TITLE
"To Do" Error

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#231]
The most recent commit (282ec8cc1aa433b2dedcf47555db9ad8aae2fdd1) made changes to code/Language/Drasil/Code/Imperative/LanguageRenderer/CppRenderer.hs that results in 
![image](https://cloud.githubusercontent.com/assets/28261578/26585388/f7ed33d6-4519-11e7-985c-45fe4f4cfb21.png)
You may already know about this and marked the error as "To Do" to literally mean the code is incomplete but just in case I thought we should bring this to your attention. Any work arounds/suggestions? Thanks

**Comment by AKM11** [comment]
For now we are simply building our examples individually as the error seems to be exclusive to tiny.

**Comment by palmerst** [comment]
Sorry, I forgot to check tiny before pushing!   Fixed in 1d2e544
