### ISSUE TITLE
Add Units

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#232]
Ensure that the Drasil knowledge-base contains all of the units from this inforgraphic:

![da3ldjeuiaakhlg jpg large](https://cloud.githubusercontent.com/assets/235140/26586412/12dc4404-451d-11e7-9dac-e64841d99b61.jpg)

**Comment by szymczdm** [comment]
I've assigned you @AKM11 since you said you were getting close to finishing your current task(s), but if anyone else finishes before you, they can take this issue on.

**Comment by AKM11** [comment]
Added the needed units as of commit 449303187e88f7ed914228f0db24905752047583.
