### ISSUE TITLE
Review Mathematical Model for Calculation fo q

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#234]
Hello Steven.  Can you please review my mathematical model for the calculation of q:

https://github.com/JacquesCarette/literate-scientific-software/blob/master/CaseStudies/glass/Documentation/MIS/MathModelForCalc_q.pdf

This model is a response to issues #41 and #56.  It is also an outcome of our discussion the other day when you were looking for something as a bridge between the requirements and the code.  We can write the definition of q using a functional approach, so I think this is the bridge you were looking for, but I might be wrong. 

The mathematical model is a bit tedious in terms of book keeping (especially for indices), but the ideas are really quite simple.  I think the mathematical presentation is easier to follow than the code.  The one wrinkle is that I ignored the complexity of exceptions.  In particular, I ignored the fact that a particular choice of wTNT and SD might not actually be defined.  We could add the exception to the function indInSeq() and, I believe, handle this problem more "elegantly" than the original code.

Please let me know your thoughts.

**Comment by palmerst** [comment]
Hi Dr. Smith.  Yes, this was exactly what was missing.  It's much more clear than the code was.  I implemented your model in the python code -- it is actually readable and understandable now! (see commit a50b72c86bed7cfb55967bba3028d0d5c6d689d3)   The new implementation throws an exception if it runs outside of the interpolation plot.  The numbers that it outputs are exactly the same as the previous implementation.

**Comment by smiths** [comment]
The code looks great Steven.  Thank you for also applying the same ideas to the calculation of q hat and for incorporating the exception.  This new version of the code is much easier to read and understand.  I didn't do a line count, but it seems shorter too.

@palmerst, I noticed you changed the casts on the inputs from float64 to simply float.  That didn't change your answers?  I remember thinking it was odd, but Thulasi needed the float64 or the results didn't agree with the original FORTRAN code.  If the answer remained the same, our new version seems to also have greater numerical stability than the previous.

**Comment by palmerst** [comment]
Regarding the float64, I wondered why they were necessary so I looked up the difference and it turns out that numpy float64 is actually the same as float.  They are both just 64 bit floating points.  The only difference is in how they are displayed when printed:  https://stackoverflow.com/questions/27098529/numpy-float64-vs-python-float

So for simplicity I just changed them to float.

**Comment by smiths** [comment]
Good to know.  I might be misremembering, but I thought Thulasi required float64, for some reason.  Regardless, I like the look of the revised code better.  With the removal of float64, does the code still depend on numpy?  If we could remove that dependency, the code will be simpler to install going forward.

**Comment by palmerst** [comment]
The only part that is using numpy now is readTable.py, and that's only because it provides convenient one line solution for reading in the interpolation data.  I can rewrite it with the standard file input functions to completely remove the dependency on numpy.

**Comment by smiths** [comment]
Yes, please remove the dependency on numpy.  Going forward, I believe this will make the code generation part easier.  We will eventually have to deal with external libraries, but postponing that problem would be fine with me.  😄

**Comment by palmerst** [comment]
Sounds good to me!  The implementation is now numpy-free in commit 0f5a632d625d65f4edf9e31efa75708a79eee16c

**Comment by smiths** [comment]
Great!  I think we can safely close this issue now.
