### ISSUE TITLE
Find a more elegant solution to "not found in SymbolMap" error that was fixed in GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#236]
Changes made in commit 863d619 were quite hacky, so need to either cross-reference `lDurFac`, `nonFactorL` and `glassTypeFac` in a different manner, or completely change the types of these variables.
This should allow for them to be added to SymbolMap.

**Comment by niazim3** [comment]
Suggestion from issue #272:
"Fix `temporary` in Unitals.hs (bottom of the file) to use ConVar rather than VarChunk. This way you can build these chunks off of `non-factored load` defined in Concepts.hs. You may need to redefine `non-factored load` to be a ConceptChunk. This shouldn't break where it is used though."

**Comment by szymczdm** [comment]
@niazim3 What's your status on this issue?

**Comment by niazim3** [comment]
This issue closes as of commits a9c7b2a...6845603.
