### ISSUE TITLE
Can I simplify this into one function?

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#238]
I have the following code in commit 2fa63c3f702c3aa439558210c95c2a566cc9a17b,
```
mkGtZeroConst' :: (Show a) => ConVar      -> [(Expr -> Expr -> Expr, Expr)] -> a -> [Sentence]
mkGtZeroConst  :: (Show a) => UnitalChunk -> [(Expr -> Expr -> Expr, Expr)] -> a -> [Sentence]
mkGtZeroConst' s@(CV _ _ _)   other num = [getS s, fmtC' s (((:>), Int 0):other), S $ show num]
mkGtZeroConst  s@(UC _ _ _ _) other num = [getS s, fmtC' s (((:>), Int 0):other), fmtU (S $ show num) s]
```

I was having issues with type matching because Haskell didn't like that I had to different possible input types

**Comment by szymczdm** [comment]
You can't mix and match types like that. It looks like you might be able to do something using type class constraints (i.e. (Concept c, Show a) => c -> ...), Where "Concept" would be replaced with whichever constraints you need. Again, this would only work if both are instances of that type class.

Also, what does fmtU do?

**Comment by njericha** [comment]
fmtU :: (Unitary a) => Sentence -> a -> Sentence
fmtU n u  = n +:+ getU u

**Comment by njericha** [comment]
Fixed 8520f5cd55179043e1d0b4dfc865053832dfd221

**Comment by njericha** [comment]
We should have a that "unwrap" function be stored in language because I've used it before when making a table.

**Comment by hmadej** [comment]
unwrap added to utils af3bd59

**Comment by JacquesCarette** [comment]
This `unwrap` already exists in the Prelude -- it is called `maybe`.

And in this particular case, `unwrap` is not great.

The class you want is `Unitary`, not `Quantity`; use the `unit` method, which is guaranteed never to fail.  If you really need `Quantity`, we need to think why that is.  It is often 'weird' to constrain quantities that have no units.

**Comment by njericha** [comment]
I really do need Quantity because one of the items that has a physical constraint is a ratio which is a quantity with no units

**Comment by JacquesCarette** [comment]
How very annoying.  But rather convincing that `Quantity` is correct!
