### ISSUE TITLE
Extra Space in References Numbering

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#239]
TeX renders the items to references with an extra space after the number,

![2017-06-02 1](https://cloud.githubusercontent.com/assets/26230851/26728152/3d83cfd6-4777-11e7-826a-70f6b0c9246d.png)
![2017-06-02 2](https://cloud.githubusercontent.com/assets/26230851/26728151/3d828af4-4777-11e7-8690-de24ce2c8aba.png)

Where as the .html version works correctly. 

![2017-06-02 3](https://cloud.githubusercontent.com/assets/26230851/26728197/65df6418-4777-11e7-8b10-da172ac8b183.png)

@szymczdm said this should be resolved once we switch to using BibTeX

**Comment by hmadej** [comment]
Possible solution that corrects output in tex files:
`[{[}1{]}:]`
Put curly braces around the square brackets when generating the list.

> [1 :] David L. Parnas.
->
> [1]: David L. Parnas.

**Comment by njericha** [comment]
Similar issue happens with the symbol `{x,y}` as html renders it fine but tex only renders the `x,y` part (since tex uses "{}" as brackets.
