### ISSUE TITLE
Units in Data Definition descriptions

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#24]
Since the description sections of the Data Definitions are mostly automated, there is currently no way to show the units for each symbol in parentheses following the description for each symbol.

**Comment by JacquesCarette** [comment]
Can you insert an example of what you'd like?  This sounds like there should be variants to the Data Definition recipe.  We need some requirements, and then Dan can implement such a feature.

**Comment by szymczdm** [comment]
Sounds like we just need to add a config parameter for printing the DDs (if it's necessary). An example would definitely help.

**Comment by bmaclach** [comment]
![ddunitsexample](https://cloud.githubusercontent.com/assets/18634568/15653609/fd118980-265b-11e6-92f9-f0ccb36a9cdc.png)

Here's an example. I'm referring to the units at the end of each line in the "Description" section.

**Comment by JacquesCarette** [comment]
Perfect!

**Comment by szymczdm** [comment]
I'll be implementing this one soon, however, until we have parameterised recipes it will either always be "on" or "off" (as there will be a flag in the config file).

**Comment by szymczdm** [comment]
This one is trickier than I expected. I'm not sure how to extract the appropriate MUChunks from an equation. For example let's say 

    ex_units = --Some units go here
    ex_eq =  2 * (C k_c) * (C h_g)
    ex_chunk = fromEqn "example" (S "This is an example to illustrate extraction problems") lE ex_units ex_eq

k_c is a VarChunk, h_g is a different eqChunk with some other units. I can no longer use "vars" in Expr.Extract to get the chunks if we want to see their units.

Without units, it doesn't matter (convert all to VarChunk and print); with units I am not sure how to figure out whether or not it has units.

**Comment by JacquesCarette** [comment]
So I think the 'mistake' here is that we don't usually infer the units from the equation.  The information is there, but we duplicate it.

You will need to be able to 'walk' an expression to dig out its units, but that is not too hard.

**Comment by szymczdm** [comment]
This should be taken care of when we finish with issue #104 (reimplementing data defs).
