### ISSUE TITLE
Design of GlassBR Discussion

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#240]
In commit 15d01587da6edc132fa8a578a7d0c62b471e3b6b we have been discussing the thickness values input to GlassBR.  I was going to add an issue for @niazim3 to change the code to use approximate equality tests.  After thinking about it further, I'm not so sure this is the best way to go.  I'll summarize the problem below:

The user is supposed to input a value (t) for the nominal thickness from the following set:

{2.5,2.7,3.0,4.0,5.0,6.0,8.0,10.0,12.0,16.0,19.0,22.0}

The program verifies that their input is within this set and then derives the actual thickness (h) from this value.  For instance, a nominal thickness of t = 2.5 is an actual thickness of h = 2.16.  The value of h is a float.  This is the value actually used in calculations.  

We have discussed the bad style of using an exact comparison between floats to determine whether t is in the correct set, and, by extension, to convert t to h.  I agree that comparison of floats for equality is not a good idea.  We were going to introduce an approximate equality, but I wonder if this is the wrong choice?

@JacquesCarette, what do you think of reading in the t values as strings?  This really is equivalent to reading in the "name" of the different types of glass.  The glass is identified as "2.5", but the name could have been "thinnest".  If the user enters 2.500001 as a float, in our proposed change, we would consider this as 2.5, but really it is a user error.  We don't really know if they meant glass 2.5, or mistyped their data.  I don't really like using strings as input either, but we don't have the problem of any ambiguity in exact comparison with strings.  The string would only exist for the purpose of verifying that the user selected one of the valid values for t, and then to convert t to h.

This issue is also relevant for @palmerst .

**Comment by JacquesCarette** [comment]
I agree: for this case, "2.5" is used as a name, not a number, as far as the input module is concerned.  Its validity should thus be checked textually.  Then it can be 'translated' to a number [it could even be done by table lookup!] for internal computations, as "2.5" is the name of something which has a particular thickness.

**Comment by smiths** [comment]
Okay.  We are on the same page.  I'll create an issue for @niazim3 to modify the current GlassBR code.  @palmerst , you will likely want to make corresponding changes to your code generation.
