### ISSUE TITLE
Parameterized symbolMap Function

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#241]
I created this function maker to shorten some parts where we call Things like:
`(Definition swhsSymbMap . Data)`

Just check the commit: 4fb480c

I defined the SWHS functions needed in my Data Defs.

- [x] GlassBR

- [x] SSP

- [x] Game Physics

- [x] SWHS

**Comment by niazim3** [comment]
GlassBR updated as of commit d9d1df4.

**Comment by njericha** [comment]
d702eea7b8479c31c218aa60327e80e0c715cdea

**Comment by hmadej** [comment]
b3f74644
