### ISSUE TITLE
Improvement to GlassBR for processing thickness input

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#242]
As discussed in issue #240, we would like to change the GlassBR code so that t is read in as an string.  This will mean modifying the file inputFormat.py.  Once this change is made the following files will also have to be modified: checkConstraints.py and derivedValues.py.

**Comment by niazim3** [comment]
Done as of commit e56f33b.
@smiths 
Although, I'm not sure whether there was a preference for how many decimal places are taken so if I should change any of the formatting or changes, please do let me know.

**Comment by smiths** [comment]
Looks good Maryyam.  Could you please change it to one decimal place though?  As far as I know, there won't be a case where anyone uses the second decimal place.  You will unfortunately have to change this in multiple places to match, but this shouldn't be necessary once the code generation that @palmerst is working on is functional.

**Comment by niazim3** [comment]
Sure, completed as of commit 4b2ba59.
