### ISSUE TITLE
Implement use of 'IntroSec' in Body Examples

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#243]
An overarching 'introductionF' function has been made to automatically generate subsections ("Purpose of Document", 'Organization of Document", "Characteristcs of Intended Reader", "Scope of Requirements").

GlassBR has been updated as of commit f5e6112.

Please update the rest of the examples so we can close this issue and remove the smaller `introF` function without causing errors. 

- [x] Gamephysics
- [x] NoPCM
- [x] SWHS
- [x] SSP

**Comment by niazim3** [comment]
Update: need to design a data structure that reduces the number of parameters needed to get `introductionF` (and `solChSpecF`) working. Opened up issue #244 .

**Comment by danscime** [comment]
SWHS updated as of d570347

**Comment by AKM11** [comment]
Going to hold off on this until we have adjusted the function a little more.

**Comment by niazim3** [comment]
@szymczdm has broken down the `introductionF` function and implemented it in SSP in commit b7651a0.
GlassBR updated to use `IntroSec` as of commit 6b50bd8.

**Comment by AKM11** [comment]
Shifted this issue to track the implementation of the aforementioned IntroSec.  Can use the same checkboxes as above.

**Comment by AKM11** [comment]
Implemented IntroSec in NoPCM as of commit 4a6e0dfc437150696727c956e68eb078c1a5281a.

**Comment by danscime** [comment]
Implemented to SWHS as of 688bcbbd0c03e90578029236771a1464f6516d79
