### ISSUE TITLE
Design data structure for Solution Characteristics Specification Section

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#244]
As discussed, design is required to replace the overarching functions (`introductionF` and `solChSpecF`) from being large to more easily readable (similar to `RefSec` and `RefProg`).

**Comment by njericha** [comment]
Just noting this was done for Introduction in b7651a0513ca8b3e6f641a3f07134dd8e4b4fa4c

**Comment by njericha** [comment]
Closing since this is now duplicate of #321
