### ISSUE TITLE
BibTeX citations

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#245]
The citation numbers [#] are currently hard-coded into the Drasil DSL.  Ideally the citations will be auto-generated.  For LaTeX this would mean using the cite command together with BibTeX.  There are other priorities at the moment, but this would be a nice detail to get working.

**Comment by njericha** [comment]
This should fix #239

**Comment by njericha** [comment]
I've done some work on this. What is left to do is,
- Add other types of sources (articles, websites, database etc.)
- Add more fields (ISBN, www link etc.)
- Add alternate renderings (APA, MLA etc.)
- **Integrate with the current rendering of Drasil**

But the general framework is done now.

**Comment by njericha** [comment]
The main problem with TeX is that the title "References" shows up twice. The functions in TeX/Print.hs also need some cleaning up.

**Comment by njericha** [comment]
Note: look into https://github.com/backtracking/bibtex2html or
nxg.me.uk/dist/bibhtml/ or www.spinellis.gr/sw/textproc/bib2xhtml/

**Comment by njericha** [comment]
The main implementation of citations is done. #48 covers the in-text citation portion of this issue.
