### ISSUE TITLE
Remove Sentence Structure Functions from Utils.hs

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#246]
As of fcf06db , we now have a separate file for all your sentence structure related needs. For now, I've duplicated a few functions from Utils.hs to SentenceStructures.hs such as foldlSent, foldlsC, and ofThe. I've left these functions in Utils.hs as to not crash everything at once. For now, do something like
```
import Data.Drasil.SentenceStructures 
import Data.Drasil.Utils hiding (foldlSent, foldlsC) 
```
for example. And once everything has been cleared up we can remove these functions from Utils.hs

edit: The file is now called "SentenceStructures.hs" (added an 's') to match the other files in the folder

**Comment by AKM11** [comment]
All repeated items from Utils deleted and everyone's code updated as of commit 97ec6f576469b918b24402d6ed3425f7c8709b49.
