### ISSUE TITLE
Fix whatever I broke.

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#249]
I broke a bunch of stuff between commit d211bcab35376bca126fcec27a6ba22b2221501e and e1fae76c2b32a813b0c52b31cef50e5398607bd0 that now need to be fixed in the examples.

Tiny is working, so use that as a starting point/guide while you work on your examples. Big changes include:
No more NPNC type, now it's NamedChunk. However, the npnc constructors still work (their types have been changed to NamedChunk); they should probably be deprecated if possible and switched over to using nc instead. Another note: NamedChunks are not instances of NounPhrase (nor should they be), so that will likely break a lot of things that weren't done "right" (ie. using `phrase t` where t is a NamedChunk will no longer work, you'll need to use `phrase $ t ^. term` or the new `fterm phrase t` (in Concepts/Documentation) instead. 

CINP is now CI, and commonINP is commonIdea. A few other things were renamed, so please check the commit log. If you have trouble, I'll be around first thing so we can hammer it out.

As always, check off your example when you're done fixing it, and the last person done please close this issue.

- [x] tiny
- [x] glassbr
- [x] gamephys
- [x] swhs
- [x] nopcm
- [x] ssp

**Comment by JacquesCarette** [comment]
The `NamedChunk` parts should be fixed - but I have some doubts about `fterm`.  I've left notes in other commits.  I think this needs discussion before lots of changes are done-then-redone.

**Comment by AKM11** [comment]
NoPCM already seems clear.

**Comment by danscime** [comment]
SWHS updated as of eeccb6c3cc16c0645e81be3405bea12115c99917

**Comment by hmadej** [comment]
A new issue should be opened for the design issue relating to these changes.
