### ISSUE TITLE
Multiplication sign

### ISSUE THREAD

**Issue by Sodaaaa** [JacquesCarette/literate-scientific-software#25]
In glassbr_srs -> 6.2.3 Instance Models -> IM2, the relation between LR, GTF, NFL and LSF is like this:
LR = NFL * GTF * LSF. 
Currently, the multiplication signs are omitted in the output file, but they are quite meaningful in this case. Otherwise, the equation will look like this: LR = NFLGTFLSF

**Comment by szymczdm** [comment]
I'm on it. Pretty sure I know the cause.

**Comment by szymczdm** [comment]
It should be fixed as of now. It shouldn't matter whether the symbol is atomic multi-char or concatenated (they mean different things, but are displayed the same).
