### ISSUE TITLE
Wording of Sentence

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#250]
Trivial/short question, we are conflicted on how a sentence in Non-Functional Requirements should be worded.  Is it preferable to say "Rather than <word>, the non-functional requirement priorities are..." or "Rather than <word>, the priority non-functional requirements are..."?  SRS documentation uses the latter but half the group thinks the former makes more sense. Preference?

**Comment by JacquesCarette** [comment]
I am fine with the former (with 'priorities').  But no strong feeling either way.

**Comment by AKM11** [comment]
Alright, we will use that then. Thank you.
