### ISSUE TITLE
Titleizing "non-factored load"?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#251]
Currently, the `CI` for **non-factored load** is defined as follows (in GlassBR.Concepts.hs):
`nonFactorL    = commonIdea "nonFactorL"    (nounPhraseSP "non-factored load")       "NFL"`

A discrepancy arises when the document would like a titleized version of this term, as instead of outputting _Non-**F**actored Load_ like it's supposed to, the result is actually _Non-**f**actored Load_. Would it be possible to create a function that can titleize words with hyphens within them correctly? Or if I were to create one, is there currently a way to distinguish where another word starts within another?

**Comment by AKM11** [comment]
Think this is fixed as of commit 60d8720b8c34ce1b5b4c8b5136a41ff1055b1ca5.
