### ISSUE TITLE
Precision of Calculations

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#253]
I have been trying to fix the failing test cases and came across a problem.  In SolarHeatingWaterOnly\Python\Testing\energyTest.py, lines 64 and 65 keep failing because, as far as I can tell, the actual value is not within the expected error range.  In this case, I was using the equation 
`params.C_w * params.Mw * (temp - params.Tinit)`
to calculate the new expected energy values without PCM and this worked fine for every other test case except the aforementioned last two (values obtained from SolarHeatingWaterOnly\Python\Testing\loadParamsTest.py).  However, if I change the precision of the error (1e-9 to 1e-8) the code runs fine.  To this end, is the factor of 10 change acceptable or is there some other approach I should take in fixing this error?

**Comment by JacquesCarette** [comment]
This is very much a @smiths kind of issue.

**Comment by smiths** [comment]
@AKM11, yes a relative error of 1e-8 is fine.  This is a very tiny error and nothing to worry about.  The choice of 1e-9 was arbitrary.  It was probably the smallest value we could get away with.   Now 1e-8 is the smallest value.  The problem you are solving is slightly different, so the change is no thing to worry about.

**Comment by AKM11** [comment]
Alright, thank you.
