### ISSUE TITLE
Add instances of Constraints class for use in Data Constraints Table

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#254]
@szymczdm and I where discussing ways of implementing a cleaner way of capturing the idea of these tables. Currently I have something like
```
fricAng = mkGtZeroConst fricAngle   [(:< 90)] (25 :: Integer)
mkGtZeroConst  :: (Concept s, Quantity s, SymbolForm s, Show a) => s -> [(Expr -> Expr)] -> a -> [Sentence]
mkGtZeroConst s other num = [getS s, fmtBF s ((:>  0):other), fmtU (S (show num)) (cqs s)]
```
Where `s` is some concept with a quantity and symbol, and `fmtBF` formats a list of binary functions to something like `x>0 and x<90`.

**Comment by JacquesCarette** [comment]
I think a data-structure that expresses "bounds" would be good.  We could abuse `Expr` to do this, but my feeling is that we'll regret that design choice.

We might need multiple such structures -- bounds on integers are different than on reals, and different again than bounds in R^n.

**Comment by njericha** [comment]
c90c7e05077df16ca09e361b29bc9367406286d5 Shows a good way of solving this now that we have a Constraints class and ConstraintedChunks @JacquesCarette

**Comment by njericha** [comment]
commit 48f6182661d9789ac4be13ca251821e7843ca776 pretty much takes care of this. The implementation of this issue will be handled by #310
