### ISSUE TITLE
Simplify ODE solver in noPCM

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#258]
In issue #255, I mentioned that pydstools is more effort than we need.  pydstools was used because swhs has events in the ode; that is, swhs has to switch the odes being solved as the pcm starts and finishes melting.  The system of odes does not change for nopcm, so we don't need pydstools.

My recommendation is to use the ode solver in numpy.  My guess is that scipy.integrate.ode would work fine:

https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.integrate.ode.html

Numpy is required, but its installation is more standard than that of pydstools.

**Comment by AKM11** [comment]
I am sorry but I am not clear on what this issue is asking me to do.  Am I supposed to remove the use of the pydstool?

**Comment by smiths** [comment]
Yes, you would replace the ode solver from pydstool with the ode solver from numpy.

**Comment by AKM11** [comment]
Spent a lot of time trying to figure out how all these components work but progress is slow.  Any suggestions on how these commands operate (i.e. what do each of the inputs do)?

**Comment by smiths** [comment]
Hi @AKM11 .  The challenge is probably that you haven't run across an ODE solver before.  Before trying to get the code in your program to work, I suggest that you look at some examples.  For instance, the example at:

https://stackoverflow.com/questions/15928750/numerical-ode-solving-in-python

Is fairly nice, although this is a second order ODE, so a bit more difficult than yours.  I like the last answer best.  If that answer makes sense to you, then you won't have any trouble changing your code.

This web-page is fairly good too:

http://modelling3e4.connectmv.com/wiki/Software_tutorial/Integration_of_ODEs

I'm not sure why they integrate explicitly instead of using the ode solver, but this also works.  If you like this example, it would be fine to follow it.

Given his background, I believe that @njericha would be able to help you with solving an ODE.  If your progress is still slow, please let me know.

**Comment by AKM11** [comment]
I have posted a working version as of commit 8ed24cc6c060ea256605748c1ebd6a269a9c8237 but there are still some issues with the resulting error.  Will continue to try and figure out where the extra error is coming from tomorrow but in the mean time someone else can look at the code if they wish.

Also, I apologize for the messy syntax, I will clean it up once the code is fully functional.

**Comment by AKM11** [comment]
Functionally, the code is now running fine.  Margin of error on output is a little higher than what is recommended but aside from that ODE is operational. Considering this issue complete.

**Comment by smiths** [comment]
Sounds good.  Thank you Aaron.
