### ISSUE TITLE
Add missing letters to Greek database and re-order?

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#259]
I needed the symbol for "normal stress" to be a lowercase sigma which I added in e32240a1dcbc3c7237372ad14e6c3134732f8194. There are still missing letters like Mu and Chi which I need in my Theoretical Models and General Definitions which I will add soon. On the topic, I noticed the ordering is based of off their English representation as a word rather than the ordering of the Greek Alphabet (ex. Gamma should be the third letter and come before delta). Should we change the ordering to reflect this?

**Comment by JacquesCarette** [comment]
Well spotted - and yes please!

**Comment by njericha** [comment]
@JacquesCarette Also, we currently have english lowercase all come before "capital A" but the greek is interweaved.

**Comment by JacquesCarette** [comment]
That does seem odd.  Unfortunately https://en.wikipedia.org/wiki/Alphabetical_order does not help.  We should pick a convention (someone else's!)

**Comment by njericha** [comment]
not a scientific resource but still an English resource suggests lowercase first http://www.chicagomanualofstyle.org/16/ch16/ch16_sec062.html

**Comment by njericha** [comment]
Another question that comes up is what to do for letters like epison and phi which have multiple lowercase representations https://en.wikipedia.org/wiki/Epsilon#Unicode

**Comment by smiths** [comment]
I would be fine with using the unicode ordering for these alternate versions of the symbols.  You are correct that there are different representations of the same symbol but I don't think it comes up that often.  Even more rare is alternate versions of the same symbol appearing in the same document.  I'm sure there is a legitimate reason for this on rare occasions, but we shouldn't get too picky on something that is rare.

**Comment by njericha** [comment]
I have now put all the letters in and reordered based on lowercase interspersed with uppercase for now 367f6e55f8a033b6a2acad759f52d2dabbbd4eac

**Comment by JacquesCarette** [comment]
ok.

**Comment by njericha** [comment]
Wikipedia uses upper then lower case interspersed https://en.wikipedia.org/wiki/List_of_common_physics_notations
