### ISSUE TITLE
NoPCM Test Odd Error

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#260]
While try to fix issue #255 I came across a strange problem in python's logic.  It seems whenever I tried to pass a value greater than, say 50 into a line such as `if (params.L < 0.10) or (params.L > 50):` the output would always be false for the greater-than value regardless of where it appeared (e.g. x > 50 or x < 0.1).  I asked everyone else in our group about it but none of them seem to know why this is happening.  This can be worked around by using an 'elif' statement instead of the 'or' (see commit 844f71806fe6e1d41b3e20fb23d7a4ef037b05cf) but I was wondering if anyone knew why this was happening and how it can be corrected (i.e. how to get or to work right).

Keep in mind, static values that are hard-coded into SolarHeatingWaterOnly\Python\verify_params.py work fine, it is only the variables (which have also been checked for discrepancies) that appear to have this problem.

If you need more information, just let me know.  Thanks in advance.

**Comment by szymczdm** [comment]
I could use some more information. Can you point me to the file(s) in question and let me know the steps you've taken in testing it so far?

**Comment by JacquesCarette** [comment]
Have you tried `50.0` instead of `50` ?

Also, python uses "duck typing", so if you pass in something with no L field for params, the comparison might always be false.  Make sure you don't have a typo!

**Comment by AKM11** [comment]
Files of interest include unrecommendedInputTest.py, verify_params.py and (for the sake of example)
Testing\unrecommendedInput\UI02.txt.  We have tried (without necessarily any logic behind it) to 
change the types of variables to floats and integers, tracking the flow of information to the if
statement with print (information reaches the evaluation correctly, something appears to be wrong
with the evaluation) and adding brackets to try and control the order of operation. Some potential
issues suggested include changes in python version (e.g. 2.7 vs 3.5) and quirks in how the 'or'
operator is running (both of which I personally find doubtful).

**Comment by AKM11** [comment]
Okay, think I found the issue. For whatever reason, the warning command was only being raised in specific scenarios (why, I am not sure).  To ensure that the warning would always be raised when referenced, I had to add the command `warnings.simplefilter('always', UserWarning)`.  These issues seem to be working as of commit c2cf925229b91218cba295c1eaf204ac76bdf5db.
