### ISSUE TITLE
Create Ways to Change Indexing of Symbols

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#265]
![2017-06-12 1](https://user-images.githubusercontent.com/26230851/27042815-0f9097f2-4f66-11e7-9e7f-3d31be14b913.png)
To capture this equation in Drasil, I need to be able to add and modify indexes for symbols that are already defined in my table of symbols. For this example, I need to say delta_i and delta_i+1. Also note a similar thing would be needed for ell_s,i and ell_s,i-1. In my table of symbols, I only have "delta" and "ell_s,i" defined.

**Comment by JacquesCarette** [comment]
Two things are really needed here:

1. A semantic way of indexing
2. A way to display it as subscripts

As we are heading towards code-generation very quickly, 1. is very important to deal with.

**Comment by njericha** [comment]
Would indexing for a particular variable be something that is defined with the `UnitalChunk`/ `ConVar` in our Unital.hs file or would indexing be something done in line when you need it in an `Expr` or `Relation`?

**Comment by JacquesCarette** [comment]
I think `Expr`.

**Comment by njericha** [comment]
I would also like to note that there should be a way of adding a prime to a symbol 
![2017-06-14](https://user-images.githubusercontent.com/26230851/27134447-97c02074-50e3-11e7-834d-01adf140b021.png)
Or should these be two different defined quantities (total stress and effective stress). This creates confusion though because sigma is already used for normal stress. 
![2017-06-14 1](https://user-images.githubusercontent.com/26230851/27134655-34cecc8a-50e4-11e7-99c1-d27bbd972250.png)

**Comment by smiths** [comment]
Yes, @njericha , there should be a prime symbol.  sigma and sigma prime are definitely different quantities, but they are related.  The total stress (sigma) is the sum of the effective stress (sigma prime) and the pore water pressure (u).  This is how geotechnical engineers find the load on the soil skeleton (sigma prime).  The characteristics of water are the same for different geotechnical problems, but the characteristics of the soil are different.  Using the concept of effective stress lets the engineers separate out the part that varies from soil to soil.

In this problem the prime means "effective" for any quantity that it is applied to.  In another problem the prime notation might have a different meaning.  I think the prime is similar to a subscript (or superscript) in terms of how it "modifies" a concept.  For instance, We can talk about mass m and then modify it to mass_w, for mass of water.  @szymczdm might want to comment on how concepts are combined?

**Comment by JacquesCarette** [comment]
We need an 'ontology' of combinations/modifiers of concepts and their renderings.  water should exist as a physical quantity (not just a quantity), so that certain modifiers (mass, extent, position, ...) can be applied to them.

Now is just a tad early to really do this.

**Comment by njericha** [comment]
#91 may actually help with this

**Comment by JacquesCarette** [comment]
@njericha how do you see #91 helping?  I see them as mostly orthogonal (the issue is that of indexing of symbols).

**Comment by njericha** [comment]
in my comment https://github.com/JacquesCarette/literate-scientific-software/wiki/WIP---How-to-define-Unitals on issue #91, we can think of an index as a modifier on the Unital. If this is implemented as described, we can call a function inline to index and the subscript will take care of itself.

**Comment by njericha** [comment]
Now that #352 is closed, part 1 of
> 1. A semantic way of indexing
> 2. A way to display it as subscripts
is complete. Right now, they are being rendered as "A[i]" so I will change this to "A<sub>i</sub>". The problem with doing this is that symbols with a subscript won't be able to be indexed. (since you would get double subscripts). I cannot "overwrite" the subscript because I could remove other needed information. (example is K<sub>st,i</sub> which SSP uses as the shear stiffness at slice i). I cannot remove current subscripts because you could not differentiate K<sub>st,i</sub> from K<sub>sn,i</sub> (the normal shear stiffness).

**Comment by njericha** [comment]
I think 4072e8d closes this issue. I found a solution that fixes most of the problems mentioned in my last comment. The only complaint would be that the table of symbols would not include a subscript "i" in the symbol. I think this is acceptable as the definition along with the index convention conveys the intended meaning.
