### ISSUE TITLE
Automate Descriptions for non-QDefinition types

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#267]
Currently, there isn't a way to automatically create a description for Instance or Theoretical Models (i.e. `RelationConcept`s).
In order to avoid the need to explicitly type out the Sentences for each models' description (like in commit 5707410), there needs to be a function that generates the description from the equation (similar to how DataDefs currently autogenerates the descriptions).

**Comment by njericha** [comment]
see #29

**Comment by niazim3** [comment]
Closing this issue since it is essentially the same as #220.
