### ISSUE TITLE
Multiple Symbol Maps being used in examples

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#268]
I noticed in SWHS/DataDefs several different instances of Symbol Map are being created (via symbolMapFun). This also seems to occur in GamePhysics, GlassBR, and SSP.

Every function should actually be relying on the same (existing) symbol map. Likely this just means symbolMapFun needs to be changed to accept a SymbolMap as one of its arguments, instead of a list of symbols, and then each use of symbolMapFun needs to be updated slightly.

To illustrate what I mean, I'll use the GamePhysics example (since it's all easy to see in one place). Currently we have:

```
cpSymbMap :: SymbolMap
cpSymbMap = symbolMap cpSymbols

cpSymMapT :: RelationConcept -> Contents 
cpSymMapT = symbolMapFun cpSymbols Theory

cpSymMapD :: QDefinition -> Contents 
cpSymMapD = symbolMapFun cpSymbols Data
```

However, for the time being, we should instead have (something like):

```
cpSymbMap :: SymbolMap
cpSymbMap = symbolMap cpSymbols

cpSymMapT :: RelationConcept -> Contents 
cpSymMapT = symbolMapFun cpSymbMap Theory

cpSymMapD :: QDefinition -> Contents 
cpSymMapD = symbolMapFun cpSymbMap Data
```

**Comment by niazim3** [comment]
Updated the definition of `symbolMapFun` and its use in GlassBR in commit 69ead51.

**Comment by danscime** [comment]
Updated SWHS 3a1ee675032e29747e80c629cd60810d7f129447
