### ISSUE TITLE
Formally review each others work

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#269]
This is a low priority task for the time being, tackle it when you are looking for a bit of variety or are running low on things to do.

You should each take a deep look at two others' work and create at least 5 issues for each. These issues do not need to be "deep" issues, but they should recommend some improvement(s) that can be made to each example. The issues can relate to the drasil implementation (you may want to start here), missing information from the original documents, etc. etc.

I've randomly assigned you as follows:

- [x] @niazim3 - swhs & ssp

- [x] @hmadej - swhs & glassbr

- [x] @njericha - glassbr & nopcm

- [x] @danscime - nopcm & gamephys

- [x] @AKM11 - swhs & gamephys

Again, this isn't high priority right now, but it will be a good exercise when you're looking for something to work on.

**Comment by smiths** [comment]
I like this issue @szymczdm .  I think it will help everyone to get a feel for the work of others, and having a target of at least 5 issues makes it unambiguous.

**Comment by njericha** [comment]
Added check boxes so we can check off when we have reviewed our assigned examples.
