### ISSUE TITLE
Local Config

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#27]
Need to be able to set up config files local to a project (or perhaps even to each recipe). This will allow greater customization of the final output.

Not sure where to start on this.

**Comment by JacquesCarette** [comment]
This issue is way too solution-driven.  I think you should rewrite it in terms of the actual problem you're seeing.  Then maybe a solution different than what you say above will emerge.

The config file itself might be a hack.  We need to understand what 'choices' need to be expressible, and then design ways to make those choices in a scalable way.

**Comment by szymczdm** [comment]
Right, I wrote that poorly.

The problem I'm seeing is that each example will require different final views, unless we force them to conform to one standard (which I'd like to avoid). This combined with some of the views we've discussed (ex. Verbose data definition descriptions, units with/without parentheses, displaying units in places like data definition descriptions, numbered sections, table width, etc.) means we need a design for choices that can vary between examples.

**Comment by JacquesCarette** [comment]
Right.  And what I was saying is that these 'choices' themselves are of a different nature, and so may each need a different implementation.

In particular, for many of them, we should have "parametric recipes", which take explicit "choice parameters" as input.  In general, a global config file is a poor solution to most problems.

In other words, what I am saying is that most of the views you've mentioned above should be made into an issue of its own, as each might end up having a rather different solution.  Of course, some may end up with the same solution -- but you don't know that in advance.

**Comment by szymczdm** [comment]
This issue and #80 are very closely related. The "real", parametric recipes should have the view configurations (design choices) associated with them.

**Comment by JacquesCarette** [comment]
Right.  So I think this particular issue should be closed.  It will definitely come up again, and the design will be quite different than what is discussed here.
