### ISSUE TITLE
SWHS Potential Changes

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#270]
The SWHS code seems pretty good but I do have a few suggestions for what could be adjusted.  Feel free to disagree with any you feel are unnecessary.

- [x] Body.hs: Shift from the use of multiple `+:+` to `foldlSent []` for each paragraph. Leave special combinators (e.g. `+:+.`, `sC`) as links for there respective sentences.
- [x] Body.hs: In the charts such as _Traceability Matrix Showing the Connections Between Assumptions and Other Items_ terms 1-3 and 6-9, the titles show up as "this Definition" and do not offer clues on their actual identity short of actually following the link.  Perhaps it would be wise to adjust reference code (e.g. `swhsSymbMapTRef`) so that it uses the word as the link as opposed to the generic "this Definition".
- [ ] Modules.hs: Certain ConceptChunks (namely mod_temp_desc and mod_ener_desc) are being identified as nounPhraseSP but the terms themselves are defined as plurals (e.g. energy _equations_).  May want to look into why this is defined this way and whether or not it is necessary.  Change to singular if possible and therefore not as nounPhraseSP?
- [x] Unitals.hs: the term htFusion still employs the `:+:` combinator.  Should probably update that to either `foldlSent []` or `+:+`
- [ ] stable (directory): Completely clear discrepancies from the log.  Not really a pressing issue but it is something that should be done eventually.  Most of them are actually just the addition of new lines to the stable version.

### @hmadej's Additions 
- [x] SWHS -> could replace repeated +:+, with foldlSent or replace (paragraph $ foldlSent) with foldlSP
- [x] remove commented out code
- [x] condense separate TModels into one TModels file
- [x] pull out responsibilities into individual parts for s_3_1_2_bullets
- [x] pull out EqnBlock s4_2_3_deriv into individual parts, could be valuable information
- [x] pull out EqnBLock s4_2_7_deriv into individual parts, could be valuable information
- [x] pull out EqnBlock s5_1_list into individual parts, could be valuable information
- [x] s4_2_5_d1sent_list, s4_2_5_d2sent_list have equations in them that are not written in the standard way (relation or eqnblock) should be pulled out? could be valuable information.
- [x]  acroA "(#)" +:+ S "-" is repeated in likelyChanges

### @niazim3's Additions
- [x] Body.hs: Implement use of `makeTMatrix` to generate **Traceability Matrices**, as they are currently created manually.
- [x] Body.hs: Add the References section from CaseStudies
- [x] TModel1.hs, TModel2.hs, TModel3.hs: I'm not sure if there's a reason why the theoretical models are in 3 separate files; can they be merged into a single `TMods.hs` file? (Also apply `foldlSent` or `foldlSP` to `t1descr`, `t2descr`, and `t3descr`)
- [x] Add a GenDefs.hs file so that **GD1** and **GD2** from CaseStudies can be created.
- [x] Body.hs: There are multiple instances of hardcoded "is the"s (e.g. see `s5_1_list`) and "the...of the"s (e.g. see `assump12`) that can be replaced by combinators defined in SentenceStructures.hs (i.e. `ofThe, isThe, ofThe'`)

Part of issue #269

**Comment by niazim3** [comment]
- [ ] Body.hs: Implement use of `makeTMatrix` to generate **Traceability Matrices**, as they are currently created manually.

**Comment by hmadej** [comment]
SWHS -> could replace repeated +:+, with foldlSent or replace (paragraph $ foldlSent) with foldlSP

remove commented out code

condense separate TModels into one TModels file

pull out responsibilities into individual parts for s_3_1_2_bullets

pull out EqnBlock s4_2_3_deriv into individual parts, could be valuable information

pull out EqnBLock s4_2_7_deriv into individual parts, could be valuable information

pull out EqnBlock s5_1_list into individual parts, could be valuable information

s4_2_5_d1sent_list, s4_2_5_d2sent_list have equations in them that are not written in the standard way (relation or eqnblock) should be pulled out? could be valuable information.

 acroA "(#)" +:+ S "-" is repeated in likelyChanges

**Comment by niazim3** [comment]
- [ ] Body.hs: Implement use of `makeTMatrix` to generate **Traceability Matrices**, as they are currently created manually.
- [ ] Body.hs: Add the References section from Casestudies

**Comment by danscime** [comment]
FoldlSent implemented fully as of 9a7f94600285ceeb0f36e9dac439742270398169

**Comment by danscime** [comment]
TMods created in f2e2ccd80f9529989110e2a88302dc09d35f0ce1 and 21715a8e732741aec29d7da48902bcb1bc67225a

**Comment by AKM11** [comment]
Added self.  Would like to know when the changes Henry mentioned are made.
