### ISSUE TITLE
NoPCM Code Review

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#274]
As part of #269 , here are 5 things to fix within NoPCM

- [x] Create TMods.hs, Definitions.hs, and Unitals.hs to organize what is currently in Example.hs

- [x] Replace `(P $ thing ^. symbol)` with `getS thing` from Utils.hs where used

- [x] Clean up uses of `:+:` to use other functions where possible. See Example.hs line 134

- [x] Add missing or EmptyS sections to Body.hs (not sure how possible this is right now)

- [x] After moving UnitalChunks from Example.hs to Unitals.hs, clean up code so that lines are not 146 characters long. (I believe 80 was the benchmark length)

From @danscime
- [x] Some lines end with a space, consider going through and removing spaces from ends.
- [ ] s5_1_list could probably use enumSimple function for final 3 requirements.
- [x] Fix line lengths to try not to exceed 80 characters.
- [ ] More understandable variable names. Ex. s2_2s and s2_2e
- [x] Some imports from SWHS such as coil_SA are also existent in your Unitals, not sure what the right answer is, but should there be a way to remove duplication?

**Comment by AKM11** [comment]
Fixed second issue as of commit 16240e2b79d5baa0f41ebcb584e8a1b5fc0cf98c.

**Comment by AKM11** [comment]
Completed the first issue and the third issue as of commit 220fc15573af78e1e5c3773c946eef9b99f4792c.

**Comment by AKM11** [comment]
Finished the fifth issue as of commit 81a4b87fe318b9675042135cae4bd6b5969c4f68

**Comment by danscime** [comment]
- [ ] Some lines end with a space, consider going through and removing spaces from ends.
- [ ] s5_1_list could probably use enumSimple function for final 3 requirements.

**Comment by AKM11** [comment]
Completed fourth issue as of commit 0e6aa3c3488d97109ff4af5df0989aaf4607368e.

**Comment by AKM11** [comment]
Fixed issues six and eight as of commit 0d9a495166f5f6c933119d9274e395bd1f8a151d.

**Comment by AKM11** [comment]
The Unitals, Definitions (for the most part) and TMods files are not actually being used.  They are redundant at this point and will eventually be deleted.  As a result, issue 10 is effectively complete.

**Comment by AKM11** [comment]
Completed issues six and nine as of commit 3aa82130e055aefc887ec7264d7c65cb1f5aee9a.

All issues complete.
