### ISSUE TITLE
GamePhysics Potential Changes

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#275]
Looked through the files for GamePhysics and I have a few suggestions for things to do.  Feel free to disagree if you feel any of these points are unnecessary.

- [x] Body.hs/Unitals.hs: Remove redundant syntax from paragraphs.  Not really a huge issue but the brackets and dollar signs in sentences such as `(plural $ physLib)` are not needed.

- [x] Body.hs: On line 381, the hard-coded square brackets can be replaced with the `sSqBr ()` function from Spec.hs.

- [x] Body.hs: On lines 551 and 556, the titles of the input/output variables tables can be replaced with their key-term equivalents.

- [x] Body.hs: Multiple sections including Introduction, General System Description, Specific System Description, and Requirements all have their own auto-generation files that can be used in place of the existing hard-coded paragraphs.
EDIT: Also remember to add the imports to the cabal file

- [x] TMods.hs:  There are numerous instances of the structure `(P $ X ^. symbol)`.  These can be replaced with `getS X` from Utils.hs.

Part of issue #269 

From @danscime

- [x] Try to reduce line lengths so that they don't exceed 80 characters.
- [x] Not sure if you want or need to, but you could remove brackets around most uses of 'phrase' and 'plural' Ex. `S "applied on a set of", (plural CP.rigidBody) `sC` S "determine their new",`
- [x] More understandable variable names in functions such as reqFrame and reqS.

In Modules, TMods,  & Unitals:
- [x] Remove unnecessary dollar signs Ex. `(phrase $ QP.angularVelocity)`
- [x] Uses of ^. term might be able to be replaced by phrase.

**Comment by njericha** [comment]
- [ ] GamePhysics\Modules.hs:3:1: warning: [-Wunused-imports] The import of `Control.Lens' is redundant

**Comment by danscime** [comment]
- [ ] Try to reduce line lengths so that they don't exceed 80 characters.
- [ ] Not sure if you want or need to, but you could remove brackets around most uses of 'phrase' and 'plural' Ex. `S "applied on a set of", (plural CP.rigidBody) `sC` S "determine their new",`
- [ ] More understandable variable names in functions such as reqFrame and reqS.

In Modules, TMods,  & Unitals:
- [ ] Remove unnecessary dollar signs Ex. `(phrase $ QP.angularVelocity)`
- [ ] Uses of ^. term might be able to be replaced by phrase.

**Comment by hmadej** [comment]
use of ^. term cannot be replaced by phrase in TMods & Unitals, phrase outputs sentence not NP.
Left brackets in because it is more readable with brackets.
