### ISSUE TITLE
Using `exp` to create exponentials causes error?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#277]
As mentioned in issue #272, using the smart constructor `exp` in the following manner is causing the following error:
![image](https://user-images.githubusercontent.com/28247301/27234100-ddbd8fec-5289-11e7-998b-e4ecb1e193d7.png)
![image](https://user-images.githubusercontent.com/28247301/27234103-e02bdc84-5289-11e7-908e-cc89b389bb8d.png)
For now, GlassBR uses the following to get the correct result:  ae50e45.
Need to find out why `exp` (defined in **Expr.hs**) cannot be used in this context.

**Comment by szymczdm** [comment]
I have a feeling I know what the problem is and will take care of it as soon as I'm back from my appointment.
