### ISSUE TITLE
Add Data Constraints to no PCM Example

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#279]
Please add data constraints to the no PCM example.  Ideally this will be from importing SWHS, not by copying and pasting.

**Comment by AKM11** [comment]
Now that I think about it, would it be better for the simpler version to build off the more complex one or the more complex version to build off the simpler one?

**Comment by JacquesCarette** [comment]
Definitely simpler from complex.  It is much easier to select information from a large pool than to add information when it doesn't exist.  [I can expand on this if needed.]

**Comment by AKM11** [comment]
SWHS is still writing data constraints this point in time.  Should I import other paragraphs, definitions, etc. that are the same in the mean time?

**Comment by JacquesCarette** [comment]
Yes, please.

**Comment by AKM11** [comment]
Finished importing constraints from SWHS as of commit cdb9db53250c6c5265f506b860f5da6dfeb9869f.  Think this issue is complete.  Will track the import of other material in issue #293.
