### ISSUE TITLE
Referencing a Theoretical Model within a Theoretical Model

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#28]
Currently you can't reference a theoretical model in the description of another theoretical model, since the theoretical model LayoutObj is defined in the "Body.hs" code and the descriptions for the models are defined in the "Example.hs" code. 

This could be fixed just by defining the LayoutObjs for the theoretical models in "Example.hs" instead of "Body.hs", but I'm not sure if that's something we'd be okay with doing?

**Comment by JacquesCarette** [comment]
I think we need to understand what each of these things really mean to understand if we're ok with that.  What do you really mean by 'reference' here?  Link to or reuse parts of?  What you wish to do matters.

**Comment by bmaclach** [comment]
Link to. Sorry for the ambiguity!

**Comment by JacquesCarette** [comment]
Then I would say that you need to split up your models, one per file.  Then you can have an order to the models (as X refers to Y).  The other examples were really small, so it made sense to use a single file.  Once they get bigger, it is best to split them up.  Which, as a bonus, makes it easy to define "base" models and then other models that depend on those.

**Comment by bmaclach** [comment]
Okay, that sounds good. Thank you!

**Comment by njericha** [comment]
This is an issue that is still present in other examples. SSP has 34 of these models/definitions so I'm not sure if we want 34 additional files for each model/definition.

**Comment by JacquesCarette** [comment]
Right, files is not the only way to split things up.  We do need a way to be able to reference models (by their ids?) and 'order' and 'link' them.

**Comment by samm82** [comment]
Bumping now that `addLabels` is merged. - @JacquesCarette who should be assigned to this issue? It seems like we now have the infrastructure to accomplish your fix.
