### ISSUE TITLE
Coupling and Parallel Block for QDef lists in SystemInformation

### ISSUE THREAD

**Issue by hmadej** [JacquesCarette/literate-scientific-software#287]
I added Block container data type for qdefinitions in SystemInformation, and added it to the constructor 68027fb

```
data Block a = Coupled a a [a]
            | Parallel a [a]
```

to get examples working an empty list of Block has to be added to examples:
f9a130d

`([] :: [Block QDefinition])`

- [x] gamephys
- [x] glassBR
- [x] NoPCM
- [x] SSP
- [x] SWHS
- [x] Tiny

**Comment by AKM11** [comment]
Everyone's code seems to be working now. Considering this issue complete.
