### ISSUE TITLE
Abbreviations vs Symbols?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#289]
Currently, in the stable and CaseStudies version of the Document for GlassBR, `LSF` (Load Share Factor), `GTF` (Glass Type Factor), and `NFL` (Non-Factored Load) are in the **Abbreviations and Acronyms** table; however, since the following Instance Model 
![image](https://user-images.githubusercontent.com/28247301/27353102-e01e239c-55d0-11e7-80a6-90b56f008609.png)
uses GTF, LSF, and NFL, should they perhaps be in the "Table of Symbols" (i.e. is it better to say we are using _symbols_ or _abbreviations_ when calculating a value)?

**Comment by JacquesCarette** [comment]
Perhaps what is going on is that `LSF` is used a both a symbol and an abbreviation!  If in the document it appears in text as a short-hand for the phrase (Load Share Factor), then that is an abbreviation; of course, when it is used in a context where it is some kind of variable representing a number, then it is a symbol.

This is actually fairly common, and so Drasil should allow that convention.  For GlassBR, what shows up in each of the tables should be driven by its actual usage.

**Comment by niazim3** [comment]
I agree that it seems to be a common occurrence. In that case, I'll ensure that chunks are in both tables if they are used as abbreviations and in equations as symbols.
Thanks for answering my question @JacquesCarette
