### ISSUE TITLE
Capture 'Monotonic' in Drasil

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#294]
I have "Vertices's monotonic" as a constraint on one of my output variables (specifically (x,y) of slip vertices's). We need a way to capture this idea is Drasil as a constraint. For it's definition, look here https://en.wikipedia.org/wiki/Monotonic_function. Simply put, Monotonically Increasing means the function never decreases, Monotonically Decreasing means the function never increases. In this context, it would mean the (x,y)-ordenents are moving "up and to the right" or "down and to the right".

**Comment by JacquesCarette** [comment]
Right - this calls for having `Forall` in `Expr`.  Then the definition of monotonic can be expressed.

**Comment by njericha** [comment]
Yes, you could right `Forall x1,x2 (x1<=x2  ->  y1<=y2)` to capture (x,y) being monotonically increasing. Although this would require #265 to index.

**Comment by njericha** [comment]
see 10cd325715c98783e207fe6cb0e79962b57938dc...314174e83d0f8d634f2f14efa3a1301d9fa47897 for work on adding forall, element of, and logic statements

**Comment by njericha** [comment]
c8d602f94c5c12ab1729d0edee8e7b645547c274 We now have monotonic! Closing this since the rest of the notation is indexing and relies on #265
