### ISSUE TITLE
Incorporating `glass_type`'s input constraints

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#299]
Since `glass_type` is similar to `nom_thick` in that the input glass type must be an instance of a set (i.e. {AN, HS, FT}). Assuming that `glass_type` should be updated to a `ConstrainedChunk` type as well, it currently isn't possible to assign physical constraints to the constrained chunk `glass_type` due to the fact that "AN", "HS", and "FT" are abbreviations, and therefore, symbols cannot be extracted from `annealedGlass`, `heatSGlass`, or `fullyTGlass`.
I considered changing the abbreviations to symbols using (for example) `Atomic` "AN", but even then, the type would remain `CI` and that wouldn't solve the issue at hand.
Should the types be changed from `CI` (i.e. common idea) to something else like a `VarChunk` so I can access the symbols? Is changing the type the best solution? @palmerst @szymczdm 

(Pulled out from issue #286)

**Comment by JacquesCarette** [comment]
Rather than a specific type, you should consider what information is needed, and then use the classes instead.

**Comment by niazim3** [comment]
Currently, I believe `CI` is an instance of the `NamedIdea` class, which to my knowledge never has a symbol that can be referenced, so I'm not sure how to use the class in this case...

It makes sense that **AN**, **HS**, and **FT** are abbreviations (i.e. are kept as `Strings` rather than` Expr`s) because these acronyms are never directly used in an equation (which comes back to being related to issue #226...) so like @JacquesCarette said, changing the type doesn't seem like the best solution either. 

More directly related to this issue, for now, I created new variables using `V` and implemented their use in the constraints for `glass_type`, but it definitely needs to be improved, so left a _Fixme_ in the comments of **GlassBR\Unitals.hs**
This issue closes as of commit 6ff0da2.
