### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#3]
We should add methods for regression testing of Drasil.  The makefiles used in ggk for doing a diff with the "golden" version of the generated file seems like a good model.  An e-mail has been sent to Dan with the locations of the makefiles in the mgg repo.

**Comment by smiths** [comment]
Hello Dan.  You can access the makefiles we discussed for ggk in the following repo:

https://gitlab.cas.mcmaster.ca/SEforSC/mgg

Specifically you might want to look at the following files:

https://gitlab.cas.mcmaster.ca/SEforSC/mgg/blob/master/code/ggk/Makefile

and

https://gitlab.cas.mcmaster.ca/SEforSC/mgg/blob/master/code/ggk/ctest/Makefile

Hopefully we can do a similar thing for regression testing with drasil.

**Comment by szymczdm** [comment]
@JacquesCarette would these tests be sufficient for now (in regards to #62), or would you need something more specific?

**Comment by JacquesCarette** [comment]
Yes.

**Comment by szymczdm** [comment]
Commit e0df0be8 addresses this issue. We should now be able to quickly and easily test if anything has changed after updating Drasil.
