### ISSUE TITLE
Equations outside of definitions/models

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#30]
I have derivation sections in my SRS which involve displaying equations outside of models or definitions. I've been using the EqnBlock LayoutObj to do this, but EqnBlocks must be formed from Sentences. Does that mean that any of the functionality that has been added or is planned to be added to Expr will  not work for EqnBlocks?

For example, in the section of my SRS shown below, those equations involve derivatives. Functionality for displaying derivatives has been added to Expr, but as far as I can tell that functionality won't work here because EqnBlocks are composed of Sentences, not Exprs.

![derivationexample](https://cloud.githubusercontent.com/assets/18634568/15713229/936ff942-27e3-11e6-98f8-808a3eea4f93.png)

**Comment by JacquesCarette** [comment]
This is a reflection of the fact that the model used for the basic Drasil design was too simple, so some of the LayoutObj are too simple.

Derivations are very important, they need to be supported.  The details still need to be worked out, but this will require a bit of design.  So will have to wait a few days until Dan comes back.

Thanks for the detailed issue, it is very clear.

**Comment by szymczdm** [comment]
I think this issue arose because we removed the capability of writing exprs into sentences somewhere down the line. I do recall it used to be a feature.

This seems like an oversight and EqnBlock should take an Expr instead of a Sentence (which I will resolve momentarily).

This also leads me to believe inlining equations might be an issue as well.

**Comment by szymczdm** [comment]
Closing this issue since it has been resolved for some time. I'll create a new issue for Eqn inlining.
