### ISSUE TITLE
Scientific Notation Looks Incorrect

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#303]
Seperate issue on @JacquesCarette 's request.
`0.01*fraction` is equal to `1.0e-2 * fraction`. The problem is that is looks like `(1.0*e) - (2*fraction)`.
![2017-06-22](https://user-images.githubusercontent.com/26230851/27447074-ad73a8e4-574d-11e7-9e10-74e715d84b77.png)

**Comment by szymczdm** [comment]
I can't find where that's defined in the example (I assumed DataDefs, but I don't have it, did you push?), either way, I just tested it and the exp function works fine and displays properly for me. 

Maybe there was a bracketing issue or I'm missing something. Can you tell me where it's defined and make sure it's been pushed?

**Comment by njericha** [comment]
I am not using exp, that is done automatically by Drasil. I've typed,
```
(Dbl 0.01) * block + (V "k") / ((C nrmDispl)+(V "A"))
```
on line 165 in DataDefs.hs

**Comment by njericha** [comment]
Also, there's not much point to having scientific notation typed with an "e" since we can type "*10^" and have it as a proper exponential.

**Comment by szymczdm** [comment]
So what you're seeing here is actually Haskell's built in "show" function. This is *not* Drasil doing it, hence why the notation is wonky.

**Comment by njericha** [comment]
Oh...So we need a new instance of Show for Expr that are of the form (Dbl x)

**Comment by szymczdm** [comment]
Not exactly, we need to override Haskell's use of "showFloat" for Real valued numbers, since it defaults to scientific notation for anything less than 0.1 or greater than 9,999,999.

**Comment by szymczdm** [comment]
Scientific notation should be fixed, see 0ba8febdcd0e02fff37d30c2ccd89fe8df7ffa2c . Now it's up to you (or the original documentation) on how you want the expression to be displayed (ie. using e^-2, 10^-2, or just as 0.01)
