### ISSUE TITLE
Double sub/super-scripts

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#306]
While working on issue #304 I noticed that SWHS employs double subscripts on some values (see below).

![image](https://user-images.githubusercontent.com/28261578/27486339-3cc40560-57fe-11e7-8613-15d447da1b4b.png)

To create this value, the code runs `(sub (htCap_S_P ^. symbol) (Atomic "min"))` where htCap_S_P already has a sub and super script. This runs fine for HTML but results in an error when trying to generate a TeX file. Advice on how to handle this?

**Comment by njericha** [comment]
#265 should help with this

**Comment by szymczdm** [comment]
@AKM11 Is the symbol (C_P*)min or C_(Pmin)*? What I mean is, is the min/max tied to the whole of C_P^L or is it related to P specifically? As the latter would be easily renderable (if captured properly) as C_{P_{min}}^L

**Comment by AKM11** [comment]
As far as Daniel and I can tell, the min/max is being applied to C_P^L as a whole. The notation is meant to represent the Heat Capacity (C) of Solid (S)/Liquid (L) Phase Change Material (P) so saying (P_min) would be saying the minimum PCM which does not really make sense.
Saying P_min would work as a hack but this would require us to completely redefine of the max/min symbol (i.e. `sub (sup cC cS) (Atomic "Pmin")` as opposed to using `htCap_S_P`).

**Comment by smiths** [comment]
@AKM11 and @danscime are correct, the min is applied to the whole thing.  Cp is the symbol for specific heat capacity.  We want the minimum (and maximum) of the specific heat capacity.  Cp is the specific heat capacity holding the pressure constant (https://en.wikipedia.org/wiki/Heat_capacity).

**Comment by szymczdm** [comment]
Alright, that clarifies things a lot. I'll try and get to this before the weekend.

**Comment by njericha** [comment]
For now, you can do
```
Index (C htCap_S_P) (V "max")
```
as the upper constraint for `htCap_S_P`

**Comment by AKM11** [comment]
@njericha This works in creating the proper output for the constraint values (see commit8f262e146a62dd038e92f6da5b1f6e4457a94731). However, we still have a problem with variables such as:
![image](https://user-images.githubusercontent.com/28261578/28466285-f218fb1c-6df9-11e7-88f4-1a764aff2d7a.png)
where the sub/sup need to be used in the definition of the value's symbol.  That being said, using `Index` for all the constraint values as opposed to a predefined terms we use now might actually be a better idea.

**Comment by njericha** [comment]
I've created #359 for the issue of not being able to index in table of symbols. If that is the only remaining issue than this can be closed @AKM11.

**Comment by AKM11** [comment]
I am not so sure that this issue should be closed yet. The issue still stands that we cannot make double sub/super script commands for TeX and, as @danscime pointed out, we are losing information if terms such as `P` and `melt` are applies to the same command.  I guess a work-around for rendering is available but it would be preferred if these subscripts could be applied separately.

**Comment by njericha** [comment]
#91 should help with applying the P and melt separately. As for double sub/sup, I figured out that it is possible to do double subscript with `{E_P}_{melt}`

**Comment by danscime** [comment]
b250117fc82ba03f03561683dc4c34881fdbec73 and 81fa273485ff0c657d7bd70e72a728b7d186d817
