### ISSUE TITLE
`Quantity` with an `Uncertainty` Field

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#308]
As mentioned in issue #304, creating a new kind of `Quantity` that has an `Uncertainty` field would be beneficial.

**Comment by njericha** [comment]
This would help #310

**Comment by njericha** [comment]
I think we need a quantity that has a typical value too

**Comment by JacquesCarette** [comment]
Yep.  And both.  Might be simpler to create a Quantity with a "free" field of attributes, which can be filled by some record containing a variety of things.  Lenses will insure that the right ones are there.

**Comment by szymczdm** [comment]
@JacquesCarette can you elaborate on that a bit?

**Comment by JacquesCarette** [comment]
What I meant is that instead of creating dozens of data-structures for various kinds of `Quantity`, create one with a free parameter, like

    data FunkyQ a = FQ { <usual fields> ; _rest :: a }

and you (internally) look for things like `Uncertainty`, etc in `_rest`.
