### ISSUE TITLE
Physical and Software constraints in Tables

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#31]
I have the following table in my SRS, which contains columns for constraints on the variables.

![tablewithasterisksexample](https://cloud.githubusercontent.com/assets/18634568/15713350/19e6bfec-27e4-11e6-8cca-5b5d113dc095.png)

I could make this table with drasil by typing out all of the constraints, but that would be tedious and I think it makes more sense to define the constraints on a variable when you define the variable, so that those constraints can be extracted from the variable using " ^. ".

**Comment by JacquesCarette** [comment]
Agreed - that is the right way to do it.  Which means that Constraints, as a "first class" object needs to be created.  As a matter of fact, the same is likely true of typical value and uncertainty!

**Comment by JacquesCarette** [comment]
[I assign some things to myself when they need design.  Not because Dan can't do it, but more as a reminder that this is more than just a bug.  Which is probably silly, and I need to add a 'design' tag instead!]

**Comment by szymczdm** [comment]
Constrained is currently just a type class while we wait on #98, we'll need to sort out some good data structures, or perhaps swap to using "databases" of known information as discussed in the comments of #104 to link a chunk to its constraints.

**Comment by njericha** [comment]
Being addressed in #254
