### ISSUE TITLE
More brackets not being generated

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#311]
What gets printed to html:
`Φc=(λficos(αi)-sin(αi))tan(ϕ')-λfisin(αi)-cos(αi)*FS`

What it should print:
`Φc=(λficos(αi)-sin(αi))tan(ϕ')-` ( `λfisin(αi)-cos(αi)` ) `*FS`

What I have typed:
```
(C shrResC) := ((C normToShear)*(C scalFunc) * cos (C baseAngle) - sin (C baseAngle)) * tan (C fricAngle) -
  ((C normToShear)*(C scalFunc) * sin (C baseAngle) - cos (C baseAngle)) * (C fs)
```

**Comment by szymczdm** [comment]
Are the brackets not being generated in the TeX verison as well? Or is this strictly an HTML issue?
