### ISSUE TITLE
Additional instances of UncertQ needed

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#315]
To use these for the data constraints table, UncertQ will need to be an instance of Symbol Form and Constrained so we can lens those fields. It would also be helpful for these quantities to have a typical value so we can generate the Constraints Tables with just these quantities.

**Comment by njericha** [comment]
Also, for SSP's input data, there are no uncertainty values yet. Would I take a guess on what these values should be and the in the future, you would have an expert determine typical uncertainties.

**Comment by smiths** [comment]
I suggest that you just enter 10% for everything.  (With soil properties, it is actually probably worse than this.)  We can ask an expert at a later time.  By setting everything to the same value, it is a clue that these numbers aren't particularly accurate.  😄
