### ISSUE TITLE
NoPCM and SWHS Cross-Reference

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#317]
In my overview of the contents of the NoPCM and SWHS SRS files, the only notable discrepancies in content (outside of the absence of PCM) appeared to be the removal of: 

- any reference to energy calculations 
- (by extension) the definition of Thermal Conduction and Transient 
- Assumption 20 and Likely Change 5 (refer to the SWHS SRS)

Additionally there was no Traceability Matrices and Graphs section (7) in NoPCM but I assume this is because there is less content that can reference each other? The Characteristics of Intended Reader section (2.3) is also missing but I know that section should be added to the NoPCM SRS.  Aside from this last point, is there a reason why this other material is absent?  If not, should I add it? Thanks.

**Comment by szymczdm** [comment]
I'm going to say yes to adding the missing content. I doubt there was a strong reason for it to be left out ( @smiths can correct me on that if I'm wrong).

**Comment by smiths** [comment]
Yes, I agree with @szymczdm.  Please add the missing content.  There should be Traceability matrices and graphs for NoPCM.  Yes, please also add the characteristics of the intended reader.

Why are the energy calculations removed?  We should still output the energy in the water.  We don't have any PCM, but there is no reason to not include the water's energy.

**Comment by AKM11** [comment]
Please disregard the point on Likely Change 5, that should be removed, misread what the sentence meant.

**Comment by AKM11** [comment]
I think everything that needed to be added has been added. Any other missing content is addressed in issue #312. Closing this issue for now.
