### ISSUE TITLE
More than one equation in the Instance Model table

### ISSUE THREAD

**Issue by Sodaaaa** [JacquesCarette/literate-scientific-software#32]
For my case,  one of the Instance Models contains two equations, like this

![screen shot 2016-06-02 at 4 51 11 am](https://cloud.githubusercontent.com/assets/19175468/15725273/b3984996-287d-11e6-9a06-bc8fab139d0a.png)

Currently there's no way to do this. 
But I'm not sure if it's necessary to consider situation like this. Should I just define B in the Data Definitions section instead?

**Comment by JacquesCarette** [comment]
Yes, in this case, please define B in the Data Definitions.  But "where" clauses may eventually be a good idea to add.

Should this issue be assigned to you then?

**Comment by Sodaaaa** [comment]
Sure, if it's just about defining B in Data Definitions, please just assign it to me.

**Comment by smiths** [comment]
Agreed.  We should define B in a separate data definition and explicitly reference that definition from IM1.  Jingwei, please also make this change in the "manual" version of our documentation in the drasil repository.

**Comment by Sodaaaa** [comment]
Okay, should I keep the "where" clause?

**Comment by JacquesCarette** [comment]
Let's skip that where clause (in the table) for now.  As B will be defined in the DD, it doesn't need a local definition.

**Comment by Sodaaaa** [comment]
Done.
