### ISSUE TITLE
Improve Auxiliary Constants Table

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#320]
For the Auxiliary Constants table show in #314 , it would be great if it could be displayed the same as the Table of symbols.  That is, I would like to see three columns: symbol, description,  units.  If possible, I would then like to add to this a value column, preceding the units column.

@niazim3, thank you for adding the new section and modifying the assumptions.

**Comment by niazim3** [comment]
Issue closes as of commit 80bc3bd. Table is now output as follows:
![image](https://user-images.githubusercontent.com/28247301/27640885-60d6e8bc-5be8-11e7-9b52-498abede2c67.png)

**Comment by smiths** [comment]
Great!  However, the exponential notation is a bit odd (7.17)10^7 would look better as 7.17 x 10^7.  I'll create an issue for @szymczdm .  😄
