### ISSUE TITLE
Add the Auxiliary Constants Table and Section in Examples

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#324]
As mentioned in issue #322, the new **Values of Auxiliary Constants** table (and thereby section) should be added to each example to remove the need for a table separately for **Specification Parameter Values**.

- [x] glassbr
- [x] gamePhyics
- [x] ssp
- [x] noPCM
- [x] swhs

GlassBR already has the new section added as of commit a1e336f (see line 795 of Body.hs), and a finalized format for the table of constants can be viewed in **AuxiliaryConstants.hs**.

**Comment by niazim3** [comment]
@smiths Even though the auxiliary constants table has columns for a chunk's symbol, description, and unit (just like **Table of Symbols**), the constants' symbols still need to appear in the **Table of Symbols**, correct?

**Comment by danscime** [comment]
SWHS 0269490ceb425b3409a88416d4867a40afed3d0e

**Comment by AKM11** [comment]
NoPCM added as of commit e030e511e735bad4fb488a32f9531b6b0983fbb1.

**Comment by niazim3** [comment]
@smiths Since ssp and  gamephysics did not have a separate Table for "Specification Parameter Values", the current output is as follows: 
![image](https://user-images.githubusercontent.com/28247301/27841191-40f45298-60cd-11e7-95b5-fa14f68a8704.png).
Is it better to explicitly state that "there are no constants" or to leave the section out altogether for such examples?
