### ISSUE TITLE
index too large Error?

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#326]
I was try to add the rest of the Instance Models section when I got the following error:

![image](https://user-images.githubusercontent.com/28261578/27648198-c1a82df0-5bfb-11e7-8db9-d6f6032ab130.png)

Does anyone know what this means or how to resolve it?  I honestly do not even know what part of the code could be causing the problem.

**Comment by JacquesCarette** [comment]
This is a call to !! in Haskell that goes wrong.  Somewhere you have a list which is 'too short', and you are indexing past the end of it.  As it is presumably recent, look at the things you changed most recently that might be related to lists getting shorter.

[Generally, we should remove all uses of `!!`, as that is another code smell.  But that may need a bit of design first]

**Comment by AKM11** [comment]
So... does it relate directly to a use of '!!' or can it be anything involving a list?

**Comment by JacquesCarette** [comment]
Eventually because of a use of `!!`, in Drasil somewhere.  The short list might, of course, be far away from the symptom.

**Comment by AKM11** [comment]
Okay, @hmadej helped me find the issue, apparently at some point I had switched one of my placeholder values from a list of lists with two values to a list of two lists with one value each, hence the indexing error.  Thank you for the input @JacquesCarette.
