### ISSUE TITLE
Add chunks for interpolation to GlassBR

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#328]
Hello @niazim3.  Please take a look at the mathematical model @smiths made for the interpolation in GlassBR:  https://github.com/JacquesCarette/literate-scientific-software/blob/master/CaseStudies/glass/Documentation/MIS/MathModelForCalc_q.pdf   (you should also look at the code in /CaseStudies/glass/Implementations/Python_Simplified/Implementation/interp.py -- this is that mathematical model translated to code).

Try to capture this knowledge in chunks in the GlassBR example.  You should end up with a set of QDefinitions that can express this model.  You should make a new .hs file in your example to keep all of these new definitions separate and in one place.  

You will likely run into some things that Expr can't handle right now.  Let me know what is missing as it comes up and I'll modify Expr to make it work.

**Comment by niazim3** [comment]
@palmerst
Having looked over both the code and linked pdf file, I was wondering if it would be possible to see an example of what would be useful as a `QDefinition` chunk type? It seems to me that the Python code just needs to be converted to Haskell code, but I may be misunderstanding the issue's purpose...

**Comment by palmerst** [comment]
We want to be able to generate code for the interpolation module, so we need to have the interpolation math captured in a set of chunks in Drasil.  For instance, the interpolation function y_interp = (y_2-y_1)/(x_2-x_1) * x + y_1  can be expressed as a QDefinition with the Expr:

( (C y_2) :- (C y_1) ) :/ ( (C x_2) :- (C x_1) ) :* (C x)  :+ (C y_1)

where x_1, x_2, y_1, y_2, and x are defined quantity chunks.

**Comment by JacquesCarette** [comment]
You should take deeper advantage of the `Num` instance for `Expr` and use `-`, `*` and `+` directly.  Might have to tweak something to use `/`.

**Comment by niazim3** [comment]
@palmerst I believe the current **Interpolation.hs** file captures the necessary chunks. I'm not sure how you'd like the function `interpolate` (please see most recent commit) incorporated with the actual chunks though...?

**Comment by niazim3** [comment]
@palmerst Can this issue be closed?

**Comment by palmerst** [comment]
There is still missing information that we need.  If you look at https://github.com/JacquesCarette/literate-scientific-software/blob/master/CaseStudies/glass/Implementations/Python_Simplified/Implementation/interp.py we need to be able to generate all of this.

You have captured `lin_interp`, but we still need to capture the other functions as sequences of `Expr`.  Ignore the exception throwing for now.  Also don't worry about making the functions into `QDefinition` -- it won't work for the larger functions.  

Focus on translating everything in the python code to `Expr` (indInSeq might be a single `Expr`, and possible matrixCol as well, but the interpY and Z functions will be sequences of `Expr`).

**Comment by niazim3** [comment]
Update on this issue's status:
Most recent commit shows that the implementation of chunks for interpolation are almost complete... There are a total of 4 `FIXME` comments because I was hoping for some clarification on the implementation of the functions `indInSeq`, `interpZ`, and `matrixCol`. @palmerst

**Comment by palmerst** [comment]
I'm currently working on generating code from this.  Once I'm finished I will be able to get a better idea of what's missing/needs fixing still.

**Comment by niazim3** [comment]
Closed in commits 24663e3...a6c5486.
