### ISSUE TITLE
Table captions shifted to the right in SRS

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#33]
The captions for tables are not centered, but instead shifted to the right. Sometimes this still looks okay, as below:

![drasiltablecaptionshift](https://cloud.githubusercontent.com/assets/18634568/15747734/1781c65e-28aa-11e6-964f-6284c412cab8.png)

But with longer captions, the caption gets cut off:

![drasiltablecaptioncutoff](https://cloud.githubusercontent.com/assets/18634568/15747749/26604308-28aa-11e6-8f04-a4931ef07558.png)

This problem only exists for the SRS Doctype, captions are centered in the HTML docs.

**Comment by JacquesCarette** [comment]
This is indeed odd.  Feels like a bug.

**Comment by szymczdm** [comment]
Took a while to find the bug, but it had to do with table width configuration. Essentially the last column of the table was being (invisibly) stretched off screen to the point that the caption was actually "centered" for the dimensions of the table, not the dimensions of the page.
