### ISSUE TITLE
Remove uses of makeConstraint, displayConstr, and fmtInConstr

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#333]
Update data constraints section to use `inDataConstTbl` and `outDataConstTbl`. 

You may have to update your `ConstrainedChunks` to `UncertQ` and use wrapper to get the types to match. This may also require the implementation of new functions in `Language/Drasil/Chunk/UncertainQuantity.hs`. I made `UncertQ` and instance of `Concept` so it can be wrapped with other concepts using `cqs`. If you're currently using `ConstrainedChunk` rather than `ConstrConcept`, you will probably have to add definition (if it makes sense to) or use `uqcND` ("uncertainty quantity constraint with no description"). See 0fdae8ba7d129ac9cdfafbcb490393e3cb16cb24 and b002319911f7c75240c07bfc22f2b3959d0018e1

edit: I had to use `ConstrWrapper` to get the inputs in a list with the outputs

- [x] glassbr
- [x] gamephysics
- [x] ssp
- [ ] swhs
- [x] nopcm

**Comment by hmadej** [comment]
updated to implement inDataConstTbl and outDataConstTbl but gamephys input and output variables are same, and doesn't use typical value for output.

**Comment by AKM11** [comment]
Added uncertainty to SWHS and NoPCM in commit bd1dcbc5d447764168a46ada31ad5f8b982dc457.

**Comment by AKM11** [comment]
Updated NoPCM input/output table constructors as of commit 365f74b1cc54635dfcfa0f9257749342fcb0867e.

**Comment by niazim3** [comment]
As mentioned in issue #334, a new `UncertainChunk` has been created that is doesn't have a unit or definition field (built off of (constrained) `VarChunk`).

**Comment by niazim3** [comment]
Removed the "Typical Value" column from the output variable constraints table since none of the examples seem to be needing it (commit a1f4adc).
