### ISSUE TITLE
Using 'sqrt' in an Expression

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#335]
I'm trying to implement the following equation: 
![image](https://user-images.githubusercontent.com/28247301/27837660-87385cc8-60b3-11e7-885b-e766ecb0453c.png)
using the following code: 
![image](https://user-images.githubusercontent.com/28247301/27837697-b1aede0a-60b3-11e7-8c55-6d98087aabf4.png).
The following error comes up when I try to `make glassbr`: 
![image](https://user-images.githubusercontent.com/28247301/27837732-f7f3588c-60b3-11e7-823d-5398c73e95a7.png).
@szymczdm 
Does this have anything to do with Haskell's 'math.sqrt' being used instead of a Drasil-defined function?

**Comment by JacquesCarette** [comment]
In Haskell, `sqrt` is a method of class `Floating`.  Because `Expr` is an instance of `Num`, it 'makes sense' to try `Floating` as well.  It might make sense to implement that instance.  [Either that or use the appropriate constructor from `Expr`].
