### ISSUE TITLE
Sqrt Symbol in HTML vs Sqrt Symbol in TeX

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#336]
![image](https://user-images.githubusercontent.com/28247301/27839444-3b4f2c54-60bf-11e7-8da7-94d281587559.png)

How is the `sqrt` symbol implemented in the TeX generation (below)? The HTML generation (above) doesn't currently do that so if I could please get some insight? @szymczdm

![image](https://user-images.githubusercontent.com/28247301/27839699-56bc9e66-60c1-11e7-9618-f7c81f155f94.png)

**Comment by szymczdm** [comment]
Likely the HTML version is just missing the proper unicode character for sqrt. I'll take a look.

**Comment by niazim3** [comment]
Closed as of commit 844638d. Created related issue #337.
