### ISSUE TITLE
De-embed SWHS

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#340]
Here's a list of places where knowledge is still embedded and needs to be pulled out (see #339 for more information) in Body.hs, I've made explicit mention on the first few as a starting point:

- [x] s2_intro (`energy`, `source`, `swhs_pcm`, etc. all captured, but still embedded)
- [x] s2_ksent (`swhs_pcm`, `progName`, etc. still embedded)
- [x] s2_1_par1
- [x] s2_2_contents
- [x] s2_2_end
- [x] s2_3_knowlegde
- [x] s2_3_understanding
- [x] s2_4_intro
- [x] s2_4_trail
... and similarly in the rest of the sections.

Some of this may even need new knowledge capture or changes to odd conventions, as certain things jump out (ex. `phrase CT.heat, S "transfer" +:+. phrase theory ...]`; Why is it all separate? Is there no concept of "heat transfer"?). Either way, this knowledge will still need to be de-embedded.

I've assigned both @AKM11 and @danscime since this will affect both of your work.

**Comment by AKM11** [comment]
Began de-embedding knowledge for s2_intro, s2_ksent and s2_1_par1 as of commit 282c33bf06bd4e1f18efe5d6163676aa30e36938.

**Comment by AKM11** [comment]
Finished de-embedding knowledge from the remaining suggested sections as of commit e93f0a0.

**Comment by AKM11** [comment]
Think I finished de-embedding knowledge from SWHS as of commit 4dd1a1a.  If anyone wants to look it over, feel free.
