### ISSUE TITLE
De-embed SSP

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#341]
Here's a list of places where knowledge is still embedded and needs to be pulled out (see #339 for more information) in Body.hs, I've made explicit mention on the first few as a starting point:

- [x] s1_2_intro (`value`, `slice`, etc. captured, but still embedded)
- [x] startIntro (`slope`, `mass`, `soil`, etc. still embedded)
- [x] kSent (`ssa`, `program`, etc. still embedded)
- [x] prpsOfDoc_p1
- [x] scpIncl
- [x] scpEnd
- [x] orgSecStart
- [x] orgSecEnd
... and similarly in the rest of the sections.

Some of this may even need new knowledge capture or changes to odd conventions, as certain things jump out. Either way, this knowledge will still need to be de-embedded.

**Comment by njericha** [comment]
Closing this now that everything is pretty much done. All that is left is to move the derivations once the Theoretical models are finished.
