### ISSUE TITLE
De-embed NoPCM

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#343]
Here's a list of places where knowledge is still embedded and needs to be pulled out (see #339 for more information) in Body.hs, I've made explicit mention on the first few as a starting point:

- [x] s2_start (`energy`, `source`, `progName`, etc. all captured, but still embedded)
- [x] s2_end (`progName`, etc. still embedded)
- [x] s2_1 (`progName`, `srs`, etc.)

... and similarly in the rest of the sections.

Since NoPCM is also pulling from SWHS, take a look at #340 as well for more examples.

**Comment by AKM11** [comment]
I think NoPCM is clear as of commit 80a7e0e
