### ISSUE TITLE
De-embed GamePhys

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#344]
Here's a list of places where knowledge is still embedded and needs to be pulled out (see #339 for more information) in Body.hs, I've made explicit mention on the first few as a starting point:

- [x] para1_s2_1_intro (`document`, `chipmunk`, etc. all captured, but still embedded)
- [x] s4_1_intro (`physLib`, `game`, etc. still embedded)
- [x] s4_1_2_list (lots of embedded knowledge here, looks like if it's de-embedded, the bullet points will show a very similar pattern)
- [x] s4_2_1_assum1 and 2 (de-embedding the knowledge will show a pattern, which can be used)
- [x] s7_intro
... and similarly elsewhere.

Some of this may even need new knowledge capture or changes to odd conventions, as certain things jump out to you. Either way, this knowledge will still need to be de-embedded.

**Comment by hmadej** [comment]
So by de-embedding, you mean parametrize sentences? I'm not sure how I would remove all those things from the para1_s2_1_intro without it becoming a function with quite a few arguments or creating sentence combinators? is that the intention?

**Comment by JacquesCarette** [comment]
It means, in part, to parametrize.  By the things that really are parameters.  Sometimes the right way to do that is to create sentence combinators, sometimes by new functions, etc.  This is a non-trivial exercise as it requires a fair amount of judgement and design.
