### ISSUE TITLE
Formatting Long Equations in TeX

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#346]
Edit Aug. 10: Tables should now generate correctly in TeX. The remaining issues are;

- [x] large fractions go over the page (Normal Shear Force Ratio derivation)
- [ ] large case expressions in Data Defs go outside the table (Normal Shear Force Ratio)

Jul 6:
- [X] long tables go over the page
> The TeX file currently generates a table of symbols that looks like this,
> 
> ![2017 june 7 2](https://user-images.githubusercontent.com/26230851/27927885-2eb97a9c-625b-11e7-8500-7f8c6fe10873.PNG)
> 
> By manually adding this piece of code after the document was generated, I was able to get the full description in view.  This found in the original case study.
> ```
> \renewcommand{\arraystretch}{1.6}
> \setlength{\tabcolsep}{20pt}
> \begin{longtable*}{l p{8.5cm} l}
> ```
> ![2017 june 7 1](https://user-images.githubusercontent.com/26230851/27927935-5003c996-625b-11e7-9fb3-e3e79e737c47.PNG)
> 
> 
> A similar issue is happening with the long equation blocks in SSP's derivation section but I'm not sure how it fix it.

**Comment by szymczdm** [comment]
Since this is purely formatting, I'm going to tag it low priority. I believe this issue has already come up in the past as well.

**Comment by JacquesCarette** [comment]
I agree that this is lower priority than other things, but it definitely needs fixed too.  So if @njericha gave it a stab, that would be nice!

**Comment by njericha** [comment]
Attempted to fix by adding the appropriate lines to TeX/Printing.hs but caused other tables to not render properly. We may need some smarter condition to know when we need these extra lines and when we don't.

**Comment by niazim3** [comment]
![image](https://user-images.githubusercontent.com/28247301/28336663-d8b70a18-6bd0-11e7-93dc-24e9b72d7974.png)
This is a solution found online, but it's not ideal since it is quite manual... just posting this here so we have a history of what has been attempted...

**Comment by njericha** [comment]
Note the above commit fixes all but equation 14 from the original SSP case study. Equations 14 is a large fraction and does not get automatically split up.
