### ISSUE TITLE
Fixing how "{}" are generated in TeX?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#354]
![image](https://user-images.githubusercontent.com/28247301/28381164-d4a73620-6c87-11e7-9b76-3f48493a7586.png)
The above is a screenshot of the currently generated TeX code and resulting output.
The description for **t** should include the curly braces (as it is present in the original CaseStudies version: 
![image](https://user-images.githubusercontent.com/28247301/28381322-72ac391a-6c88-11e7-9a49-89d667d4e5d0.png)).
Commit 451f324 is an unsuccessful attempt at inserting the necessary \ before the opening and closing curly brace... what needs to be added in order for the **{}** to be properly produced in LaTeX?

**Comment by smiths** [comment]
@niazim3 , to get { to appear in LaTeX  you need a slash before it, like \{.  The same applies for the closing curly bracket \}.

**Comment by niazim3** [comment]
Closed with the help of @njericha, issue was with the way `sCurlyBr` was defined, since it was originally using `S "{" :+: ...` when it should have been using `Sp CurlyBrOpen :+: ...`
