### ISSUE TITLE
Change Source for Risk of Failure

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#357]
The Source for DD1 (Risk of Failure (B)) is listed as [4], the source should actually be Beason et al (1998).  This document has the title "Basis for ASTME E 1300 Annealed Glass Thickness Selection Charts."  It is in our repo under:

1BasisForASTME1300AnnealedGlassThicknessSelectionCharts.pdf

I don't think citations are currently working, so maybe for now you can just put a comment in the code that this change needs to be made.  I don't like to lose information like this, because I won't remember the "mistake" later.  Since it wouldn't take long, could you also please update the original manually written document to use the correct reference.

**Comment by niazim3** [comment]
Commit f6ad3f6. 
Added comment in **DataDefs.hs** that outlined source number as well as a reference to this issue. Added `Source : [7]` to the stable version of the TeX file. Also added the above source as a reference under **References.hs**, however, it may need some formatting and will eventually be added to the list of references to be output.

**Comment by smiths** [comment]
Thanks!
