### ISSUE TITLE
Referencing Consistency

### ISSUE THREAD

**Issue by AKM11** [JacquesCarette/literate-scientific-software#361]
Right now the HTML and TeX files reference items in two distinct ways.
HTML takes the entire string from show and integrates it into the reference, i.e.:
![image](https://user-images.githubusercontent.com/28261578/28467214-1e64f506-6dfd-11e7-8c08-559b3d7e5b62.png)
TeX, on the other hand, has predefined methods for dealing with certain references, i.e.:
![image](https://user-images.githubusercontent.com/28261578/28467289-67dd8482-6dfd-11e7-9e17-a84f2cbb5ea6.png)
which calls on
![image](https://user-images.githubusercontent.com/28261578/28467347-98077000-6dfd-11e7-8c4d-9321a3678513.png)
Note that the predefined terms only exist for certain types.

What I am wondering is whether or not it is possible to make the referencing system consistent, i.e. can we have HTML and TeX only rely on Spec or only rely on their own predefined functions? If so, is there a preference on which method we use?

**Comment by JacquesCarette** [comment]
What the HTML renderer does there is a hack, and it makes the resulting text look awful.  I despise "this" links.  The right way to do it is to have the reference itself be the link.

We need to think harder about referencing.  It is an important problem, and deserves a solidly designed solution.

**Comment by AKM11** [comment]
Okay, have a place to start on HTML then. @JacquesCarette What is your opinion on the TeX method of rendering? Don't all the exclusive rendering methods make `ref` and `hyperref` redundant or is that preferred?

**Comment by JacquesCarette** [comment]
The TeX method is ok -- and is 'the' way to do it in TeX.  We need to build into the HTML that the text of the reference and the link 'overlap', so that what gets linked is the actual reference text as opposed to a proxy.

**Comment by AKM11** [comment]
I was experiments with some alternatives in one of my more recent commits (e6843e565dcb3469cc20deef2a1156ceed6b9eb5) is this what you had in mind for HTML?

**Comment by JacquesCarette** [comment]
I don't know!  I can't quite predict what the output will actually be from the code changes.

**Comment by AKM11** [comment]
Here is a picture of a reference in the output for NoPCM at the moment (note the difference between the Definition reference and the assumption).

![image](https://user-images.githubusercontent.com/28261578/28541756-1aa7a462-7088-11e7-85d7-80ad07f30af0.png)

However, I feel I should mention that making this rendition of the output has other problems associated with it that relate more to another issue (see #360).  I apologize, more specifically I was trying to clarify what you meant by 'actual reference text as opposed to a proxy' but I think I know what you mean now.

**Comment by JacquesCarette** [comment]
Right 'this Definition' is what I meant by proxy.

If we could have "Integration Definition (###) over" where either '###' or 'Definition (###)' is a link would be good.

**Comment by AKM11** [comment]
My main question was answered (thank you @JacquesCarette), I will format the HTML code so that it follows a trend similar to the TeX code.
