### ISSUE TITLE
LICS Slides

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#362]
I like your initial work on the LICS slides.  Rather than google slides, I would have suggested using LaTeX and beamer, and putting the source file under version control in our repo.  You could start with one of the existing presentations in the repo and modify it for your needs.  It is your presentation, so you should do what you are most comfortable with, but I'm confident that if you gave beamer a try, you would like it.  😄 

I move the "Generate all the things" slide a bit earlier in your slide deck.  You might want it even earlier still.  It really is the motivation for the approach we are adopting, so it fits as part of the introduction.

Part of your presentation could focus on how we have used GitHub to facilitate working together.  I think the audience would all understand this and benefit from hearing about our success story.

It would be more difficult to present, but examples of code you have contributed to Drasil could be another thing to discuss.  Not everyone in the audience will know Haskell, and nobody will know Drasil (other than us), but showing a combinator  you added and explaining how it helped, would be interesting.

**Comment by hmadej** [comment]
converted to tex and uploaded to LICS folder, 3318007

**Comment by smiths** [comment]
Thanks @hmadej.  I moved the LICS folder to the Presentations folder, so that it is with all of the other presentations.  I also changed the reference to meme.png so that the slides would compile.
