### ISSUE TITLE
Friction and Cohesion in SSP

### ISSUE THREAD

**Issue by njericha** [JacquesCarette/literate-scientific-software#364]
While indexing all of SSP, I found that the case study applies "index i" _sometimes_ to friction (phi') and cohesion (c'). I am wondering if what the case study says is correct, or if phi and c should always be indexed at slice i or not. There is an example for when;
- phi is indexed and c isn't (see GD3 and IM5)
- c is indexed and phi isn't (see DD10 and IM3)
- both are indexed (see equation 28)
- neither are indexed (see equation 27 and T3)

**Comment by smiths** [comment]
Great question.  This is indeed an inconsistency.  Please add the subscript everywhere.  I had a look at the original code from Brandon (it is in the repo) and he reads in a list of c and phi values.  There is potentially a different value at every layer.
