### ISSUE TITLE
Implement a single Environment context for all table lookup

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#365]
Currently the `C` constructor in `Expr` takes a chunk constrained to be `SymbolForm`, but we need to also ensure that it is a `Quantity` (and possibly other classes down the road).  Since `Quantity.hs` cannot be imported due to cyclic imports, it should instead just take a `Chunk` and use maps to get the `SymbolForm`, `Quantity`, etc. from its `id`.  Making this change will require that we have a way to access these maps throughout the Drasil code.

@JacquesCarette you wanted to look into this so we don't need to redesign this more than once.  You mentioned three possibilities:  

1.  using reader monad
2.  using implicit types
3.  using reify + reflect

**Comment by JacquesCarette** [comment]
What I need is a better sense of the urgency of this.  Could you take a look at this (and the other things assigned to me) and set some milestones.

**Comment by palmerst** [comment]
It's important, but not exactly urgent.  Python generation can do just fine without this since it's dynamically typed.  We won't be able to compile other generated languages until this is done due to type errors.

I added it to the 0.3.0 milestone (Aug 31).

**Comment by smiths** [comment]
From Nov 2, 2017 meeting - we have a working solution that addresses the inherent problem now.
