### ISSUE TITLE
Update Text Files to Reflect Changes made in Issue 363?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#367]
Stemming from changes tracked in issue #363, I was wondering if the plaintext files read in for input when testing glassBR should have the values for plate length and plate width to be in terms of _m_ instead of _mm_ (for consistency with the SRS Document)? Or should the test cases remain as is?

**Comment by niazim3** [comment]
(Also, noting: if a change is required, **calculations.py** needs to be updated to not divide by 1000 (i.e. no unit conversions.)

**Comment by smiths** [comment]
The user will prefer to work with mm.  Therefore, the value should be read in mm and then converted to m.  For this behavior to be correct, we need to change the requirements in the SRS.  For the inputs requirement R1, please say that a and b should be read in mm and then converted to m.  As trivial as it is, I think you should add a new requirement for this conversion of the units for a and b.
