### ISSUE TITLE
Start generating code for each example

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#371]
See glassbr Body.hs and Main.hs for an example of how to do this.  You'll need to add something like this to your Body.hs:

exampleChoices :: Choices
exampleChoices = Choices {
  lang = [Python, Cpp, CSharp, Java],
  impType = Program,
  logFile = "log.txt",
  logging = LogNone, 
  comments = CommentNone,
  onSfwrConstraint = Warning,
  onPhysConstraint = Warning, 
  inputStructure = AsClass 
}
  
example_code :: CodeSpec
example_code = codeSpec' exampleSystInfo exampleChoices

(the glassbr example uses the addModDefs function in example_code -- don't worry about this yet)

Let me know if this produces any errors when running the executable for you example.

- [x] SSP
- [x] GamePhys
- [x] GlassBR
- [x] NoPCM
- [x] SWHS
- [ ] Tiny

**Comment by JacquesCarette** [comment]
Great.

Will option `Program` make sense for `GamePhys`?  That's the one that appears to need the `Library` option the most.  [Also, was `tiny` done?]

**Comment by palmerst** [comment]
No, `Program` doesn't make sense for `GamePhys` -- or at least it won't in the future.  For now no main function is generated unless it is hacked in so `Program` and `Library` don't effect the generated code.

I forgot about tiny!  Added to list.

**Comment by danscime** [comment]
SWHS as of 9277d75e72f84657eaced588bf34cfa54ed22a72

**Comment by niazim3** [comment]
Comments from commit 3a05c0f may be helpful when actually generating code.

**Comment by hmadej** [comment]
I think 482149c and e9317c5 cover the remaining examples and this issue can be closed.

**Comment by JacquesCarette** [comment]
This is a huge milestone!  Good work!
