### ISSUE TITLE
Rendering References in TeX?

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#375]
@danscime and I are having trouble rendering the References section from the changes made in #370.
A warning that shows up when the .tex file is built is "Empty Bibliography" and the pdf that is produced looks like the following 
![image](https://user-images.githubusercontent.com/28247301/28976686-dd7e0b16-790c-11e7-9745-b79b5728392f.png), even though the source code includes all the defined citations 
![image](https://user-images.githubusercontent.com/28247301/28976754-24cad468-790d-11e7-97b6-43dce6278d0f.png)...

Why isn't the Bibliography showing up?

**Comment by niazim3** [comment]
With the help of @AKM11, got references to render in Tex. (Had to configure the settings in editor to add the use of the BibTeX tool).

**Comment by danscime** [comment]
Not sure how to render mine yet on a Mac

**Comment by njericha** [comment]
Run
```
pdfLaTeX
BibTeX
pdfLaTeX
```
in that order if you use TeXworks
