### ISSUE TITLE
Create `GlassType` and `GlassThickness` data-types for GlassBR

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#376]
As stated by @JacquesCarette in comments of commit 6e95430: "...it would be best to create a GlassType data-type, with fields factors and abbr. Then glassTypeFactors and glassTypeAbbr would be a [ GlassType].
Same for the actual/nominal thickness pairs of lists. They should be in the document as a single list of pairs. For actual usage, the information can then be extracted."

**Comment by niazim3** [comment]
@JacquesCarette Would it be easier to keep the data related to `GlassType` and `GlassThickness` as a list of tuples instead of a new _data-type_ and then extract the necessary data from the tuples? Creating new data-types results in a "layer" to unwrap when using the information for display in sentences or in data definitions with Cases; if that is not an issue, I can continue creating the new data-types, however, I was wondering if that does bring up the question on the implementation of data-types for the code generation aspect of Drasil?

**Comment by JacquesCarette** [comment]
You should definitely define type synonyms and use those, rather than hard-coding that the implementation is a list of tuples.   Yes, adding data-structures requires unwrapping - but that is not too onerous, given the extra type-safety you get in return.

I don't understand how this would affect code-generation?

**Comment by niazim3** [comment]
Apologies for the confusion, I was making things complicated by creating a new _chunk_ type for glass thickness and glass type and lens' to extract the factors, abbrs, etc.. 
This issue closes with the help of @hmadej

**Comment by JacquesCarette** [comment]
Good - yes, the code you have just checked in is indeed the solution I was thinking of.  Sorry I was not clear enough!
