### ISSUE TITLE
Compilation error due to ambiguity of :< and :>

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#38]
I'm getting a compilation error due to ambiguity between the :< and :> defined in Expr.hs and the ones imported from Control.Lens in the latest committed version.

Screenshot of cmd for reference:
![error](https://cloud.githubusercontent.com/assets/14371273/15918182/3f70e410-2dd2-11e6-84f0-a17dbe313785.png)

**Comment by szymczdm** [comment]
I can't reproduce this error, can you find out what version of lens you've got?

**Comment by palmerst** [comment]
4.14

**Comment by szymczdm** [comment]
I've got the same. Not sure why this is happening, but you can just modify the import for Control.Lens to:
`import Control.Lens hiding ((:>),(:<))`
and it should fix it.

If it works, commit the changes and we'll see what happens.

**Comment by palmerst** [comment]
Yea, that fixed it -- committed changes.
