### ISSUE TITLE
Review Formatting/Code Cleanup of Examples

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#382]
Please follow @JacquesCarette's updates to GlassBR as a model (6e22663...0228619).

In order to maintain a consistent format throughout the examples, 

-please ensure that indenting is not > 4 spaces
-go through anonymous functions in the examples, and use the `.` operator where possible (i.e. only when doing so would make the function shorter and just as clear)
-please ensure that line lengths do not exceed 80 characters

- [x] GlassBR
- [x] SSP
- [x] Gamephysics
- [x] SWHS
- [x] NoPCM
- [x] HGHC

**Comment by AKM11** [comment]
Reformatted NoPCM code as of commit b232825535caa396117c7512adbe4fd7b3f7d354.
