### ISSUE TITLE
Avoid Using 'id' Lens Where Possible

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#383]
Please remove instances of `import Prelude hiding (id)` where redundant. (As @JacquesCarette stated "We should avoid using the 'id' lens as much as possible.  All such uses should be flagged for review.")

- [x] GlassBR
- [x] SSP
- [x] Gamephysics
- [x] SWHS
- [x] NoPCM
- [x] HGHC

**Comment by AKM11** [comment]
Removed Prelude in NoPCM as of commit b232825535caa396117c7512adbe4fd7b3f7d354.
