### ISSUE TITLE
Allow `Person` to be Created Using Special Characters

### ISSUE THREAD

**Issue by niazim3** [JacquesCarette/literate-scientific-software#386]
`Person` currently takes strings, but there are instances where people have special characters in their names (the implementation of which is not currently possible). An example of this is the editor of "A new requirements template for scientific computing", J. Ralyt**é**.

**Comment by JacquesCarette** [comment]
This is indeed a problem.  It is fine for a smart constructor for Person to be String-driven, but indeed it should be implemented in terms of Sentence internally.

How big a change is that?

**Comment by szymczdm** [comment]
This one should be a fairly simple mechanical change, unless there's a weird import chain or the renderer does something funky.

**Comment by szymczdm** [comment]
Fixed as of 3ce31722870265195c873c4d3cc82d66d9374e71.
