### ISSUE TITLE
SSP broken

### ISSUE THREAD

**Issue by danscime** [JacquesCarette/literate-scientific-software#389]
@szymczdm and I looked through and found that commit c2c241d3292b8df91dec413efe0e73a0a5b025c9 broke the code. So make is giving an error for SSP. Something about Language/Drasil/Code/Imperative/Import.hs
 
<img width="567" alt="screen shot 2017-08-17 at 9 59 43 am" src="https://user-images.githubusercontent.com/28261339/29416012-d2c9b5f0-8332-11e7-9ae4-b4c14697269f.png">

**Comment by JacquesCarette** [comment]
@palmerst you should use better error messages than "not implemented" [i.e. put in the file name and function name in the error], so that when this happens, it is much easier to figure out where the problem arises from.

I think Haskell provides __LINE__ and __FILE__ for just that purpose.

**Comment by palmerst** [comment]
Fixed in  e7c55a3

@JacquesCarette the file name and line number are reported in the call stack.
