### ISSUE TITLE
Problems compiling GlassBR_SRS.tex

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#395]
Can we address the problems with compiling GlassBR_SRS.tex correctly?  From the default output of Drasil, I had to take the following steps to get correct compilation:

1. Copy the files into the same folder as the tex file (as mentioned in issue #214 ).  To get the figures to fit, I also had to adjust the width of the figures using [width=0.5\textwidth] within each of the includegraphics commands.

2. Change the double subscripts in equations from entries like $x_z_1$ to entries like $x_{z_1}$.  This occurred in the table of symbols (page 5 of the pdf, around line 200 for the tex file).

3. Change text entries like  X_z_1 to  X\_z\_1.  The original generated tex for this will compile, but it doesn't shown an underscore where one is expected, but a dot.

Interestingly the symbol $x_{z_1}$ only appears in the table of symbols.  It does not seem to appear anywhere else in the document.

**Comment by szymczdm** [comment]
1 and 2 will be addressed shortly. I don't quite understand what you mean in 3. Also, your last note makes perfect sense as its one of the issues (#396) that needs to be corrected.

**Comment by smiths** [comment]
Thanks for the clarification Dan.  I had forgot about the changes to the symbol map to be used for both the code generation and the SRS.  Item 3 from my original issue is about the LaTeX text.  In the table of symbols the Description field has the LaTeX code "X_z_1."  The intention is almost assuredly to print X followed by an underscore followed by z followed by an underscore followed by 1.  LaTeX however does not interpret the text this way.  I expected the compile to fail, since LaTeX uses the underscore in math mode and the text in question is not in math mode.  It does compile though, just showing weird dots, instead of underscores.  A description of how to typeset an underscore is given at:

http://www.tex.ac.uk/FAQ-underscore.html

My solution has always been simpler, instead of _, I use \_ in the tex code.  In the GlassBR example, this change works fine.

**Comment by szymczdm** [comment]
I just realized you were explaining that you were escaping the underscores (I had to look at your comment source, since markdown uses backslash as an escape as well). What I saw was "instead of _, I use _", but what your source shows is "instead of _, I use \\_"

**Comment by smiths** [comment]
Oops.  I should have previewed my document before commenting.  😄

**Comment by smiths** [comment]
Thanks @szymczdm.  I can see that you have changed the path to the figures and that you have a datafiles folder with a GlassBR sub-folder.  However, where I have been building the srs from is not the correct relative path.  I have been running the glassbr executable from within the .stack-work folder.  Should I be running something different?  I see a dist folder in the code directory, but it didn't seem to be updated when I ran make.  (The generated glassbr SRS doesn't use the new path.)

I'm sure it is a trivial thing to sort out.  I think all I need to know is where to find the glassbr executable that I should be running to create the tex file that I can then run make on.

**Comment by szymczdm** [comment]
After you run make there should be a "build" folder with the up-to-date examples within. That should have the correct relative path.

**Comment by smiths** [comment]
Yep, that works.  😄
