### ISSUE TITLE
Remove code-specific symbols from GlassBR

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#396]
Thanks to both the code gen and docs being built from the same symbolMap, GlassBR has irrelevant symbols in the SRS (ie. symbols for variables/functions that only appear in code).

The best way to solve this would be to parse the document and only keep symbols that are used therein, but temporarily we could just have two Symbol Maps (one for code, one for docs. Generating will error out if we miss relevant symbols, but not if we add irrelevant ones, so this would be a constructive excercise).

**Comment by JacquesCarette** [comment]
Was this issue filed before or after our meeting?  Because we decided not to go with multiple maps.

**Comment by szymczdm** [comment]
Before. What we need now is the context specific tables built from the one global map. 

I'll set up a separate issue for the named stages datatypes soon.

**Comment by szymczdm** [comment]
This is fixed as of 8f35e4639f4e150bb5466e9947d8a78bd6408dee
