### ISSUE TITLE
Change Drasil to a Library

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#4]
Drasil should be changed into a library so that projects can simply import it and define their own documents to generate.  This will facilitate the work on the various summer projects, without a need for everyone to work directly in the literate-scientific-software repo.

**Comment by szymczdm** [comment]
Jacques completed this with his reorganization of the repo. I'm not going to close the issue yet, until we have a "how to" or some such thing written.

**Comment by smiths** [comment]
Yes, I was just going to write you about this.  We should have a how-to written so that people that use Drasil know the steps for importing it into their projects.

**Comment by smiths** [comment]
I don't know if it is typical for Haskell programs, but I would like a make file that I can run to build each of the projects.  As the repo is right now, I can only figure out how to build Main.hs for Dan's examples.  I cannot build any of the other examples (Glass-BR, Game-Physics, SWHS).

**Comment by JacquesCarette** [comment]
This is still an open issue.  We can probably have multiple .cabal files, one per project, for now.  [We should also seriously investigate 'stack'].  It just hasn't been deal with yet.
