### ISSUE TITLE
Change "includegraphics" to "includegraphics[width=0.9\textwidth]"

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#400]
Can we change the includegraphics LaTeX command in the generated tex file to specify the width?  I'm sure that we eventually would like to allow the user to control this, but in the mean time, it would be nice if the figures fit on the page.  I thought 0.9\textwidth would give us a good compromise, but full textwidth would be fine too.

**Comment by szymczdm** [comment]
Made a similar change as of commit 9f1b3432349958a5d278700f451dcd9791ab (set the width to \\textwidth). I can change it to 0.9\\textwidth if you prefer.

I plan on adding a parameter for width (% of page) which can be added to both the TeX and HTML outputs in the future (issue #403).

**Comment by smiths** [comment]
Thanks @szymczdm.  I'm fine with \textwidth, without the 0.9.  I like your idea of adding the % of page parameter, as discussed in #403.  I'll close this  issue.
