### ISSUE TITLE
External library functions with functions as input

### ISSUE THREAD

**Issue by palmerst** [JacquesCarette/literate-scientific-software#410]
External library functions have different signatures in different languages -- we can make a generic version of these calls in GOOL and let the language renderers create the actual calls.  But this doesn't work when some library calls require functions as input (e.g. some ODE solvers take a function for the RHS of the ODE, some just use arrays).  This requires a new function definition that will not be present in the GOOL code in some languages.  A very hacky solution could make the renderers insert the function definition into the GOOL code it is rendering, but this seems wrong.

**Comment by JacquesCarette** [comment]
Please update this issue with yesterday's discussion.

**Comment by palmerst** [comment]
Since all the current GOOL languages support lambda expressions, we will use lambdas for now as the arguments for these types of functions.
