### ISSUE TITLE
PCM, NOPCM

### ISSUE THREAD

**Issue by halonazhao** [JacquesCarette/literate-scientific-software#416]
Hello @szymczdm,
I am doing the NoPCM case. In stable version, it removed all PCM information. But in manual version, there is. Should I just remove all PCM related information in manual version just like stable version did?

**Comment by szymczdm** [comment]
Yes. You may also want to double check that the information still makes sense / is correct.

**Comment by halonazhao** [comment]
I just found there are two SWHS, one with PCM, one without PCM. Now I see.
Thanks.
