### ISSUE TITLE
Printing differentials at the end of an integral

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#43]
There is currently no way to print the differential at the end of an integral, such as the _dτ_ in the example below:

![integral](https://cloud.githubusercontent.com/assets/18634568/16455584/dae46ce4-3de2-11e6-88c8-c224594b75cd.png)

**Comment by szymczdm** [comment]
@JacquesCarette How should we handle this design-wise? Adding a field to the integral would be one way to do it. That would also mean adding a second extra field (to represent the expression being integrated), which would most likely be for the better. So, for example, an integral would be written: 

    Integral (Bound1, Bound2) (Expression to Integrate) (w.r.t. Chunk)

as opposed to the current: 

    Integral (Bound1, Bound2) --Expression to integrate follows

I think I've answered my own question here, as the look of the proposed change makes much more sense to me.

**Comment by JacquesCarette** [comment]
Yes, that is the way to do it.  For consistency, the Sum case should be made the same.

**Comment by JacquesCarette** [comment]
Yes, that is the way to do it.  For consistency, the Sum case should be made the same.

**Comment by JacquesCarette** [comment]
Yes, that is the way to do it.  For consistency, the Sum case should be made the same.

**Comment by szymczdm** [comment]
This is now resolved.
