### ISSUE TITLE
Remove Chipmunk Code

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#431]
I would like to remove the Chipmunk code from the Drasil repo.  It was added 3 years ago by Joseph Seger when he started his Masters.  He didn't write the code; as far as I know, it is just a copy of the original Chipmunk project.

If you are okay with removing the folder Chipmunk2D-master, please comment below.  If not, please let us know why we should keep it.  The modified code (originally by Alex H) is in the new Case Studies repo.

**Comment by JacquesCarette** [comment]
I am definitely fine with removing that folder.
