### ISSUE TITLE
Fractions within Paragraphs

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#44]
This might not be an issue at all but I thought I'd mention it just in case. There are some instances in my manual SRS where there is a fraction as part of a paragraph, such as below:

![fractionwithinparagraph](https://cloud.githubusercontent.com/assets/18634568/16657560/f2b8361c-4430-11e6-89f1-9cfb734ecfa7.png)

I am currently representing this in Drasil as shown below because I can't find a way to actually print it as a fraction. Representing it as I have is still correct, though, which is why I'm not sure if this is a problem.

![fractionwithinparagraphnot](https://cloud.githubusercontent.com/assets/18634568/16657582/018eeeb0-4431-11e6-884c-0ce1c82c63ec.png)

**Comment by bmaclach** [comment]
Here's another example, but this one involves a derivative: 

![derivativeinparagraph](https://cloud.githubusercontent.com/assets/18634568/16659967/60871aa6-443a-11e6-96ce-c873073bc6c5.png)

Again, I could type it out in a Paragraph, similar to the first example, like this:

`S "d" :+: U (temp_PCM ^. symbol) :+: S "/d" :+: U (time ^. symbol)`

But this does not seem like an ideal way to display a derivative in a Paragraph.

**Comment by szymczdm** [comment]
I'm going to close this issue as it will be solved once #67 is tackled.
