### ISSUE TITLE
Problem with GlassBR?

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#441]
The GlassBR SRS seems to no longer contain the data definitions.  I used the latest version of the repo files, ran make and looked in the build folder for GlassBR.  The GlassBR_SRS.tex file compiles, but a big part of it is missing.  @szymczdm, can you please look into this.

**Comment by szymczdm** [comment]
I'm aware of the issue, and pretty sure I know why this happened (I forgot to swap something out after a temporary commit). I'll return it to working order tonight and use a branch if I still need the (currently) modified code.

**Comment by smiths** [comment]
Thanks @szymczdm
