### ISSUE TITLE
Problem with how fractions are printed in EqnBlock

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#45]
I have the following equation in my manual SRS:

![originalexprfraction](https://cloud.githubusercontent.com/assets/18634568/16657688/5cdca2bc-4431-11e6-832d-0f8f84dd19ea.png)

Which I attempted to code in Drasil with the following code, where items including HTC are the 'h' variables, items including SA are the 'A' variables, and items including htCap are the 'C' variables (I think the rest is self-explanatory, but let me know if anything is unclear):

```
EqnBlock (Deriv (C temp_W) (C time) := ((C coil_HTC) * (C coil_SA)) /
                ((C w_mass) * (C htCap_W)) * ((C temp_C) - (C temp_W)) +
                ((C coil_HTC) * (C coil_SA)) / ((C coil_HTC) * (C coil_SA)) *
                ((C pcm_HTC) * (C pcm_SA)) / ((C w_mass) * (C htCap_W)) *
                ((C temp_PCM) - (C temp_W)))
```

But it ended up looking like this:

![exprfractionerror](https://cloud.githubusercontent.com/assets/18634568/16657710/6e045ed6-4431-11e6-9131-ad289c5ea8ab.png)

The second fraction on the right side of the equation is incorrect. I can get the equation to print out correctly by rearranging the terms in my code and adding some extra brackets like so:

```
EqnBlock (Deriv (C temp_W) (C time) := ((C coil_HTC) * (C coil_SA)) /
                ((C w_mass) * (C htCap_W)) * ((C temp_C) - (C temp_W)) +
                (((C coil_HTC) * (C coil_SA)) * ((C pcm_HTC) * (C pcm_SA))) / 
                (((C coil_HTC) * (C coil_SA))  * ((C w_mass) * (C htCap_W))) *
                ((C temp_PCM) - (C temp_W)))
```

But since I think the layout of my first attempt was still correct if BEDMAS rules are followed, this might be something that should be looked into. The problem exists in both the TeX and HTML files.

**Comment by njericha** [comment]
@danscime take a look and see if this is still happening and if you can find a way to fix it?

**Comment by njericha** [comment]
See https://github.com/JacquesCarette/literate-scientific-software/wiki/Explicit-Grouping-of-Expressions

**Comment by njericha** [comment]
```
(C coil_HTC) * (C coil_SA))  /  ((C coil_HTC) * (C coil_SA))   *
((C pcm_HTC) * (C pcm_SA))  /  ((C w_mass) * (C htCap_W))
```
I actually don't think this problem is fixable without brackets. Since / and \* have the same infixr, this will be read from left to right by default as
```
{ [(C coil_HTC) * (C coil_SA))  /  ((C coil_HTC) * (C coil_SA)) ] * ((C pcm_HTC) * (C pcm_SA)) } /
((C w_mass) * (C htCap_W))
```
