### ISSUE TITLE
Tables set to false still increase table counter

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#5]
Currently, tables set to False to prevent the table caption from appearing are still considered tables by the table counter in the .tex document. This shifts the numbering for future tables that are set to True.

For example, in my SRS the first three tables do not require a caption, and are therefore set to False. My fourth table does require a caption, but when set to True the caption reads "Table 4: Input Variables" even though it is really only the first table with a caption. I think it should read "Table 1" instead.

Brooks

**Comment by szymczdm** [comment]
Fixed and tested. Tables set to false should now become part of the longtable* environment (and the captions package will be included in the SRS).
