### ISSUE TITLE
Internal references to start a sentence in HTML

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#51]
Internal references in the HTML file take the form of "this Table" or "this Section", etc. Therefore, if a sentence starts with an internal reference, the first word of the sentence ends up not being capitalized, such as in the example below.

![referencetostartsentence](https://cloud.githubusercontent.com/assets/18634568/16665372/53bc3a7e-4451-11e6-9c19-67c84fcacbeb.png)

**Comment by szymczdm** [comment]
This should be kept in mind when designing #108 as we could simply apply the same grammar rules to our generated content.

**Comment by szymczdm** [comment]
This might be a bit more complicated than I originally thought (or than I think right now), but if we use noun phrases for the "this section"(/Table/whatever), then we will have capitalization rules and whatnot available to us.

**Comment by JacquesCarette** [comment]
If we rephrase a number of things to not use so much 'this XXX', this will become partly moot.  Which I think is a good idea.  Though I am quite sure references will continue to be a headache.

**Comment by njericha** [comment]
This should be fixed with #160 since the reference should automatically start with a capital.
