### ISSUE TITLE
Underscores in Sentences

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#52]
While reviewing Jingwei's example on GlassBR, I encountered issues with underscores being used in Sentences. GlassBR has variables named is_safe1 and is_safe2. When used in Sentences, Latex renders them in text mode and as a result it doesn't render properly, like this:
![image](https://cloud.githubusercontent.com/assets/16506055/16781929/68a6b952-484b-11e6-901b-6762550a02c6.png)

Escaping the underscores could fix this, but I think a better solution would be for Drasil to make Latex include the underscore package, if possible.

**Comment by szymczdm** [comment]
Can you point me to the exact point where this happens?

**Comment by lmawarid** [comment]
Sure, for example, this piece of code for the Table of Symbols:

![image](https://cloud.githubusercontent.com/assets/16506055/16782324/0c1963f4-484d-11e6-8356-8408e31c7db3.png)

comes out like this:

![image](https://cloud.githubusercontent.com/assets/16506055/16782352/3471cf12-484d-11e6-8aec-113603fabd62.png)

Also, in descriptions of Theoretical Models:

![image](https://cloud.githubusercontent.com/assets/16506055/16782385/58438232-484d-11e6-96ca-eb2395c3541d.png)

it causes this:

![image](https://cloud.githubusercontent.com/assets/16506055/16782414/747a4b70-484d-11e6-80e1-c500c436ae2f.png)

**Comment by szymczdm** [comment]
This is two separate issues. First off, the symbol for "is_safe" should have an underscore representation, not an underscore (so this still needs to be implemented, it's going to work similar to things like "Tau" or "alpha").

As for the theoretical model, that "is_safe" should be pulled from the chunk, not written directly, and thus will be fine once the symbol is fixed. All of this is also assuming the context printing is working appropriately.
