### ISSUE TITLE
Inequalities in Sentences

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#53]
Another issue I encountered while reviewing the GlassBR example. There were some instances where inequalities were used in Sentences, e.g. in descriptions of Theoretical Models and in tables in Data Constraints. This leads to problems as Latex doesn't render these properly at all in text mode. For example, this piece of code for the Data Constraints section:

![image](https://cloud.githubusercontent.com/assets/16506055/16782132/41886ba8-484c-11e6-8e00-4aa662f55368.png)

is rendered like this:

![image](https://cloud.githubusercontent.com/assets/16506055/16782140/47fc0332-484c-11e6-958f-0d5ebaff6ec0.png)

As far as I know, strict inequalities must use \textgreater or \textless in text mode, while non-strict ones are only available in math mode. Would it be possible to create some kind of construct to use these inequalities in descriptions?

**Comment by szymczdm** [comment]
These constraints should not be used directly in sentences. The inequalities themselves should be expressions and should be captured within chunks. Currently the chunk type to do this does not exist, but that is coming. I'll leave this open until it's implemented.

**Comment by lmawarid** [comment]
All right. I will tag @Sodaaaa here as this concerns her documentation at the moment.

**Comment by szymczdm** [comment]
This should be solved automatically once #67 and #31 are fully implemented. I'm continuing to leave this open until then, to ensure we take a look back at this.

**Comment by szymczdm** [comment]
This issue should now be closed since we can inline Exprs, we have constraints, and we have the necessary inequalities.
