### ISSUE TITLE
Rewrite specification for q hat in Glass SRS

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#56]
Write a specification for q hat that formally shows how it could be defined using interpolation within a table of values.  This issue is part of the resolution for issue #41 .  Once we have the new specification, we can better determine if it is part of the requirements, or part of the design.

**Comment by szymczdm** [comment]
@smiths do you know when you might be able to get to this issue?

**Comment by smiths** [comment]
Hi Dan.  I'll aim for next week.

**Comment by smiths** [comment]
A specification of the calculation of q from a table of values was added to the MIS folder for GlassBR for commit 19de542.

**Comment by smiths** [comment]
Although I didn't technically write the mathematical model for q hat, I'm still going to close this issue.  If we determine that the mathematical model in:

https://github.com/JacquesCarette/literate-scientific-software/blob/master/CaseStudies/glass/Documentation/MIS/MathModelForCalc_q.pdf

Is the right approach, then it will be straightforward to do the same thing for q hat.
