### ISSUE TITLE
Adding derived units to SI_Units

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#58]
The SI_Units module is currently missing some derived units with special names (e.g. newtons vs kgm/s^2). For me, they are newtons and radians. and I defined them in my ChipmunkUnits module for my project:

```
`----- Named Derived Units -----

newton, radians :: DerUChunk

newton = DUC
    (UD (CC "Newton" (S "force")) (UName $ Atomic "N"))
    (USynonym (UProd [kilogram ^. unit, metre ^. unit,
                      UPow (second ^. unit) (-2)]))

radians = DUC
    (UD (CC "Radians" (S "angle")) (UName $ Atomic "rad"))
    (USynonym (UProd [metre ^. unit, UPow (metre ^. unit) (-1)]))`
```

However, as per Dr Carette's suggestion, these should actually be added to Drasil's SI_Units module to facilitate reuse. I should mention @bmaclach @Sodaaaa as well in case there are units they would like to include.

**Comment by JacquesCarette** [comment]
Done.
