### ISSUE TITLE
Table of Units and Table of Symbols templates

### ISSUE THREAD

**Issue by lmawarid** [JacquesCarette/literate-scientific-software#59]
I tried to use the modules Example.Drasil.Units and Example.Units.TableOfSymbols to generate my table of units and symbols, respectively, and I have noticed a couple of things about them:
1. The current templates implement these sections as 'top-level sections' (section depth 0), but instead in the manual SRS they are actually subsections of the first Reference Material section, so they should have a section depth of 1. 
2. The intro paragraphs for the Table of Units is generic and consistent across the SRSs I've seen, but the intro for the Table of Symbols may need to be varied. For example the PCM SRS talks about heat transfer literature, HGHC talks about nuclear physics literature, and I needed to add extra details about my symbols.
3. Suggestion: this follows from (1) and (2), but would it perhaps be a good idea to make the entire Reference Material section into a template? It could take the tables as parameters, as well as a custom intro paragraph for the Table of Symbols if needed.

**Comment by JacquesCarette** [comment]
Yes, to all 3 points.  This is a very important part of higher-level knowledge capture.  It is great that we've finally gotten to the point where this is not only an issue, but it is possible to deal with it.

**Comment by szymczdm** [comment]
Solved as of 41956a3a09d61f09a6249465080e7d27f0f3ea4c (and we avoided using a Template!)
