### ISSUE TITLE
Unitless Chunks in Data Definition

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#60]
One of my unitless chunks is also the subject of a data definition:

![unitlessdatadef](https://cloud.githubusercontent.com/assets/18634568/16999906/4b0cc334-4e8e-11e6-8804-d8a0fb9a2050.png)

The fromEqn function used to construct data definitions takes the unit as one of its arguments. So when I had defined my own "unitless" unit, I could make the data definition like this:

```
dd4MeltFrac = fromEqn "melt_fraction" dd4descr (melt_frac ^. symbol) unitless
              melt_frac_eqn
```

But since I can't reference "unitless" as the unit anymore, I don't think it's currently possible to create unitless data definitions.

**Comment by JacquesCarette** [comment]
Not using `fromEqn`, no.  But that's a bug in `fromEqn` and, to a certain extent, EqChunk.  It should contain a MUChunk and not force units.  Especially as units ought to be derivable from the equation!

**Comment by szymczdm** [comment]
We should keep this in mind when solving #104, as it seems there's a lot going on in data definitions that can be improved.

**Comment by njericha** [comment]
Closing this now that we have `ConVar` and `UnitalChunk` to represent unitless vs. things with units
