### ISSUE TITLE
Module Guide in Drasil

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#63]
Please convert your Module Guide into Drasil.  This will be possible when Steven merges his branch into Master.  @palmerst can you please add a comment to this issue to give the summer students specific instructions and examples when the code is ready?

**Comment by palmerst** [comment]
(this is copy-pasted from earlier email -- forgot this was created as an issue!)

I have just merged my implementation of MG generation in Drasil to the master branch of the LSS repository.  The MG is generated through a template -- you just have to define some chunks and pass them in.  I'm hoping it will be quick and straightforward to generate the MG!  Please try generating your MG's using the template generator and let me know if it successful in producing generated documents that are representative of your manually created documents (and of course create issues if things are missing).

I have created an MG in my SSP example.  You can use this as a guide to creating your MG.  See modules defined in SSPModules.hs and likely/unlikely changes defined in SSPChanges.hs.  Note that for now you can only generate the TeX version -- the HTML AST has not been updated so it will fail if you try to generate a website version of the MG.  Also note that I have not yet included traceability between requirements/modules and uses diagram generation so these will be missing from the generated documents.
