### ISSUE TITLE
Small typo in MG

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#64]
In the first sentence of section 4 of the MG generated by Drasil, the opening quotation mark around "information hiding" is actually a closing quotation mark, as can be seen in the image below. This is an automatically generated sentence so it is not specific to any one example.

![wrongquotation](https://cloud.githubusercontent.com/assets/18634568/17630056/a33e83ee-608b-11e6-8a87-e1be6dd954d0.png)

**Comment by palmerst** [comment]
Fixed in commit a7cc58a
