### ISSUE TITLE
Acronyms in module names are not fully capitalised in MG

### ISSUE THREAD

**Issue by bmaclach** [JacquesCarette/literate-scientific-software#65]
Since module names are automatically put into title case, acronyms as part of module names are not fully capitalised in the MG product even if they are capitalised in the code. This occurs in the list of modules in section 3 of the MG, as well as in the subsection names in section 4 of the MG. An example is shown below, where "ode" should be capitalised in the module names.

![notcapitalacronym](https://cloud.githubusercontent.com/assets/18634568/17630253/86379794-608c-11e6-86ec-521011456a8b.png)

**Comment by palmerst** [comment]
Fixed in commit a7cc58a
