### ISSUE TITLE
Inlining Equations

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#67]
Ability to add equations in the middle of text (paragraphs) without requiring an EqnBlock. 

This feels like it will solve other issues as well (such as #44).

**Comment by szymczdm** [comment]
@JacquesCarette I've taken a look at this, and the most obvious solution was to allow inlining in Sentence. However, that doesn't work (cyclical imports happen). This is definitely a feature I would like to have, although it may not entirely be necessary (we could "force" the use of equation blocks).

Off the top of my head it seems like we could use a helper function / utility to convert an expression into a sentence. So I'm going to take a crack at that, and leave this comment here as a reminder of why we didn't just inline Expr into Sentence.

**Comment by szymczdm** [comment]
Actually, after thinking about it a bit more (and starting an attempt on it), it seems like converting an expression to a sentence is definitely not the right approach. It's essentially duplicating the import/print code and it would be too tied to the output typesetting (ex. we couldn't just convert something like "a > b" to a sentence, since ">" has a different representation in TeX versus HTML and we would have no way to represent that without **heavily** bloating Sentence).

**Comment by JacquesCarette** [comment]
Right.  You need to be able to 'embed' an equation into a Sentence, not convert it.  It might make most sense to have 2 ways to embed equations, block and inline, but not by 'inlining', just as a representation.

**Comment by szymczdm** [comment]
This is still an interesting issue and definitely one I'd like to tackle soon. Currently, Expr and Spec seem separate, but Expr imports Chunk which imports Spec. Spec (Sentence) would need some means of importing Expr (as our baseline). Our LayoutObjects allow us to have an equation block mixed in with our paragraphs (of sentences), but inlining equations is different.

We could probably get away with creating a new data type similar to SecCons (for wrapping Sentences OR Equations), but I'm not sure if that's good enough, especially since it would add a bit of bloat. Mind you, the bloat would only be apparent when switching between Sentences and Exprs, so it might not be unreasonable (especially with some smart constructors).

Any thoughts?

**Comment by szymczdm** [comment]
@JacquesCarette can you take a look at this? I just spent some time trying to untangle this, and I'm a bit stuck on which direction to go in to get expression inlining working.

**Comment by JacquesCarette** [comment]
Yes, I can definitely look at how to untangle this.

**Comment by JacquesCarette** [comment]
Ok, I know how to fix this, but it is going to take some work.  But it goes in the right direction.

To break the cycle, remove the `NamedIdea` constraint in `C` in `Expr`.  That will break `vars` in `Chunk/Extract.hs`; what it should do is to have an extra parameter, which is a map from ids (as `String`) to `NWrapper`.

The hard part is to create that map.  Right now, I think the simplest is to have each project have a list of the 'input variables', and build a map from that.  Which is "easy" in the sense that it already exists, as it is used to build the table of symbols!  So the main thing to do is to turn that list into a map, then pass it to `vars`.

This is unfortunately more coding than I can do this afternoon.

**Comment by szymczdm** [comment]
That makes a lot of sense. I'll try and get that started tomorrow, I think I've got a fairly clear idea of how to do it now.

**Comment by szymczdm** [comment]
I'm actually going to try and knock this out this weekend, so I've pushed it to the next milestone as it was a bigger issue than expected.

**Comment by JacquesCarette** [comment]
That was indeed a big one.  But it will definitely help!
