### ISSUE TITLE
Add short name for chunks

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#69]
Please add a field for each chunk where the user can supply a short name.  This name would then be used for cross-referencing.  Currently the chunks (like requirements, data definitions, modules etc) are automatically labelled in LaTeX with numbers.  We do not currently have a facility to automatically number chunks in html.  Rather than add numbers in html, we discussed adding short labels for both LaTeX and html.  In LaTeX we could have a configuration option for using the numbers, or switching to the short names.  The short names would be especially useful for generating legible traceability matricies.

**Comment by szymczdm** [comment]
I'd like @JacquesCarette 's input on this. I see a few possible options for implementing short names.

1. Add a "short name" field to the base chunk, then propagate the changes throughout the rest of the existing chunks. This short name field could take a Maybe, so if we don't care about a short name for a specific chunk (i.e. one that is simply a name), we can just include a Nothing.

2. Create a new chunk that is just name + short name. Wherever a shortname is necessary, add the type constraint. Then we need to implement new data types for chunks with shortname vs. without.

3. Something else

Number 1 will mean updating just about everything before we could test it. Number 2 would let us keep our existing examples and codebase and let us slowly incorporate the changes. It would also mean creating a lot more data types. I'm not sure what the cleanest way to do this would be.

**Comment by JacquesCarette** [comment]
We should go with option 2 as far as the class design goes.
Note that, as far as data-structures go, we could actually implement it via option 1 !   If we are careful to use smart constructors more often, rather than constructors, it makes this very easy, and forward compatible.  It does mean some changes now, but it is fairly mechanical.

**Comment by szymczdm** [comment]
I'm going to close this issue as #106 (and potentially #103 if the short names are acronyms) will solve the problem once implemented.

**Comment by JacquesCarette** [comment]
So I think we should be more systematic about this.  What I would prefer is if a (currently failing!) test case were created that would explicitly test for this issue be created.  When #106 and #103 are fixed, we'll expect the test case to start passing.  If it doesn't, then we'd know this is indeed done.  If not, then we know there is still something to do.  As it stands, with this issue closed, we simply won't know!

**Comment by szymczdm** [comment]
I'm not sure where to stand on this issue, can we consider it closed thanks to the introduction of acronyms/abbreviations? Or should we leave it open until we're using the shortnames throughout the generation of references?

**Comment by JacquesCarette** [comment]
Thinking about this further, I think that it would be best to create a new issue (using acronyms/abbreviations in reference generation) and close this one.  The design has been done, now it is on to implementation.

**Comment by smiths** [comment]
@JacquesCarette beat me to it.  :-)  I agree with closing this issue and creating a new one for reference generation.

**Comment by szymczdm** [comment]
Alright, created #160 for the implementation.
