### ISSUE TITLE
Add Automatic Generation of Traceability Graphs in the SRS

### ISSUE THREAD

**Issue by smiths** [JacquesCarette/literate-scientific-software#70]
Please add automatically generated traceability graphs for the SRS.  The automatically generated graphs should capture the same information shown on page 29 of the SRS for PCM.  (You can find the SRS at https://github.com/smiths/swhs/blob/master/SRS/PCM_SRS.pdf).  You should be able to generalize the code that you wrote to generate the figure of the uses hierarchy in your MG.  A sample of one of your automatically generated uses hierarchies is below.

![uses](https://cloud.githubusercontent.com/assets/1422000/17941276/974e00fe-6a00-11e6-8478-4fb1260282ff.png)

Once we have the generated traceability graphs for the SRS documents, we should have a look to see if any pattern emerges from the pictures.

**Comment by njericha** [comment]
@smiths I'm just going through old issues and am wondering if this has been completed yet?

**Comment by smiths** [comment]
@palmerst wrote code to automatically generate the traceability graphs in the SRS and the uses hierarchy in the MG.  However, I don't think this code was fully integrated into Drasil.  @palmerst , can you please clarify the status of your auto graph generating addition to Drasil?

**Comment by palmerst** [comment]
This is completed.
