### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/literate-scientific-software#73]
Right now, Drasil compiles with tons of warnings.  There should be none.

I can't assign this directly to @szymczdm or @palmerst as it is really a shared issue.  So both it is.

**Comment by palmerst** [comment]
I went through the warnings and fixed them.  They were all essentially trivial -- mostly incomplete pattern matches and name shadowing -- so I just fixed them all.  There are now zero compiler warnings.
