### ISSUE TITLE
Move global concepts out of examples and into Data.Drasil

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#76]
Concepts like "assumptions", "data definitions", etc. need to be moved somewhere global (I'm thinking Data.Drasil.Concepts.Documentation or something of that ilk).

Other concepts _should_ be moved, things like "boiling", "latent_heat", or "coil". Not sure how to separate the namespace for them. I'm going to look at them a bit more in depth to see which are completely generic and can be separated, from those that are example specific (and possibly named poorly).

@JacquesCarette ideas for Concept namespaces would be great. I'm thinking of having a "Data.Drasil.Concepts.Thermodynamics" (for latent heat, conservation of energy, etc.), "...Concepts.PhysicalProperties" (for things like dimensions, volume, surface area, etc.), and I'm not sure where I should put things relating to phase changes like "boiling", "melting", etc.

**Comment by JacquesCarette** [comment]
Regarding concept namespaces: let's deal with that like we have done for the rest of Drasil, namely let's fake it for now, and refactor as we better understand the problem.  These namespaces will form a sort of ontology, and that's a big domain; so we don't want to overthink it!

Your starting suggestions are great.  My hunch is that "boiling" could go into `...Concepts.PhysicalProperties.Materials` or something like that.  This is where @smiths is likely to be able to guide us!

**Comment by smiths** [comment]
This should not be a hierarchy, but more like a dictionary where there are multiple paths to get to the same word/concept.

For now, lets put boiling and melting in Thermodynamics.

**Comment by szymczdm** [comment]
Done.
