### ISSUE TITLE
Correct "FIXME"s in Example/Drasil/SWHS/Concepts.hs

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#78]
Some of the CCs should actually be UCs and should be placed elsewhere.

**Comment by danscime** [comment]
Only 2 FIXMEs left.
- Use compound nounphrases instead of pn/cn
- Temporarily have to manually create the compound phrase, because it uses acronym and a sentence.

Not sure what to do for these two.

**Comment by szymczdm** [comment]
The first one should be fairly easily doable, just use "nounPhrase" or "compoundPhrase" where necessary. If you're not sure what to use, check out the haddock documentation (`make docs` from the code folder, open up index and find the appropriate file, in this case Language.Drasil.NounPhrase I believe).

As for the second one, that would be a separate issue.

**Comment by JacquesCarette** [comment]
So does this mean this one is done?

**Comment by danscime** [comment]
Yes but I will add the new issue for  the compound phrase that has an acronym and sentence.
