### ISSUE TITLE
Extract Common Units

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#84]
Extract common units from the examples.

@JacquesCarette should I follow your example of putting them into SI_Units, or separate into namespaces?

**Comment by JacquesCarette** [comment]
Put the standard units (i.e. those you can find on the web on lists of 'standard' units) there, and the extra in separate namespaces.

**Comment by szymczdm** [comment]
Done. I did move some units into their own namespace, and others are still in SI_Units, so there will need to be some reorganization at some point, but that will need to be done for more than just Units.
