### ISSUE TITLE
Clean up GamePhysics example - Unique chunks

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#88]
Clean up the existing game physics example to (hopefully) reveal more patterns/commonalities.

**Comment by szymczdm** [comment]
By "clean up" I mean removing as much duplication as we can, creating new combinators, etc. It will be an ongoing task over the summer, but we should get the first pass done soon.

**Comment by JacquesCarette** [comment]
So is this a good issue?  It feels too broad and unfocused.  Yes, it is being worked on.  If there are specific things, they should be made into (separate) issues.  Now that we have Henry working on this, and as long as he knows that he's supposed to "aggressively" clean it up, we're good.

**Comment by szymczdm** [comment]
You're right, it is a bit too broad, I'll try to pare it down a bit, namely we want to remove all duplication of concepts so that each has a unique source.

**Comment by szymczdm** [comment]
@hmadej I'm assuming this is done? Can you confirm and close the issue if so?

**Comment by hmadej** [comment]
Yes, from what I can see this is complete, may have to clean up the new sections being added, such as User Characteristics and Collision Diagrams
