### ISSUE TITLE
Unitless

### ISSUE THREAD

**Issue by Sodaaaa** [JacquesCarette/literate-scientific-software#9]
Some of the symbols are unitless. Might need defn for "unitless".

**Comment by smiths** [comment]
I agree that explicitly saying unitless is a good idea.  I do not know how it is internally represented in drasil, but in the output the string "unitless" would be fine.  Dan, is this something you can add?

**Comment by JacquesCarette** [comment]
We had a discussion about this issue this morning.  Yes, we have to have symbols (quantities to be precise) which are unitless.  However, it does not make sense to have unitless-unital quantities.  There are some technical issues to fix to deal with this nicely, but we're on it.

**Comment by JacquesCarette** [comment]
I assigned Dan for now, but I understand that this issue might need me too.

**Comment by szymczdm** [comment]
I tried to create a data type with a constructor for Quantity and Unital, but I'm not sure where to go from there. My thought process so far is either the new data type needs to become an instance of Chunk, Concept, etc. or there will need to be some helper functions to do anything. I'm not sure what the "user" should see in this case / where and how the new data type will be used.

Related is ["Units in Data Definition descriptions"](https://github.com/JacquesCarette/literate-scientific-software/issues/24) which I believe will be solved once this is solved.

**Comment by JacquesCarette** [comment]
This is now fixed with the introduction of `MUChunk`.  It may well be that other things also need fixed to fully deal with all the repercussions, but this precise issue is fixed.
