### ISSUE TITLE
Should we have a unitals namespace?

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#92]
Unitals tend to be example specific, so they are not easily pulled out. 

Not sure if we should have "Unitals" namespaces in the same way as concepts and quantities, because there would most likely be very few of them, (at least, prior to parameterization as mentioned in #91).

It feels like this will become more clear after the cleanup of examples is finished.

**Comment by JacquesCarette** [comment]
This issue is not very clear to me.  It probably needs to be expanded with an example or two.  I'm sure that when you're staring at a particular Unitals.hs file, trying to pull stuff out, it is obvious that there is design to be done.  But what you wrote isn't enough.

**Comment by szymczdm** [comment]
Since the most recent redesign, this is no longer an issue. Unitals can (and should) be pulled out into the Quantities namespace, since they are just quantities (with units and symbols as opposed to "maybe" having them).
