### ISSUE TITLE
Fix sloppy conventions throughout the examples

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#93]
A lot of chunks in the examples use sloppy naming conventions. ie. the "name" of a chunk will be something like "p" and it's description will be "position". This flew under the radar until now because it wasn't causing problems. However, thanks to the parameterization of things like "Table of Symbols", it's very obvious that things need to be changed.

We may need to discuss how to approach this, but from what I'm seeing the following is what should happen:

1. Fix names to be meaningful (ex. "position" instead of "p").
2. Correct vague/scant descriptions (ex. "The rate of change of a body's orientation" instead of "angular velocity"; Note: this particular example has already been corrected)
3. Fix the existing parameterized recipe(s) to use the appropriate field (ex. Table of Symbols lists a "description" which is actually just the "name" of the chunk the symbol belongs to, so we should update the recipe to use ^. name instead of ^. descr).

Overall I think that will lead to much more complete and readable examples.

**Comment by szymczdm** [comment]
I think this has been fixed for the most part, but let's just have a quick once-over to confirm. Namely we need to look at ensuring we have meaningful naming conventions (so the id, term, and defn for a chunk should all be meaningful) and filling in/correcting missing/vague definitions.

Once you've double checked your example for these things, please check it off here: 

Naming conventions
- [ ] gamephys
- [ ] glassbr
- [ ] pcm
- [ ] ssp
- [ ] swhs
- [ ] tiny

Vague/Missing Definitions
- [ ] gamephys
- [ ] glassbr
- [ ] pcm
- [ ] ssp
- [ ] swhs
- [ ] tiny

After every box is checked, we can close this issue. For those of you with missing (or FIXME) definitions, we'll need to fill those in.

**Comment by AKM11** [comment]
Is there any particular source you would like up to use for definitions?

**Comment by szymczdm** [comment]
I think @smiths would be the best person to answer that specific question (and I'm sure he can help us come up with some definitions we can all agree on as well 😆 )

**Comment by szymczdm** [comment]
Note there is an almost identical issue to what I just mentioned in #105 with some additional details.

**Comment by AKM11** [comment]
Dr. Carette gave an answer in issue #162 if it helps.

**Comment by smiths** [comment]
If there are any questions about specific definitions, please let me know.  Google search, and some engineering judgement, will often given you a good starting point, but if there is any doubt, you can create an issue and we can discuss.

**Comment by AKM11** [comment]
PCM more or less clear as of commit ff7eaed3673cbf8c7b127329147b5cda7a445ce6

**Comment by AKM11** [comment]
Actually, if possible I would like someone to verify that `ht_gen_vol`, `ht_xfer_CW`, `time_final`, and `temp_init` have acceptable definitions.

**Comment by njericha** [comment]
The entirety of my Units have missing definitions but the nounPhrase part is treated as the definition. Example, ri = 
uc' "R_i" (cn "shear resistance without the influence of interslice forces for slice i") fixme (sub cR lI) newton
Should this be moved to the definition since table of symbols looks at the nounPhrase to find the description

**Comment by JacquesCarette** [comment]
@AKM11 : you should probably specifically include @smiths on such messages.

@njericha : yes.  And then ask @smiths to double-check.

**Comment by njericha** [comment]
If I move the current term to the new description, the table of symbols function will have to be changed to find the description of unitals rather than the term. This would also affect other examples and require everyone to move their terms to definitions

**Comment by JacquesCarette** [comment]
Hmm, I think @szymczdm has looked at this before (it sounds familiar).  And he held off on making some changes because of similar reasons.  So I'll let him handle this one.

**Comment by njericha** [comment]
Fixed as many definitions as I could here 28acb16f410070473764c827d75918ab26d60056 except for; residual shear stiffness, residual shear stiffness, and effective cohesion since I could not find an adequate definition for them. I also do not have a solution for the unitals which have a description as their name as described in my previous comments.

**Comment by danscime** [comment]
In SWHS Unitals, there are missing definitions for some tau symbols and melt fraction. The terms are things like "ODE parameter for liquid PCM", "ODE parameter for water", and  "melt fraction". Should I create the definitions just out of the term? Or are we removing the need for definitions for certain terms?

**Comment by smiths** [comment]
@szymczdm would be better able to answer the question on whether we are removing the need for definitions.  The symbols tau and eta do not have a standard physical meaning.  There purpose is to make the equations easier to read and present.  The "definition" of tau and eta is really the equation that defines them.  I don't think we can have equations in definitions though.  If you need a text definition for tau and eta, I suggest you describe them as derived parameters, based on ... (list the parameters they are based on).

For melt fraction, you can express this in words as a fraction by describing the numerator and the denominator.  The existing SRS and equations should help you with this.

**Comment by niazim3** [comment]
Does an abbreviation of a term count as a _meaningful_ name (e.g. `sd` or `standOffDist` for "stand off distance" from **GlassBR**)? This particular term also has x, y, and z components related to it that are already named `sdx`, `sdy`, and `sdz` which are alright as they are but are not of much use if `sd` is not specific enough...

**Comment by JacquesCarette** [comment]
This issue seems to have exploded into all sorts of stuff.  I don't really follow anymore what's 'live', what's fixed, what the new question is really all about, etc.  Seems like time to split it?

**Comment by AKM11** [comment]
All of HGHC's terms (mostly equations) have definitions already and its variables already seem self explanatory.  I will check it off on the list.

**Comment by niazim3** [comment]
GlassBR updated as of commits 4740221 and 462023f.

**Comment by njericha** [comment]
see issue #227 for SSP
