### ISSUE TITLE
Add Space / QType to master branch

### ISSUE THREAD

**Issue by szymczdm** [JacquesCarette/literate-scientific-software#99]
I just took a quick look, and adding the ability to use Steven's "QType" (or "Space" in my case) to make the merge easier would actually involve a lot of effort on this end.

I've created the module "Language.Drasil.Space" and will commit it shortly, but I think it would be best to leave implementing it into the chunks until we've split Symbol and Quantity. Otherwise it's going to necessitate a lot of changes which will ultimately need to be changed again very soon.

I'm not sure how to proceed. If I start the hierarchy redesign, Steven may have to wait a few days before he'll be able to merge his work in. Then the merge will still be tedious. However, if I were to add "typ" to Quantity before the split, every single example would break and need the addition of the "typ" parameter in a multitude of places (as well as a new (or modified existing) data structure). Then everything would need to be separated in the following pass.

@JacquesCarette , @smiths , @palmerst : What would you be most comfortable with to proceed? Should I jump into the redesign, or try to make the merge a bit easier?

**Comment by JacquesCarette** [comment]
I can see that.  Make the split of symbol asap, and then this can proceed in parallel.

**Comment by szymczdm** [comment]
I think it should now be possible for @palmerst to merge his changes in without outright breaking anything. Then finishing the updates to Quantity and SymbolForm should be straightforward and mechanical.
